type = "package"
schema_version = "2.0.0.dev3"
name = "utl-ts"
parent = "package"
ftype = "TS6"
multi = true
subtype = "utility"

[dims.time_series_names]
value = "len(time_series_names)"

[blocks.attributes.fields.time_series_namerecord]
type = "record"
description = "xxx"

[blocks.attributes.fields.time_series_namerecord.fields.names]
type = "keyword"
description = "keyword to specify the names of the time series. The 'NAME' keyword can be used as a substitute for 'NAMES'."
aliases = [
    "name",
]

[blocks.attributes.fields.time_series_namerecord.fields.time_series_names]
type = "array"
description = "Name by which a package references a particular time-array series. The name must be unique among all time-array series used in a package."
tagged = false
dtype = "string"

[blocks.attributes.fields.interpolation_methodrecord]
type = "record"
description = "xxx"
optional = true

[blocks.attributes.fields.interpolation_methodrecord.fields.methods]
type = "keyword"
description = " xxx"

[blocks.attributes.fields.interpolation_methodrecord.fields.interpolation_method]
type = "array"
description = "Interpolation method, which is either STEPWISE or LINEAR."
tagged = false
dtype = "string"
shape = [
    "time_series_names",
]

[blocks.attributes.fields.interpolation_methodrecord_single]
type = "record"
description = "xxx"
optional = true

[blocks.attributes.fields.interpolation_methodrecord_single.fields.method]
type = "keyword"
description = " xxx"

[blocks.attributes.fields.interpolation_methodrecord_single.fields.interpolation_method_single]
type = "string"
description = "Interpolation method, which is either STEPWISE or LINEAR."
tagged = false
valid = [
    "stepwise",
    "linear",
    "linearend",
]

[blocks.attributes.fields.sfacrecord]
type = "record"
description = "xxx"
optional = true

[blocks.attributes.fields.sfacrecord.fields.sfacs]
type = "keyword"
description = " xxx"

[blocks.attributes.fields.sfacrecord.fields.sfacval]
type = "array"
description = "Scale factor, which will multiply all array values in time series. SFAC is an optional attribute; if omitted, SFAC = 1.0."
tagged = false
dtype = "double"
shape = [
    "time_series_names",
]

[blocks.attributes.fields.sfacrecord_single]
type = "record"
description = "xxx"
optional = true

[blocks.attributes.fields.sfacrecord_single.fields.sfac]
type = "keyword"
description = " xxx"

[blocks.attributes.fields.sfacrecord_single.fields.sfacval]
type = "double"
description = "Scale factor, which will multiply all array values in time series. SFAC is an optional attribute; if omitted, SFAC = 1.0."
tagged = false

[blocks.timeseries.fields.timeseries]
type = "list"
description = "xxx"

[blocks.timeseries.fields.timeseries.item]
name = "timeseries"
type = "record"
description = "xxx"

[blocks.timeseries.fields.timeseries.item.fields.ts_time]
type = "double"
description = "A numeric time relative to the start of the simulation, in the time unit used in the simulation. Times must be strictly increasing."
tagged = false

[blocks.timeseries.fields.timeseries.item.fields.ts_array]
type = "array"
description = "A 2-D array of numeric, floating-point values, or a constant value, readable by the U2DREL array-reading utility."
tagged = false
dtype = "double"
shape = [
    "time_series_names",
]
