# autogenerated file, do not modify
from pathlib import Path
from typing import Optional, Union

import attrs

from flopy4.mf6.package import Package
from flopy4.mf6.row import Row
from flopy4.mf6.spec import field, path


@attrs.define(kw_only=True, slots=False)
class Fmi(Package):
    @attrs.define
    class PackagedataRow(Row):
        flowtype: Union[float, str]
        fname: Path = path(converter=Path, inout="filein")
        aux: tuple = ()

    save_flows: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    flow_imbalance_correction: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    packagedata: Optional[list[PackagedataRow]] = field(
        default=None,
        block="packagedata",
    )


FmiPackagedataRow = Fmi.PackagedataRow
