# autogenerated file, do not modify
from typing import ClassVar

from pydantic.dataclasses import dataclass

from flopy4.mf6._types import FloatArrayLike
from flopy4.mf6.package import CFG, Package
from flopy4.mf6.spec import field


@dataclass(config=CFG, kw_only=True)
class Ic(Package):
    dfn_name: ClassVar[str] = "gwt-ic"

    export_array_ascii: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="export array variables to layered ascii files.",
    )
    export_array_netcdf: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="export array variables to netcdf output files.",
    )
    strt: FloatArrayLike = field(
        default=0.0,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
        longname="starting concentration",
    )  # type: ignore[assignment]
