# autogenerated file, do not modify
# ruff: noqa: E501
from pathlib import Path
from typing import ClassVar, Optional

import numpy as np
from attrs import Converter
from numpy.typing import NDArray
from xattree import xattree

from flopy4.mf6.converter import structure_array
from flopy4.mf6.package import Package
from flopy4.mf6.spec import array, field, path
from flopy4.utils import to_path


@xattree(kw_only=True)
class Ist(Package):
    multi_package: ClassVar[bool] = True

    save_flows: bool = field(
        block="options", default=False, longname="save calculated flows to budget file"
    )
    budget_filerecord: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="fileout"
    )
    budgetcsv_filerecord: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="fileout"
    )
    sorption: Optional[str] = field(block="options", default=None, longname="activate sorption")
    first_order_decay: bool = field(
        block="options", default=False, longname="activate first-order decay"
    )
    zero_order_decay: bool = field(
        block="options", default=False, longname="activate zero-order decay"
    )
    cim_filerecord: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="fileout"
    )
    cim: bool = field(block="options", default=False, longname="cim keyword")
    print_format: bool = field(
        block="options", default=False, longname="keyword to indicate that a print format follows"
    )
    sorbate_filerecord: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="fileout"
    )
    export_array_ascii: bool = field(
        block="options", default=False, longname="export array variables to layered ascii files."
    )
    export_array_netcdf: bool = field(
        block="options", default=False, longname="export array variables to netcdf output files."
    )
    porosity: NDArray[np.float64] = array(
        block="griddata",
        dims=("nodes",),
        default=None,
        netcdf=True,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="porosity of the immobile domain",
    )
    volfrac: NDArray[np.float64] = array(
        block="griddata",
        dims=("nodes",),
        default=None,
        netcdf=True,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="volume fraction of this immobile domain",
    )
    zetaim: NDArray[np.float64] = array(
        block="griddata",
        dims=("nodes",),
        default=None,
        netcdf=True,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="mass transfer rate coefficient between the mobile and immobile domains",
    )
    decay: Optional[NDArray[np.float64]] = array(
        block="griddata",
        dims=("nodes",),
        default=None,
        netcdf=True,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="first rate coefficient",
    )
    decay_sorbed: Optional[NDArray[np.float64]] = array(
        block="griddata",
        dims=("nodes",),
        default=None,
        netcdf=True,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="second rate coefficient",
    )
    bulk_density: Optional[NDArray[np.float64]] = array(
        block="griddata",
        dims=("nodes",),
        default=None,
        netcdf=True,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="bulk density",
    )
    distcoef: Optional[NDArray[np.float64]] = array(
        block="griddata",
        dims=("nodes",),
        default=None,
        netcdf=True,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="distribution coefficient",
    )
    sp2: Optional[NDArray[np.float64]] = array(
        block="griddata",
        dims=("nodes",),
        default=None,
        netcdf=True,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="second sorption parameter",
    )
