# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional, Union

from pydantic import SkipValidation
from pydantic.dataclasses import dataclass

from flopy4.mf6._types import _optional_path
from flopy4.mf6.item import Item
from flopy4.mf6.package import CFG, Package
from flopy4.mf6.spec import field, path


@dataclass(config=CFG, kw_only=True)
class Lkt(Package):
    dfn_name: ClassVar[str] = "gwt-lkt"

    multi_package: ClassVar[bool] = True

    @dataclass(config=CFG)
    class Packagedata(Item):
        ifno: int = field(index=True, pk=True)
        strt: float = field()
        aux: tuple = ()
        boundname: Optional[str] = field(default=None, optional=True)

    @dataclass(config=CFG)
    class Status(Item):
        _keyword: ClassVar[str] = "status"
        ifno: int = field(index=True, fk="packagedata.ifno")
        status: Union[float, str] = field()

    @dataclass(config=CFG)
    class Concentration(Item):
        _keyword: ClassVar[str] = "concentration"
        ifno: int = field(index=True, fk="packagedata.ifno")
        concentration: Union[float, str] = field(time_series=True)

    @dataclass(config=CFG)
    class Rainfall(Item):
        _keyword: ClassVar[str] = "rainfall"
        ifno: int = field(index=True, fk="packagedata.ifno")
        rainfall: Union[float, str] = field(time_series=True)

    @dataclass(config=CFG)
    class Evaporation(Item):
        _keyword: ClassVar[str] = "evaporation"
        ifno: int = field(index=True, fk="packagedata.ifno")
        evaporation: Union[float, str] = field(time_series=True)

    @dataclass(config=CFG)
    class Runoff(Item):
        _keyword: ClassVar[str] = "runoff"
        ifno: int = field(index=True, fk="packagedata.ifno")
        runoff: Union[float, str] = field(time_series=True)

    @dataclass(config=CFG)
    class ExtInflow(Item):
        _keyword: ClassVar[str] = "ext-inflow"
        ifno: int = field(index=True, fk="packagedata.ifno")
        ext_inflow: Union[float, str] = field(time_series=True)

    @dataclass(config=CFG)
    class Auxiliary(Item):
        _keyword: ClassVar[str] = "auxiliary"
        ifno: int = field(index=True, fk="packagedata.ifno")
        auxname: Union[float, str] = field()
        auxval: Union[float, str] = field(time_series=True)

    _StressPeriodDataItem = (
        Status | Concentration | Rainfall | Evaporation | Runoff | ExtInflow | Auxiliary
    )

    flow_package_name: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
        longname="keyword to specify name of corresponding flow package",
    )
    auxiliary: Optional[list[str]] = field(
        default=None,
        block="options",
        optional=True,
        longname="keyword to specify aux variables",
    )
    flow_package_auxiliary_name: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
        longname="keyword to specify name of concentration auxiliary variable in flow package",
    )
    boundnames: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    print_input: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="print input to listing file",
    )
    print_concentration: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="print calculated stages to listing file",
    )
    print_flows: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="print calculated flows to listing file",
    )
    save_flows: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="save lake flows to budget file",
    )
    concentration_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="out",
        keyword="concentration",
    )
    budget_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="out",
        keyword="budget",
    )
    budgetcsv_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="out",
        keyword="budgetcsv",
    )
    ts_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="in",
        keyword="ts6",
    )
    obs_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="in",
        keyword="obs6",
    )
    packagedata: Optional[SkipValidation[list[Packagedata]]] = field(
        default=None,
        block="packagedata",
        write_if_empty=True,
    )
    _stress_period_data: Optional[SkipValidation[dict[int, list[_StressPeriodDataItem]]]] = field(
        alias="stress_period_data",
        default=None,
        repr=False,
        block="period",
        fill_forward=True,
    )


LktPackagedata = Lkt.Packagedata
LktStatus = Lkt.Status
LktConcentration = Lkt.Concentration
LktRainfall = Lkt.Rainfall
LktEvaporation = Lkt.Evaporation
LktRunoff = Lkt.Runoff
LktExtInflow = Lkt.ExtInflow
LktAuxiliary = Lkt.Auxiliary
