# autogenerated file, do not modify
from pathlib import Path
from typing import Optional, TypeAlias, Union

import attrs
from numpy.typing import NDArray

from flopy4.mf6.package import Package
from flopy4.utils import to_path

try:
    import dask.array as da

    ArrayLike: TypeAlias = Union[NDArray, da.Array]
except ImportError:
    ArrayLike: TypeAlias = NDArray  # type: ignore[misc, no-redef]  # dask optional


@attrs.define(kw_only=True, slots=False)
class Mst(Package):
    save_flows: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    first_order_decay: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    zero_order_decay: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    sorption: Optional[str] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "options",
            "dfn_type": "string",
            "optional": True,
        },
    )
    sorbate_file: Optional[Path] = attrs.field(
        default=None,
        converter=lambda v: None if v is None else to_path(v),
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "fileout",
        },
    )
    export_array_ascii: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    export_array_netcdf: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    porosity: ArrayLike = attrs.field(
        default=None,
        metadata={
            "dfn_block": "griddata",
            "dfn_type": "double",
            "shape": ("nodes",),
            "layered": True,
            "chunk_axis": "nlay",
            "netcdf": True,
        },
    )
    decay: Optional[ArrayLike] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "griddata",
            "dfn_type": "double",
            "shape": ("nodes",),
            "layered": True,
            "chunk_axis": "nlay",
            "netcdf": True,
            "optional": True,
        },
    )
    decay_sorbed: Optional[ArrayLike] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "griddata",
            "dfn_type": "double",
            "shape": ("nodes",),
            "layered": True,
            "chunk_axis": "nlay",
            "netcdf": True,
            "optional": True,
        },
    )
    bulk_density: Optional[ArrayLike] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "griddata",
            "dfn_type": "double",
            "shape": ("nodes",),
            "layered": True,
            "chunk_axis": "nlay",
            "netcdf": True,
            "optional": True,
        },
    )
    distcoef: Optional[ArrayLike] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "griddata",
            "dfn_type": "double",
            "shape": ("nodes",),
            "layered": True,
            "chunk_axis": "nlay",
            "netcdf": True,
            "optional": True,
        },
    )
    sp2: Optional[ArrayLike] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "griddata",
            "dfn_type": "double",
            "shape": ("nodes",),
            "layered": True,
            "chunk_axis": "nlay",
            "netcdf": True,
            "optional": True,
        },
    )
