# autogenerated file, do not modify
from pathlib import Path
from typing import Optional

import attrs

from flopy4.mf6._types import _optional_path
from flopy4.mf6.package import Package
from flopy4.mf6.spec import field, path


@attrs.define(kw_only=True, slots=False)
class Mvt(Package):
    print_input: bool = field(
        default=False,
        block="options",
        dfn_type="keyword",
        optional=True,
    )
    print_flows: bool = field(
        default=False,
        block="options",
        dfn_type="keyword",
        optional=True,
    )
    save_flows: bool = field(
        default=False,
        block="options",
        dfn_type="keyword",
        optional=True,
    )
    budget_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        dfn_type="record",
        optional=True,
        inout="fileout",
    )
    budgetcsv_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        dfn_type="record",
        optional=True,
        inout="fileout",
    )
