# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

import attrs

from flopy4.mf6._types import _optional_path
from flopy4.mf6.package import Package
from flopy4.mf6.spec import field, path


@attrs.define(kw_only=True, slots=False)
class Mvt(Package):
    dfn_name: ClassVar[str] = "gwt-mvt"

    print_input: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="print input to listing file",
    )
    print_flows: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="print calculated flows to listing file",
    )
    save_flows: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="save MVT flows to budget file",
    )
    budget_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="out",
    )
    budgetcsv_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="out",
    )
