# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional, Union

from pydantic import Field, SkipValidation
from pydantic.dataclasses import dataclass

from flopy4.mf6._types import _optional_path
from flopy4.mf6.item import Item
from flopy4.mf6.package import CFG, Package
from flopy4.mf6.record import Record
from flopy4.mf6.spec import field, path


@dataclass(config=CFG, kw_only=True)
class Oc(Package):
    dfn_name: ClassVar[str] = "gwt-oc"

    @dataclass(config=CFG)
    class Format(Record):
        _keyword: ClassVar[str] = ""
        format_: str = Field()
        columns: Optional[int] = Field(default=None, json_schema_extra={"tagged": True})
        width: Optional[int] = Field(default=None, json_schema_extra={"tagged": True})
        digits: Optional[int] = Field(default=None, json_schema_extra={"tagged": True})

    @dataclass(config=CFG)
    class Concentrationprint(Record):
        _keyword: ClassVar[str] = "concentration"
        _extra_tokens: ClassVar[tuple[str, ...]] = ("PRINT_FORMAT",)
        formatrecord: "Oc.Format" = Field()

    @dataclass(config=CFG)
    class All(Item):
        _keyword: ClassVar[str] = "all"

    @dataclass(config=CFG)
    class First(Item):
        _keyword: ClassVar[str] = "first"

    @dataclass(config=CFG)
    class Last(Item):
        _keyword: ClassVar[str] = "last"

    @dataclass(config=CFG)
    class Frequency(Item):
        _keyword: ClassVar[str] = "frequency"
        frequency: int = field()

    @dataclass(config=CFG)
    class Steps(Item):
        _keyword: ClassVar[str] = "steps"
        steps: tuple = field(default=(), array=True)

    @dataclass(config=CFG)
    class Save(Item):
        _keyword: ClassVar[str] = "save"
        rtype: Union[float, str] = field()
        ocsetting: "Oc.All | Oc.First | Oc.Last | Oc.Frequency | Oc.Steps" = field()

    @dataclass(config=CFG)
    class Print(Item):
        _keyword: ClassVar[str] = "print"
        rtype: Union[float, str] = field()
        ocsetting: "Oc.All | Oc.First | Oc.Last | Oc.Frequency | Oc.Steps" = field()

    _StressPeriodDataItem = Save | Print

    budget_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="out",
        keyword="budget",
    )
    budgetcsv_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="out",
        keyword="budgetcsv",
    )
    concentration_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="out",
        keyword="concentration",
    )
    concentrationprint: Optional[Concentrationprint] = field(
        default=None,
        block="options",
    )
    _stress_period_data: Optional[SkipValidation[dict[int, list[_StressPeriodDataItem]]]] = field(
        alias="stress_period_data",
        default=None,
        repr=False,
        block="period",
        fill_forward=True,
    )


OcAll = Oc.All
OcFirst = Oc.First
OcLast = Oc.Last
OcFrequency = Oc.Frequency
OcSteps = Oc.Steps
OcSave = Oc.Save
OcPrint = Oc.Print
