# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

import attrs

from flopy4.mf6._types import _optional_path
from flopy4.mf6.package import Package
from flopy4.mf6.record import Record


@attrs.define(kw_only=True, slots=False)
class Oc(Package):
    @attrs.define
    class Concentrationprint(Record):
        _keyword: ClassVar[str] = "concentration"
        _extra_tokens: ClassVar[tuple[str, ...]] = ("PRINT_FORMAT",)

    budget_file: Optional[Path] = attrs.field(
        default=None,
        converter=_optional_path,
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "fileout",
        },
    )
    budgetcsv_file: Optional[Path] = attrs.field(
        default=None,
        converter=_optional_path,
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "fileout",
        },
    )
    concentration_file: Optional[Path] = attrs.field(
        default=None,
        converter=_optional_path,
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "fileout",
        },
    )
    concentrationprint: Optional[Concentrationprint] = attrs.field(
        default=None, metadata={"dfn_block": "options"}
    )
    save_concentration: Optional[dict[int, list[str]]] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "period",
            "dfn_type": "string",
            "oc_action": "save",
            "oc_rtype": "concentration",
        },
    )
    save_budget: Optional[dict[int, list[str]]] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "period",
            "dfn_type": "string",
            "oc_action": "save",
            "oc_rtype": "budget",
        },
    )
    print_concentration: Optional[dict[int, list[str]]] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "period",
            "dfn_type": "string",
            "oc_action": "print",
            "oc_rtype": "concentration",
        },
    )
    print_budget: Optional[dict[int, list[str]]] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "period",
            "dfn_type": "string",
            "oc_action": "print",
            "oc_rtype": "budget",
        },
    )
