# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

from xattree import xattree

from flopy4.mf6.package import Package
from flopy4.mf6.spec import array, field, path
from flopy4.utils import to_path


@xattree(kw_only=True)
class Sft(Package):
    multi_package: ClassVar[bool] = True

    flow_package_name: Optional[str] = field(
        block="options",
        default=None,
        longname="keyword to specify name of corresponding flow package",
    )
    auxiliary: Optional[list[str]] = array(
        block="options", default=None, longname="keyword to specify aux variables"
    )
    flow_package_auxiliary_name: Optional[str] = field(
        block="options",
        default=None,
        longname="keyword to specify name of concentration auxiliary variable in flow package",
    )
    boundnames: bool = field(block="options", default=False)
    print_input: bool = field(
        block="options", default=False, longname="print input to listing file"
    )
    print_concentration: bool = field(
        block="options", default=False, longname="print calculated concentrations to listing file"
    )
    print_flows: bool = field(
        block="options", default=False, longname="print calculated flows to listing file"
    )
    save_flows: bool = field(
        block="options", default=False, longname="save reach flows to budget file"
    )
    concentration_filerecord: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="fileout"
    )
    budget_filerecord: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="fileout"
    )
    budgetcsv_filerecord: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="fileout"
    )
    ts_filerecord: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="filein"
    )
    obs_filerecord: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="filein"
    )
    # TODO: packagedata — could not determine list column dimension
