# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional, Union

import attrs

from flopy4.mf6._types import _optional_path
from flopy4.mf6.item import Item
from flopy4.mf6.package import Package
from flopy4.mf6.spec import field, path


@attrs.define(kw_only=True, slots=False)
class Src(Package):
    dfn_name: ClassVar[str] = "gwt-src"

    multi_package: ClassVar[bool] = True

    @attrs.define
    class StressPeriodData(Item):
        cellid: tuple = field(cellid=True)
        smassrate: Union[float, str] = field(time_series=True)
        aux: tuple = ()
        boundname: Optional[str] = field(default=None, optional=True)

    auxiliary: Optional[list[str]] = field(
        default=None,
        block="options",
        optional=True,
    )
    auxmultname: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
    )
    boundnames: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    print_input: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    print_flows: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    save_flows: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    ts_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="in",
    )
    obs_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="in",
    )
    highest_saturated: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    maxbound: Optional[int] = field(
        default=0,
        block="dimensions",
        auto_from="stress_period_data",
    )
    _stress_period_data: Optional[dict[int, list[StressPeriodData]]] = field(
        alias="stress_period_data",
        default=None,
        repr=False,
        block="period",
        fill_forward=True,
    )

SrcStressPeriodData = Src.StressPeriodData
