class CommonNames:
    iprn = "IPRN"
    internal = "INTERNAL"
    constant = "CONSTANT"
    external = "OPEN/CLOSE"
    format = "FORMAT"
    structured = "structured"
    vertex = "vertex"
    unstructured = "unstructured"
    empty = ""
