# autogenerated file, do not modify
from typing import ClassVar, Optional, Union

import attrs

from flopy4.mf6.model import Model
from flopy4.mf6.model_methods import ModelMethods
from flopy4.mf6.prt.dis import Dis
from flopy4.mf6.prt.disv import Disv
from flopy4.mf6.prt.fmi import Fmi
from flopy4.mf6.prt.mip import Mip
from flopy4.mf6.prt.oc import Oc
from flopy4.mf6.prt.prp import Prp
from flopy4.mf6.spec import child, field

__all__ = [
    "Prt",
    "Dis",
    "Disv",
    "Fmi",
    "Mip",
    "Oc",
    "Prp",
]


@attrs.define(kw_only=True, slots=False)
class Prt(ModelMethods, Model):
    dfn_name: ClassVar[str] = "prt-nam"

    list_: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
        longname="name of listing file",
    )
    print_input: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="print input to listing file",
    )
    print_flows: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="print calculated flows to listing file",
    )
    save_flows: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="save flows for all packages to budget file",
    )
    dis: Optional[Union[Dis, Disv]] = child(block="packages")
    fmi: Optional[Fmi] = child(block="packages")
    mip: Optional[Mip] = child(block="packages")
    oc: Optional[Oc] = child(block="packages")
    prp: list[Prp] = child(block="packages", default=attrs.Factory(list))
