# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

import attrs

from flopy4.dimensions import DerivedDim
from flopy4.mf6._types import FloatArrayLike, IntArrayLike
from flopy4.mf6.disv_methods import DisvMethods
from flopy4.mf6.grid_dims_methods import GridDimsMethods
from flopy4.mf6.item import Item
from flopy4.mf6.package import Package
from flopy4.mf6.spec import child, field, path
from flopy4.mf6.utl.ncf import Ncf


@attrs.define(kw_only=True, slots=False)
class Disv(DisvMethods, GridDimsMethods, Package):
    dfn_name: ClassVar[str] = "prt-disv"

    @attrs.define
    class Vertices(Item):
        iv: int = field(index=True, pk=True)
        xv: float = field()
        yv: float = field()

    @attrs.define
    class Cell2d(Item):
        icell2d: int = field(index=True, pk=True)
        xc: float = field()
        yc: float = field()
        ncvert: Optional[int] = field(default=None, optional=True)
        icvert: tuple[int, ...] = field(
            default=(), array=True, index=True, count="ncvert", optional=True
        )

    length_units: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
        longname="model length units",
    )
    nogrb: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="do not write binary grid file",
    )
    grb_file: Optional[Path] = path(
        default=None,
        converter=attrs.converters.optional(Path),
        block="options",
        optional=True,
        direction="out",
        keyword="grb6",
    )
    xorigin: Optional[float] = field(
        default=None,
        block="options",
        optional=True,
        longname="x-position origin of the model grid coordinate system",
    )
    yorigin: Optional[float] = field(
        default=None,
        block="options",
        optional=True,
        longname="y-position origin of the model grid coordinate system",
    )
    angrot: Optional[float] = field(
        default=None,
        block="options",
        optional=True,
        longname="rotation angle",
    )
    export_array_ascii: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="export array variables to layered ascii files.",
    )
    export_array_netcdf: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="export array variables to netcdf output files.",
    )
    crs: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
        longname="CRS user input string",
    )
    ncf: Optional[Ncf] = child(block="options", keyword="ncf6", direction="in")
    nlay: Optional[int] = field(
        default=None,
        block="dimensions",
        longname="number of layers",
    )
    ncpl: Optional[int] = field(
        default=None,
        block="dimensions",
        longname="number of cells per layer",
    )
    nvert: Optional[int] = field(
        default=None,
        block="dimensions",
        longname="number of vertices",
    )
    top: FloatArrayLike = field(
        default=None,
        block="griddata",
        shape=("ncpl",),
        longname="model top elevation",
    )
    botm: FloatArrayLike = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        layered=True,
        longname="model bottom elevation",
    )
    idomain: Optional[IntArrayLike] = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        layered=True,
        optional=True,
        longname="idomain existence array",
    )
    vertices: Optional[list[Vertices]] = field(
        default=None,
        block="vertices",
        dim="nvert",
    )
    cell2d: Optional[list[Cell2d]] = field(
        default=None,
        block="cell2d",
        dim="ncpl",
    )

    nodes = DerivedDim("nlay * ncpl")
    ncelldim = DerivedDim("2")


DisvVertices = Disv.Vertices
DisvCell2d = Disv.Cell2d
