# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

import attrs

from flopy4.mf6._types import _optional_path
from flopy4.mf6.package import Package
from flopy4.mf6.spec import field, path


@attrs.define(kw_only=True, slots=False)
class Fmi(Package):
    dfn_name: ClassVar[str] = "prt-fmi"

    save_flows: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    gwfhead: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="packagedata",
        optional=True,
        inout="filein",
    )
    gwfbudget: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="packagedata",
        optional=True,
        inout="filein",
    )
    gwfspdis: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="packagedata",
        optional=True,
        inout="filein",
    )
    gwfgrid: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="packagedata",
        optional=True,
        inout="filein",
    )
