# autogenerated file, do not modify
from typing import ClassVar, Optional

from pydantic.dataclasses import dataclass

from flopy4.mf6._types import FloatArrayLike, IntArrayLike
from flopy4.mf6.package import CFG, Package
from flopy4.mf6.spec import field


@dataclass(config=CFG, kw_only=True)
class Mip(Package):
    dfn_name: ClassVar[str] = "prt-mip"

    export_array_ascii: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="export array variables to layered ascii files.",
    )
    porosity: FloatArrayLike = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        longname="porosity",
    )
    retfactor: Optional[FloatArrayLike] = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        optional=True,
        longname="retardation factor",
    )
    izone: Optional[IntArrayLike] = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        optional=True,
        longname="zone number",
    )
