# autogenerated file, do not modify
from typing import Optional

import attrs

from flopy4.mf6._types import FloatArrayLike, IntArrayLike
from flopy4.mf6.package import Package
from flopy4.mf6.spec import field


@attrs.define(kw_only=True, slots=False)
class Mip(Package):
    export_array_ascii: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    porosity: FloatArrayLike = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        layered=True,
    )
    retfactor: Optional[FloatArrayLike] = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        layered=True,
        optional=True,
    )
    izone: Optional[IntArrayLike] = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        layered=True,
        optional=True,
    )
