# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

import attrs
import numpy as np

from flopy4.mf6.package import Package
from flopy4.mf6.record import Record
from flopy4.utils import to_path


@attrs.define(kw_only=True, slots=False)
class Oc(Package):
    @attrs.define
    class TrackTimes(Record):
        _keyword: ClassVar[str] = "track_times"
        times: float = attrs.field()

    @attrs.define
    class TrackTimesfile(Record):
        _keyword: ClassVar[str] = "track_timesfile"
        timesfile: str = attrs.field()

    budget_file: Optional[Path] = attrs.field(
        default=None,
        converter=lambda v: None if v is None else to_path(v),
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "fileout",
        },
    )
    budgetcsv_file: Optional[Path] = attrs.field(
        default=None,
        converter=lambda v: None if v is None else to_path(v),
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "fileout",
        },
    )
    track_file: Optional[Path] = attrs.field(
        default=None,
        converter=lambda v: None if v is None else to_path(v),
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "fileout",
        },
    )
    trackcsv_file: Optional[Path] = attrs.field(
        default=None,
        converter=lambda v: None if v is None else to_path(v),
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "fileout",
        },
    )
    track_release: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    track_exit: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    track_subfeature_exit: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    track_timestep: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    track_terminate: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    track_weaksink: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    track_usertime: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    track_dropped: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    track_times: Optional[TrackTimes] = attrs.field(default=None, metadata={"dfn_block": "options"})
    track_timesfile: Optional[TrackTimesfile] = attrs.field(
        default=None, metadata={"dfn_block": "options"}
    )
    dev_dump_event_trace: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    ntracktimes: Optional[int] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "dimensions",
            "dfn_type": "integer",
            "optional": True,
        },
    )
    tracktimes: Optional[np.recarray] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "tracktimes",
            "schema": "__tracktimes_schema__",
            "auto_from": "tracktimes",
        },
    )
    save_budget: Optional[dict[int, list[str]]] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "period",
            "dfn_type": "string",
            "oc_action": "save",
            "oc_rtype": "budget",
        },
    )
    print_budget: Optional[dict[int, list[str]]] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "period",
            "dfn_type": "string",
            "oc_action": "print",
            "oc_rtype": "budget",
        },
    )
    __tracktimes_schema__: ClassVar[list[dict]] = [
        {
            "name": "time",
            "dfn_type": "double",
            "role": "value",
        },
    ]

    tracktimes_dtype: np.dtype = attrs.field(init=False, factory=lambda: np.dtype([]))
    period_dtype: np.dtype = attrs.field(init=False, factory=lambda: np.dtype([]))

    _DTYPE_MAP: ClassVar[dict] = {
        "integer": np.int64,
        "double": np.float64,
        "double precision": np.float64,
        "string": np.object_,
        "keyword": np.object_,
        "object": np.object_,
    }

    def __attrs_post_init__(self) -> None:
        _aux_tmp = getattr(self, "auxiliary", None)
        naux = len(_aux_tmp) if _aux_tmp is not None else 0
        ncelldim = self._compute_ncelldim()
        _tracktimes_f: list[tuple] = []
        for _col in self.__tracktimes_schema__:
            _role = _col.get("role", "value")
            _dt = _col.get("dtype")
            _dt = (
                eval(_dt)
                if _dt
                else self._DTYPE_MAP.get(_col.get("dfn_type", "string"), np.object_)
            )
            if _role == "cellid":
                _tracktimes_f.append((_col["name"], np.int64, (ncelldim,)))
            elif _role == "feature_id":
                _tracktimes_f.append((_col["name"], np.int64))
            elif _role == "boundname":
                if getattr(self, "boundnames", False):
                    _tracktimes_f.append((_col["name"], np.object_))
            else:
                _tracktimes_f.append((_col["name"], _dt))
        if "tracktimes" == "packagedata":
            for _i in range(naux):
                _tracktimes_f.append((f"aux{_i}", np.object_))
        self.tracktimes_dtype = np.dtype(_tracktimes_f)
        _raw_tracktimes = getattr(self, "tracktimes", None)
        if _raw_tracktimes is not None:
            self.tracktimes = self._coerce_to_recarray(_raw_tracktimes, self.tracktimes_dtype)
        if getattr(self, "tracktimes", None) is not None and getattr(self, "ntracktimess", 0) == 0:
            object.__setattr__(self, "ntracktimess", len(getattr(self, "tracktimes")))
        super().__attrs_post_init__()

    @property  # type: ignore[override]
    def stress_period_data(self) -> "Optional[dict[int, np.recarray]]":
        return self._stress_period_data

    @stress_period_data.setter
    def stress_period_data(self, value) -> None:
        self._stress_period_data = value

    def to_dataframe(self) -> "pandas.DataFrame":  # type: ignore[name-defined]
        """Return stress period data as a tidy pd.DataFrame. Zero cost if not called."""
        import pandas as pd

        _spd = self._stress_period_data
        if not _spd:
            return pd.DataFrame()
        frames = []
        for kper in sorted(_spd):
            arr = _spd[kper]
            rows = {}
            for nm in arr.dtype.names or ():
                col = arr[nm]
                rows[nm] = [tuple(v) for v in col] if col.ndim > 1 else col.tolist()
            df = pd.DataFrame(rows)
            df.insert(0, "kper", kper)
            frames.append(df)
        return pd.concat(frames, ignore_index=True)
