# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

import attrs
import numpy as np

from flopy4.mf6._types import _optional_path
from flopy4.mf6.package import Package
from flopy4.mf6.record import Record
from flopy4.mf6.schema import Column, Schema
from flopy4.mf6.spec import field, path


@attrs.define(kw_only=True, slots=False)
class Oc(Package):
    @attrs.define
    class TrackTimesfile(Record):
        _keyword: ClassVar[str] = "track_timesfile"
        timesfile: str = attrs.field()

    budget_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        inout="fileout",
    )
    budgetcsv_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        inout="fileout",
    )
    track_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        inout="fileout",
    )
    trackcsv_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        inout="fileout",
    )
    track_release: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    track_exit: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    track_subfeature_exit: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    track_timestep: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    track_terminate: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    track_weaksink: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    track_usertime: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    track_dropped: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    # TODO: track_timesrecord — type 'record' not yet supported
    track_timesfile: Optional[TrackTimesfile] = field(
        default=None,
        block="options",
    )
    scratch_buffer: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    ntracktimes: Optional[int] = field(
        default=None,
        block="dimensions",
        optional=True,
    )
    save_budget: Optional[dict[int, list[str]]] = field(
        default=None,
        block="period",
        oc_action="save",
        oc_rtype="budget",
    )
    print_budget: Optional[dict[int, list[str]]] = field(
        default=None,
        block="period",
        oc_action="print",
        oc_rtype="budget",
    )
    tracktimes: Optional[np.recarray] = field(
        default=None,
        block="tracktimes",
        schema="__tracktimes_schema__",
        auto_from="tracktimes",
    )

    class _TracktimesSchema(Schema):
        time = Column("time", role="value", dfn_type="double")

    __tracktimes_schema__: ClassVar[type[Schema]] = _TracktimesSchema

    @attrs.define
    class TracktimesRow:
        time: float

        def __iter__(self):
            yield self.time

    tracktimes_dtype: np.dtype = attrs.field(init=False, factory=lambda: np.dtype([]))
    period_dtype: np.dtype = attrs.field(init=False, factory=lambda: np.dtype([]))


OcTracktimesRow = Oc.TracktimesRow
