# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

import attrs
import numpy as np

from flopy4.mf6.package import Package
from flopy4.mf6.record import Record
from flopy4.utils import to_path


@attrs.define(kw_only=True, slots=False)
class Prp(Package):
    multi_package: ClassVar[bool] = True

    @attrs.define
    class ReleaseTimes(Record):
        _keyword: ClassVar[str] = "release_times"
        times: float = attrs.field()

    @attrs.define
    class ReleaseTimesfile(Record):
        _keyword: ClassVar[str] = "release_timesfile"
        timesfile: str = attrs.field()

    boundnames: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    print_input: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    dev_exit_solve_method: Optional[int] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "options",
            "dfn_type": "integer",
            "optional": True,
        },
    )
    exit_solve_tolerance: Optional[float] = attrs.field(
        default="1e-5",
        metadata={
            "dfn_block": "options",
            "dfn_type": "double",
            "optional": True,
        },
    )  # type: ignore[assignment]
    local_z: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    extend_tracking: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    track_file: Optional[Path] = attrs.field(
        default=None,
        converter=lambda v: None if v is None else to_path(v),
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "fileout",
        },
    )
    trackcsv_file: Optional[Path] = attrs.field(
        default=None,
        converter=lambda v: None if v is None else to_path(v),
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "fileout",
        },
    )
    stoptime: Optional[float] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "options",
            "dfn_type": "double",
            "optional": True,
        },
    )
    stoptraveltime: Optional[float] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "options",
            "dfn_type": "double",
            "optional": True,
        },
    )
    stop_at_weak_sink: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    istopzone: Optional[int] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "options",
            "dfn_type": "integer",
            "optional": True,
        },
    )
    drape: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    release_times: Optional[ReleaseTimes] = attrs.field(
        default=None, metadata={"dfn_block": "options"}
    )
    release_timesfile: Optional[ReleaseTimesfile] = attrs.field(
        default=None, metadata={"dfn_block": "options"}
    )
    dry_tracking_method: Optional[str] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "options",
            "dfn_type": "string",
            "optional": True,
        },
    )
    dev_forceternary: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
        },
    )
    release_time_tolerance: Optional[float] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "options",
            "dfn_type": "double",
            "optional": True,
        },
    )
    release_time_frequency: Optional[float] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "options",
            "dfn_type": "double",
            "optional": True,
        },
    )
    coordinate_check_method: Optional[str] = attrs.field(
        default="eager",
        metadata={
            "dfn_block": "options",
            "dfn_type": "string",
            "optional": True,
        },
    )
    dev_cycle_detection_window: Optional[int] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "options",
            "dfn_type": "integer",
            "optional": True,
        },
    )
    nreleasepts: Optional[int] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "dimensions",
            "dfn_type": "integer",
        },
    )
    nreleasetimes: Optional[int] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "dimensions",
            "dfn_type": "integer",
        },
    )
    packagedata: Optional[np.recarray] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "packagedata",
            "schema": "__packagedata_schema__",
            "auto_from": "packagedata",
        },
    )
    releasetimes: Optional[np.recarray] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "releasetimes",
            "schema": "__releasetimes_schema__",
            "auto_from": "releasetimes",
        },
    )
    _stress_period_data: Optional[dict[int, np.recarray]] = attrs.field(
        alias="stress_period_data",
        default=None,
        repr=False,
        metadata={
            "dfn_block": "period",
            "schema": "__period_schema__",
            "fill_forward": True,
        },
    )
    __packagedata_schema__: ClassVar[list[dict]] = [
        {
            "name": "irptno",
            "dfn_type": "integer",
            "role": "feature_id",
        },
        {
            "name": "cellid",
            "dfn_type": "integer",
            "role": "cellid",
        },
        {
            "name": "xrpt",
            "dfn_type": "double",
            "role": "value",
        },
        {
            "name": "yrpt",
            "dfn_type": "double",
            "role": "value",
        },
        {
            "name": "zrpt",
            "dfn_type": "double",
            "role": "value",
        },
        {
            "name": "boundname",
            "dfn_type": "string",
            "role": "boundname",
        },
    ]

    __releasetimes_schema__: ClassVar[list[dict]] = [
        {
            "name": "time",
            "dfn_type": "double",
            "role": "value",
        },
    ]

    __period_schema__: ClassVar[list[dict]] = [
        {
            "name": "cellid",
            "dfn_type": "integer",
            "role": "cellid",
            "shape": "ncelldim",
            "optional": False,
        },
        {
            "name": "all",
            "dfn_type": "keyword",
            "optional": False,
            "role": "value",
        },
        {
            "name": "first",
            "dfn_type": "keyword",
            "optional": False,
            "role": "value",
        },
        {
            "name": "last",
            "dfn_type": "keyword",
            "optional": False,
            "role": "value",
        },
        {
            "name": "frequency",
            "dfn_type": "integer",
            "optional": False,
            "role": "value",
        },
        {
            "name": "steps",
            "dfn_type": "integer",
            "optional": False,
            "role": "value",
        },
        {
            "name": "fraction",
            "dfn_type": "double",
            "optional": True,
            "role": "value",
        },
    ]

    packagedata_dtype: np.dtype = attrs.field(init=False, factory=lambda: np.dtype([]))
    releasetimes_dtype: np.dtype = attrs.field(init=False, factory=lambda: np.dtype([]))
    period_dtype: np.dtype = attrs.field(init=False, factory=lambda: np.dtype([]))

    _DTYPE_MAP: ClassVar[dict] = {
        "integer": np.int64,
        "double": np.float64,
        "double precision": np.float64,
        "string": np.object_,
        "keyword": np.object_,
        "object": np.object_,
    }

    def __attrs_post_init__(self) -> None:
        _aux_tmp = getattr(self, "auxiliary", None)
        naux = len(_aux_tmp) if _aux_tmp is not None else 0
        ncelldim = self._compute_ncelldim()
        _packagedata_f: list[tuple] = []
        for _col in self.__packagedata_schema__:
            _role = _col.get("role", "value")
            _dt = _col.get("dtype")
            _dt = (
                eval(_dt)
                if _dt
                else self._DTYPE_MAP.get(_col.get("dfn_type", "string"), np.object_)
            )
            if _role == "cellid":
                _packagedata_f.append((_col["name"], np.int64, (ncelldim,)))
            elif _role == "feature_id":
                _packagedata_f.append((_col["name"], np.int64))
            elif _role == "boundname":
                if getattr(self, "boundnames", False):
                    _packagedata_f.append((_col["name"], np.object_))
            else:
                _packagedata_f.append((_col["name"], _dt))
        if "packagedata" == "packagedata":
            for _i in range(naux):
                _packagedata_f.append((f"aux{_i}", np.object_))
        self.packagedata_dtype = np.dtype(_packagedata_f)
        _raw_packagedata = getattr(self, "packagedata", None)
        if _raw_packagedata is not None:
            self.packagedata = self._coerce_to_recarray(_raw_packagedata, self.packagedata_dtype)
        if (
            getattr(self, "packagedata", None) is not None
            and getattr(self, "npackagedatas", 0) == 0
        ):
            object.__setattr__(self, "npackagedatas", len(getattr(self, "packagedata")))
        _releasetimes_f: list[tuple] = []
        for _col in self.__releasetimes_schema__:
            _role = _col.get("role", "value")
            _dt = _col.get("dtype")
            _dt = (
                eval(_dt)
                if _dt
                else self._DTYPE_MAP.get(_col.get("dfn_type", "string"), np.object_)
            )
            if _role == "cellid":
                _releasetimes_f.append((_col["name"], np.int64, (ncelldim,)))
            elif _role == "feature_id":
                _releasetimes_f.append((_col["name"], np.int64))
            elif _role == "boundname":
                if getattr(self, "boundnames", False):
                    _releasetimes_f.append((_col["name"], np.object_))
            else:
                _releasetimes_f.append((_col["name"], _dt))
        if "releasetimes" == "packagedata":
            for _i in range(naux):
                _releasetimes_f.append((f"aux{_i}", np.object_))
        self.releasetimes_dtype = np.dtype(_releasetimes_f)
        _raw_releasetimes = getattr(self, "releasetimes", None)
        if _raw_releasetimes is not None:
            self.releasetimes = self._coerce_to_recarray(_raw_releasetimes, self.releasetimes_dtype)
        if (
            getattr(self, "releasetimes", None) is not None
            and getattr(self, "nreleasetimess", 0) == 0
        ):
            object.__setattr__(self, "nreleasetimess", len(getattr(self, "releasetimes")))
        _has_keystring = any(
            col.get("role") in ("keystring", "keystring_value") for col in self.__period_schema__
        )
        fields: list[tuple] = []
        for col in self.__period_schema__:
            role = col.get("role", "value")
            if role == "cellid":
                fields.append((col["name"], np.int64, (ncelldim,)))
            elif role in ("keystring", "keystring_value"):
                fields.append((col["name"], np.object_))
            elif col.get("time_series"):
                fields.append((col["name"], np.object_))
            elif not col.get("optional", False):
                _dt = col.get("dtype")
                _col_dt = (
                    eval(_dt)
                    if _dt
                    else self._DTYPE_MAP.get(col.get("dfn_type", "double"), np.float64)
                )
                fields.append((col["name"], _col_dt))
        if not _has_keystring:
            for i in range(naux):
                fields.append((f"aux{i}", np.object_))
            if getattr(self, "boundnames", False):
                fields.append(("boundname", np.object_))
        self.period_dtype = np.dtype(fields)
        if self._stress_period_data is not None:
            self._stress_period_data = {
                kper: self._coerce_to_recarray(rows, self.period_dtype)
                for kper, rows in self._stress_period_data.items()
            }
        _spd = self._stress_period_data
        if _spd and getattr(self, "maxbound", None) == 0:
            self.maxbound = max(len(v) for v in _spd.values())
        super().__attrs_post_init__()

    @property  # type: ignore[override]
    def stress_period_data(self) -> "Optional[dict[int, np.recarray]]":
        return self._stress_period_data

    @stress_period_data.setter
    def stress_period_data(self, value) -> None:
        self._stress_period_data = value

    def to_dataframe(self) -> "pandas.DataFrame":  # type: ignore[name-defined]
        """Return stress period data as a tidy pd.DataFrame. Zero cost if not called."""
        import pandas as pd

        _spd = self._stress_period_data
        if not _spd:
            return pd.DataFrame()
        frames = []
        for kper in sorted(_spd):
            arr = _spd[kper]
            rows = {}
            for nm in arr.dtype.names or ():
                col = arr[nm]
                rows[nm] = [tuple(v) for v in col] if col.ndim > 1 else col.tolist()
            df = pd.DataFrame(rows)
            df.insert(0, "kper", kper)
            frames.append(df)
        return pd.concat(frames, ignore_index=True)
