# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

import attrs
import numpy as np

from flopy4.mf6._types import _optional_path
from flopy4.mf6.package import Package
from flopy4.mf6.record import Record
from flopy4.mf6.schema import Column, Schema


@attrs.define(kw_only=True, slots=False)
class Prp(Package):
    multi_package: ClassVar[bool] = True

    @attrs.define
    class ReleaseTimes(Record):
        _keyword: ClassVar[str] = "release_times"
        times: float = attrs.field()

    @attrs.define
    class ReleaseTimesfile(Record):
        _keyword: ClassVar[str] = "release_timesfile"
        timesfile: str = attrs.field()

    boundnames: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    print_input: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    dev_exit_solve_method: Optional[int] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "options",
            "dfn_type": "integer",
            "optional": True,
        },
    )
    exit_solve_tolerance: Optional[float] = attrs.field(
        default="1e-5",
        metadata={
            "dfn_block": "options",
            "dfn_type": "double",
            "optional": True,
        },
    )  # type: ignore[assignment]
    local_z: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    extend_tracking: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    track_file: Optional[Path] = attrs.field(
        default=None,
        converter=_optional_path,
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "fileout",
        },
    )
    trackcsv_file: Optional[Path] = attrs.field(
        default=None,
        converter=_optional_path,
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "fileout",
        },
    )
    stoptime: Optional[float] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "options",
            "dfn_type": "double",
            "optional": True,
        },
    )
    stoptraveltime: Optional[float] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "options",
            "dfn_type": "double",
            "optional": True,
        },
    )
    stop_at_weak_sink: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    istopzone: Optional[int] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "options",
            "dfn_type": "integer",
            "optional": True,
        },
    )
    drape: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    release_times: Optional[ReleaseTimes] = attrs.field(
        default=None, metadata={"dfn_block": "options"}
    )
    release_timesfile: Optional[ReleaseTimesfile] = attrs.field(
        default=None, metadata={"dfn_block": "options"}
    )
    dry_tracking_method: Optional[str] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "options",
            "dfn_type": "string",
            "optional": True,
        },
    )
    dev_forceternary: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
        },
    )
    release_time_tolerance: Optional[float] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "options",
            "dfn_type": "double",
            "optional": True,
        },
    )
    release_time_frequency: Optional[float] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "options",
            "dfn_type": "double",
            "optional": True,
        },
    )
    coordinate_check_method: Optional[str] = attrs.field(
        default="eager",
        metadata={
            "dfn_block": "options",
            "dfn_type": "string",
            "optional": True,
        },
    )
    dev_cycle_detection_window: Optional[int] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "options",
            "dfn_type": "integer",
            "optional": True,
        },
    )
    nreleasepts: Optional[int] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "dimensions",
            "dfn_type": "integer",
        },
    )
    nreleasetimes: Optional[int] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "dimensions",
            "dfn_type": "integer",
        },
    )
    packagedata: Optional[np.recarray] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "packagedata",
            "schema": "__packagedata_schema__",
            "auto_from": "packagedata",
        },
    )
    releasetimes: Optional[np.recarray] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "releasetimes",
            "schema": "__releasetimes_schema__",
            "auto_from": "releasetimes",
        },
    )
    _stress_period_data: Optional[dict[int, np.recarray]] = attrs.field(
        alias="stress_period_data",
        default=None,
        repr=False,
        metadata={
            "dfn_block": "period",
            "schema": "__period_schema__",
            "fill_forward": True,
        },
    )

    class _PackagedataSchema(Schema):
        irptno = Column("irptno", role="feature_id", dfn_type="integer")
        cellid = Column("cellid", role="cellid", dfn_type="integer")
        xrpt = Column("xrpt", role="value", dfn_type="double")
        yrpt = Column("yrpt", role="value", dfn_type="double")
        zrpt = Column("zrpt", role="value", dfn_type="double")
        boundname = Column("boundname", role="boundname", dfn_type="string")

    __packagedata_schema__: ClassVar[type[Schema]] = _PackagedataSchema

    class _ReleasetimesSchema(Schema):
        time = Column("time", role="value", dfn_type="double")

    __releasetimes_schema__: ClassVar[type[Schema]] = _ReleasetimesSchema

    class _PeriodSchema(Schema):
        cellid = Column("cellid", role="cellid", dfn_type="integer", shape="ncelldim")
        all = Column("all", role="value", dfn_type="keyword")
        first = Column("first", role="value", dfn_type="keyword")
        last = Column("last", role="value", dfn_type="keyword")
        frequency = Column("frequency", role="value", dfn_type="integer")
        steps = Column("steps", role="value", dfn_type="integer")
        fraction = Column("fraction", role="value", dfn_type="double", optional=True)

    __period_schema__: ClassVar[type[Schema]] = _PeriodSchema

    packagedata_dtype: np.dtype = attrs.field(init=False, factory=lambda: np.dtype([]))
    releasetimes_dtype: np.dtype = attrs.field(init=False, factory=lambda: np.dtype([]))
    period_dtype: np.dtype = attrs.field(init=False, factory=lambda: np.dtype([]))
