# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

import attrs

from flopy4.mf6._types import _optional_path
from flopy4.mf6.package import Package
from flopy4.mf6.record import Record
from flopy4.mf6.row import Row
from flopy4.mf6.spec import field, path

_Row = Row


@attrs.define(kw_only=True, slots=False)
class Prp(Package):
    dfn_name: ClassVar[str] = "prt-prp"

    multi_package: ClassVar[bool] = True

    @attrs.define
    class ReleaseTimesfile(Record):
        _keyword: ClassVar[str] = "release_timesfile"
        timesfile: str = attrs.field()

    @attrs.define
    class PackagedataRow(Row):
        irptno: int = field(pk=True)
        cellid: tuple = field(cellid=True)
        xrpt: float = field()
        yrpt: float = field()
        zrpt: float = field()
        aux: tuple = ()
        boundname: Optional[str] = field(default=None, optional=True)

    @attrs.define
    class ReleasetimesRow(Row):
        time: float

    @attrs.define
    class Row(_Row):
        keyword: str
        value: Optional[object] = field(default=None, optional=True)

    boundnames: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    print_input: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    exit_solve_tolerance: Optional[float] = field(
        default=1e-05,
        block="options",
        optional=True,
    )
    local_z: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    extend_tracking: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    track_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        inout="fileout",
    )
    trackcsv_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        inout="fileout",
    )
    stoptime: Optional[float] = field(
        default=None,
        block="options",
        optional=True,
    )
    stoptraveltime: Optional[float] = field(
        default=None,
        block="options",
        optional=True,
    )
    stop_at_weak_sink: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    istopzone: Optional[int] = field(
        default=None,
        block="options",
        optional=True,
    )
    drape: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    # TODO: release_timesrecord — type 'record' not yet supported
    release_timesfile: Optional[ReleaseTimesfile] = field(
        default=None,
        block="options",
    )
    dry_tracking_method: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
    )
    release_time_tolerance: Optional[float] = field(
        default=None,
        block="options",
        optional=True,
    )
    release_time_frequency: Optional[float] = field(
        default=None,
        block="options",
        optional=True,
    )
    coordinate_check_method: Optional[str] = field(
        default="eager",
        block="options",
        optional=True,
    )
    nreleasepts: Optional[int] = field(
        default=None,
        block="dimensions",
    )
    nreleasetimes: Optional[int] = field(
        default=None,
        block="dimensions",
    )
    packagedata: Optional[list[PackagedataRow]] = field(
        default=None,
        block="packagedata",
        auto_from="packagedata",
    )
    releasetimes: Optional[list[ReleasetimesRow]] = field(
        default=None,
        block="releasetimes",
        auto_from="releasetimes",
    )
    _stress_period_data: Optional[dict[int, list[Row]]] = field(
        alias="stress_period_data",
        default=None,
        repr=False,
        block="period",
        fill_forward=True,
    )


PrpRow = Prp.Row
PrpPackagedataRow = Prp.PackagedataRow
PrpReleasetimesRow = Prp.ReleasetimesRow
