"""
Orchestrate MF6 Python class generation from DFN specification files.

Usage (CLI)::

    generate-mf6-classes MODFLOW-ORG/modflow6@6.6.0
    generate-mf6-classes /path/to/local/dfns --mf6-version 6.8.0.dev0+abc1234
"""

import argparse
import logging
import sys
import warnings
from pathlib import Path

with warnings.catch_warnings():
    warnings.filterwarnings("ignore", message=".*modflow_devtools.dfns.*experimental.*")
    from modflow_devtools.dfns.registry import LocalDfnRegistry, RemoteDfnRegistry

from .make import make_all

logger = logging.getLogger(__name__)

_PROJ_ROOT = Path(__file__).parents[4].expanduser().resolve()
_MF6_ROOT = _PROJ_ROOT / "flopy4" / "mf6"
_DFN_SCHEMA_VERSION = "2.0.0.dev1"

# DFN names that require special handling beyond simple package generation.
# These are skipped until their generation tier is implemented.
#
# nam files: model/simulation name files need special model-level handling.
# dis/disv: require DisBase + grid conversion methods (dis tier).
# tdis/ims: top-level hand-written files, not yet templated.
# *g / *a variants: gridded/array package variants, deferred.
#
# TODO (subpackage tier): detect `# flopy subpackage` DFN annotations and emit
# a typed child attrs field (e.g. ncf: Optional[Ncf]) alongside the existing path
# field; DisBase.write() already establishes the write pattern for NCF.
# utl-ts also needs period values referencing timeseries by name written as strings.
_SKIP = {
    # discretization tier (require DisBase + grid methods)
    "gwf-dis",
    "gwf-disv",
    "gwt-dis",
    "gwe-dis",
    "prt-dis",
    # time discretization (hand-written tdis.py)
    "sim-tdis",
    # hand-written: wkt field type override + Ncf.from_grid() factory.
    # TODO: move factory to NcfBase (utl/ncf_base.py) so codegen can own utl/ncf.py,
    # matching the DisBase pattern used for discretization packages.
    "utl-ncf",
}


def _parse_release_id(
    release_id: str,
) -> tuple[LocalDfnRegistry | RemoteDfnRegistry, str | None]:
    """Parse a release_id into a registry and resolved MF6 version.

    Parameters
    ----------
    release_id :
        Either a local directory path or a remote release ID in
        ``owner/repo@tag`` format (e.g. ``MODFLOW-ORG/modflow6@6.7.0``
        or ``MODFLOW-ORG/modflow6@latest``).

    Returns
    -------
    tuple
        (registry, mf6_version) where mf6_version is the resolved concrete
        tag for remote registries (``@latest`` is resolved via the GitHub
        API) or None for local paths.
    """
    path = Path(release_id).expanduser()
    if path.exists() and path.is_dir():
        return LocalDfnRegistry(path=path), None
    if "@" not in release_id or "/" not in release_id.split("@")[0]:
        raise ValueError(
            f"release_id must be 'owner/repo@tag' or a local path; got: {release_id!r}"
        )
    registry = RemoteDfnRegistry(release_id=release_id)
    return registry, registry.latest_tag()


def _populate_remote_cache(
    registry: RemoteDfnRegistry, release_id: str, force: bool = False
) -> None:
    """Populate the registry's DFN cache.

    Tries ``registry.sync()`` first (requires a ``dfns.zip`` release asset).
    Falls back to fetching DFNs from the repository tree when that asset is
    not yet available — writes directly into the registry's cache path so
    ``registry.spec()`` finds the files in the expected location.

    Parameters
    ----------
    force :
        Re-fetch even if the cache already exists. Should be True for
        branch refs (mutable) and False for pinned release tags.
    """
    if not force and registry.cache_path.exists() and any(registry.cache_path.iterdir()):
        return
    try:
        registry.sync()
    except Exception:
        # dfns.zip not yet a release asset; fetch from the git tree instead.
        from modflow_devtools.dfn import get_dfns

        owner_repo, tag = release_id.split("@", 1)
        owner, repo = owner_repo.split("/")
        registry.cache_path.mkdir(parents=True, exist_ok=True)
        get_dfns(owner=owner, repo=repo, ref=tag, outdir=registry.cache_path)


def _write_contract(outdir: Path, mf6_version: str) -> None:
    (outdir / "_contract.py").write_text(
        "# autogenerated file, do not modify\n"
        f'MF6_VERSION = "{mf6_version}"\n'
        f'DFN_SCHEMA_VERSION = "{_DFN_SCHEMA_VERSION}"\n'
    )


def generate_classes(
    release_id: str,
    outdir: str | Path = _MF6_ROOT,
    mf6_version: str | None = None,
    developmode: bool = False,
    fmt: bool = True,
    makedirs: bool = False,
    existing_only: bool = False,
    force: bool = False,
) -> None:
    """Generate Python classes for MODFLOW 6 packages.

    Fetches (or reads) DFN files via the registry, generates a Python source
    file for each component into ``outdir``, and writes ``_contract.py``
    recording the MF6 version and DFN schema version.

    Parameters
    ----------
    release_id :
        Remote release ID (``owner/repo@tag``) or local path to a directory
        of ``.dfn`` files.
    outdir :
        Root output directory. Defaults to ``flopy4/mf6/`` inside the
        project so generated files land alongside hand-written ones.
    mf6_version :
        Override the MF6 version written to ``_contract.py``. For remote
        release IDs the tag is used automatically; for local paths this
        defaults to ``"unknown"`` unless provided here.
    developmode :
        Include fields marked ``developmode`` in the DFN. Default False.
    fmt :
        Run ``ruff format`` / ``ruff check --fix`` on each generated file.
    makedirs :
        Create output subdirectories if missing.
    existing_only :
        Only (re)generate files that already exist on disk.
    force :
        Force re-fetch of DFNs even if already cached. Automatically
        enabled for branch refs (non-semver tags), which are mutable.
    """
    registry, derived_version = _parse_release_id(release_id)
    effective_version = mf6_version or derived_version or "unknown"

    if effective_version == "unknown":
        logger.warning(
            "MF6 version is unknown for local DFN path '%s'. "
            "Pass --mf6-version to record it explicitly in _contract.py.",
            release_id,
        )

    if isinstance(registry, RemoteDfnRegistry):
        # Branch refs are mutable: always re-fetch unless the caller explicitly
        # passes a pinned semver tag (first char is a digit).
        is_branch = not effective_version[0].isdigit() if effective_version else True
        _populate_remote_cache(registry, release_id, force=force or is_branch)

    logger.info(f"Loading DFNs from {release_id!r} (schema {_DFN_SCHEMA_VERSION})")
    dfns = registry.spec(schema_version=_DFN_SCHEMA_VERSION)

    outdir = Path(outdir).expanduser().resolve()
    generated = make_all(
        dfns=dfns,
        outdir=outdir,
        developmode=developmode,
        fmt=fmt,
        skip=_SKIP,
        makedirs=makedirs,
        existing_only=existing_only,
    )

    _write_contract(outdir, effective_version)
    logger.info(f"Generated {len(generated)} files. Contract: MF6 {effective_version}.")
    return effective_version


def cli_main() -> None:
    """Command-line entry point."""
    parser = argparse.ArgumentParser(
        description="Generate MF6 Python classes from DFN specification files.",
    )
    parser.add_argument(
        "release_id",
        help="Remote release ID (owner/repo@tag) or local path to .dfn files.",
    )
    parser.add_argument(
        "--mf6-version",
        default=None,
        dest="mf6_version",
        help="MF6 version string to record in _contract.py. "
        "Inferred from the release tag for remote IDs; defaults to 'unknown' for local paths.",
    )
    parser.add_argument(
        "--outdir",
        default=str(_MF6_ROOT),
        help="Root output directory (default: flopy4/mf6/ in the project).",
    )
    parser.add_argument(
        "--developmode",
        action="store_true",
        help="Include developmode fields.",
    )
    parser.add_argument(
        "--no-format",
        action="store_true",
        help="Skip ruff formatting.",
    )
    parser.add_argument(
        "--makedirs",
        action="store_true",
        help="Create missing output subdirectories (useful for preview paths).",
    )
    parser.add_argument(
        "--existing-only",
        action="store_true",
        help="Only regenerate files that already exist on disk.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Force re-fetch of DFNs even if already cached. "
        "Implied for branch refs (e.g. @develop).",
    )
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    if args.verbose:
        logging.basicConfig(level=logging.INFO)

    try:
        generate_classes(
            release_id=args.release_id,
            outdir=args.outdir,
            mf6_version=args.mf6_version,
            developmode=args.developmode,
            fmt=not args.no_format,
            makedirs=args.makedirs,
            existing_only=args.existing_only,
            force=args.force,
        )
    except (EOFError, KeyboardInterrupt):
        sys.exit(f"Cancelled '{sys.argv[0]}'")


if __name__ == "__main__":
    cli_main()
