name = "gwt-mst"
multi = false

[options.save_flows]
name = "save_flows"
type = "keyword"
block = "options"
description = "keyword to indicate that mst flow terms will be written to the file specified with 'budget fileout' in output control."

[options.first_order_decay]
name = "first_order_decay"
type = "keyword"
block = "options"
description = "is a text keyword to indicate that first-order decay will occur.  use of this keyword requires that decay and decay_sorbed (if sorption is active) are specified in the griddata block."

[options.zero_order_decay]
name = "zero_order_decay"
type = "keyword"
block = "options"
description = "is a text keyword to indicate that zero-order decay will occur.  use of this keyword requires that decay and decay_sorbed (if sorption is active) are specified in the griddata block."

[options.sorption]
name = "sorption"
type = "string"
block = "options"
description = "is a text keyword to indicate that sorption will be activated.  valid sorption options include linear, freundlich, and langmuir.  use of this keyword requires that bulk_density and distcoef are specified in the griddata block.  if sorption is specified as freundlich or langmuir then sp2 is also required in the griddata block."

[options.sorbate_filerecord]
name = "sorbate_filerecord"
type = "record"
block = "options"
description = ""

[options.sorbate_filerecord.sorbate]
block = "options"
name = "sorbate"
type = "keyword"
shape = ""
in_record = "true"
reader = "urword"
tagged = "true"
optional = "false"
longname = "sorbate keyword"
description = "keyword to specify that record corresponds to sorbate concentration."

[options.sorbate_filerecord.fileout]
block = "options"
name = "fileout"
type = "keyword"
shape = ""
in_record = "true"
reader = "urword"
tagged = "true"
optional = "false"
longname = "file keyword"
description = "keyword to specify that an output filename is expected next."

[options.sorbate_filerecord.sorbatefile]
block = "options"
name = "sorbatefile"
type = "string"
preserve_case = "true"
shape = ""
in_record = "true"
reader = "urword"
tagged = "false"
optional = "false"
longname = "file keyword"
description = "name of the output file to write sorbate concentration information.  Sorbate concentrations will be written whenever aqueous concentrations are saved, as determined by settings in the Output Control option."

[griddata.porosity]
name = "porosity"
type = "double precision"
shape = "(nodes)"
block = "griddata"
description = "is the mobile domain porosity, defined as the mobile domain pore volume per mobile domain volume.  additional information on porosity within the context of mobile and immobile domain transport simulations is included in the modflow 6 supplemental technical information document."

[griddata.decay]
name = "decay"
type = "double precision"
shape = "(nodes)"
block = "griddata"
description = "is the rate coefficient for first or zero-order decay for the aqueous phase of the mobile domain.  a negative value indicates solute production.  the dimensions of decay for first-order decay is one over time.  the dimensions of decay for zero-order decay is mass per length cubed per time.  decay will have no effect on simulation results unless either first- or zero-order decay is specified in the options block."

[griddata.decay_sorbed]
name = "decay_sorbed"
type = "double precision"
shape = "(nodes)"
block = "griddata"
description = "is the rate coefficient for first or zero-order decay for the sorbed phase of the mobile domain.  a negative value indicates solute production.  the dimensions of decay_sorbed for first-order decay is one over time.  the dimensions of decay_sorbed for zero-order decay is mass of solute per mass of aquifer per time.  if decay_sorbed is not specified and both decay and sorption are active, then the program will terminate with an error.  decay_sorbed will have no effect on simulation results unless the sorption keyword and either first- or zero-order decay are specified in the options block."

[griddata.bulk_density]
name = "bulk_density"
type = "double precision"
shape = "(nodes)"
block = "griddata"
description = "is the bulk density of the aquifer in mass per length cubed.  bulk_density is not required unless the sorption keyword is specified.  bulk density is defined as the mobile domain solid mass per mobile domain volume.  additional information on bulk density is included in the modflow 6 supplemental technical information document."

[griddata.distcoef]
name = "distcoef"
type = "double precision"
shape = "(nodes)"
block = "griddata"
description = "is the distribution coefficient for the equilibrium-controlled linear sorption isotherm in dimensions of length cubed per mass.  if the freunchlich isotherm is specified, then discoef is the freundlich constant.  if the langmuir isotherm is specified, then distcoef is the langmuir constant.  distcoef is not required unless the sorption keyword is specified."

[griddata.sp2]
name = "sp2"
type = "double precision"
shape = "(nodes)"
block = "griddata"
description = "is the exponent for the freundlich isotherm and the sorption capacity for the langmuir isotherm.  sp2 is not required unless the sorption keyword is specified in the options block.  if the sorption keyword is not specified in the options block, sp2 will have no effect on simulation results."
