name = "olf-flw"
multi = true

[options.auxiliary]
name = "auxiliary"
type = "string"
shape = "(naux)"
block = "options"
description = "defines an array of one or more auxiliary variable names.  there is no limit on the number of auxiliary variables that can be provided on this line; however, lists of information provided in subsequent blocks must have a column of data for each auxiliary variable name defined here.   the number of auxiliary variables detected on this line determines the value for naux.  comments cannot be provided anywhere on this line as they will be interpreted as auxiliary variable names.  auxiliary variables may not be used by the package, but they will be available for use by other parts of the program.  the program will terminate with an error if auxiliary variables are specified on more than one line in the options block."

[options.auxmultname]
name = "auxmultname"
type = "string"
block = "options"
description = "name of auxiliary variable to be used as multiplier of flow rate."

[options.boundnames]
name = "boundnames"
type = "keyword"
block = "options"
description = "keyword to indicate that boundary names may be provided with the list of inflow cells."

[options.print_input]
name = "print_input"
type = "keyword"
block = "options"
description = "keyword to indicate that the list of inflow information will be written to the listing file immediately after it is read."

[options.print_flows]
name = "print_flows"
type = "keyword"
block = "options"
description = "keyword to indicate that the list of inflow flow rates will be printed to the listing file for every stress period time step in which 'budget print' is specified in output control.  if there is no output control option and 'print_flows' is specified, then flow rates are printed for the last time step of each stress period."

[options.save_flows]
name = "save_flows"
type = "keyword"
block = "options"
description = "keyword to indicate that inflow flow terms will be written to the file specified with 'budget fileout' in output control."

[options.timeseries]
name = "timeseries"
type = "record"
block = "options"
description = "Contains data for the ts package. Data can be stored in a dictionary containing data for the ts package with variable names as keys and package data as values. Data just for the timeseries variable is also acceptable. See ts package documentation for more information"

[options.timeseries.subpackage]
parent = "parent_package"
key = "ts_filerecord"
val = "timeseries"
abbr = "ts"
param = "timeseries"
description = "xxx"

[options.observations]
name = "observations"
type = "record"
block = "options"
description = "Contains data for the obs package. Data can be stored in a dictionary containing data for the obs package with variable names as keys and package data as values. Data just for the observations variable is also acceptable. See obs package documentation for more information"

[options.observations.subpackage]
parent = "parent_model_or_package"
key = "obs_filerecord"
val = "observations"
abbr = "obs"
param = "continuous"

[dimensions.maxbound]
name = "maxbound"
type = "integer"
block = "dimensions"
description = "integer value specifying the maximum number of inflow cells that will be specified for use during any stress period."

[period.stress_period_data]
name = "stress_period_data"
type = "list"
shape = "(maxbound)"
block = "period"
description = ""

[period.stress_period_data.stress_period_data]
name = "stress_period_data"
type = "record"
block = "period"
description = ""

[period.stress_period_data.stress_period_data.cellid]
block = "period"
name = "cellid"
type = "integer"
shape = "(ncelldim)"
tagged = "false"
in_record = "true"
reader = "urword"
longname = "cell identifier"
description = "is the cell identifier, and depends on the type of grid that is used for the simulation.  For a structured grid that uses the DIS input file, CELLID is the layer, row, and column.   For a grid that uses the DISV input file, CELLID is the layer and CELL2D number.  If the model uses the unstructured discretization (DISU) input file, CELLID is the node number for the cell."

[period.stress_period_data.stress_period_data.q]
block = "period"
name = "q"
type = "double precision"
shape = ""
tagged = "false"
in_record = "true"
reader = "urword"
time_series = "true"
longname = "well rate"
description = "is the volumetric inflow rate. A positive value indicates inflow to the stream.  Negative values are not allows. If the Options block includes a TIMESERIESFILE entry (see the 'Time-Variable Input' section), values can be obtained from a time series by entering the time-series name in place of a numeric value."

[period.stress_period_data.stress_period_data.aux]
block = "period"
name = "aux"
type = "double precision"
in_record = "true"
tagged = "false"
shape = "(naux)"
reader = "urword"
optional = "true"
time_series = "true"
longname = "auxiliary variables"
description = "represents the values of the auxiliary variables for each inflow. The values of auxiliary variables must be present for each inflow. The values must be specified in the order of the auxiliary variables specified in the OPTIONS block.  If the package supports time series and the Options block includes a TIMESERIESFILE entry (see the 'Time-Variable Input' section), values can be obtained from a time series by entering the time-series name in place of a numeric value."

[period.stress_period_data.stress_period_data.boundname]
block = "period"
name = "boundname"
type = "string"
shape = ""
tagged = "false"
in_record = "true"
reader = "urword"
optional = "true"
longname = "inflow name"
description = "name of the inflow cell.  BOUNDNAME is an ASCII character variable that can contain as many as 40 characters.  If BOUNDNAME contains spaces in it, then the entire name must be enclosed within single quotes."
