name = "prt-oc"
multi = false

[options.budget_filerecord]
name = "budget_filerecord"
type = "record"
block = "options"

[options.budget_filerecord.budget]
block = "options"
name = "budget"
type = "keyword"
in_record = "true"
reader = "urword"
tagged = "true"
optional = "false"
longname = "budget keyword"
description = "keyword to specify that record corresponds to the budget."

[options.budget_filerecord.fileout]
block = "options"
name = "fileout"
type = "keyword"
in_record = "true"
reader = "urword"
tagged = "true"
optional = "false"
longname = "file keyword"
description = "keyword to specify that an output filename is expected next."

[options.budget_filerecord.budgetfile]
block = "options"
name = "budgetfile"
type = "string"
preserve_case = "true"
in_record = "true"
reader = "urword"
tagged = "false"
optional = "false"
longname = "file keyword"
description = "name of the output file to write budget information."

[options.budgetcsv_filerecord]
name = "budgetcsv_filerecord"
type = "record"
block = "options"

[options.budgetcsv_filerecord.budgetcsv]
block = "options"
name = "budgetcsv"
type = "keyword"
in_record = "true"
reader = "urword"
tagged = "true"
optional = "false"
longname = "budget keyword"
description = "keyword to specify that record corresponds to the budget CSV."

[options.budgetcsv_filerecord.fileout]
block = "options"
name = "fileout"
type = "keyword"
in_record = "true"
reader = "urword"
tagged = "true"
optional = "false"
longname = "file keyword"
description = "keyword to specify that an output filename is expected next."

[options.budgetcsv_filerecord.budgetcsvfile]
block = "options"
name = "budgetcsvfile"
type = "string"
preserve_case = "true"
in_record = "true"
reader = "urword"
tagged = "false"
optional = "false"
longname = "file keyword"
description = "name of the comma-separated value (CSV) output file to write budget summary information.  A budget summary record will be written to this file for each time step of the simulation."

[options.track_filerecord]
name = "track_filerecord"
type = "record"
block = "options"

[options.track_filerecord.track]
block = "options"
name = "track"
type = "keyword"
in_record = "true"
reader = "urword"
tagged = "true"
optional = "false"
longname = "track keyword"
description = "keyword to specify that record corresponds to a binary track file.  Each PRT Model's OC Package may have only one binary track output file."

[options.track_filerecord.fileout]
block = "options"
name = "fileout"
type = "keyword"
in_record = "true"
reader = "urword"
tagged = "true"
optional = "false"
longname = "file keyword"
description = "keyword to specify that an output filename is expected next."

[options.track_filerecord.trackfile]
block = "options"
name = "trackfile"
type = "string"
preserve_case = "true"
in_record = "true"
reader = "urword"
tagged = "false"
optional = "false"
longname = "file keyword"
description = "name of the binary output file to write tracking information."

[options.trackcsv_filerecord]
name = "trackcsv_filerecord"
type = "record"
block = "options"

[options.trackcsv_filerecord.trackcsv]
block = "options"
name = "trackcsv"
type = "keyword"
in_record = "true"
reader = "urword"
tagged = "true"
optional = "false"
longname = "track keyword"
description = "keyword to specify that record corresponds to a CSV track file.  Each PRT Model's OC Package may have only one CSV track file."

[options.trackcsv_filerecord.fileout]
block = "options"
name = "fileout"
type = "keyword"
in_record = "true"
reader = "urword"
tagged = "true"
optional = "false"
longname = "file keyword"
description = "keyword to specify that an output filename is expected next."

[options.trackcsv_filerecord.trackcsvfile]
block = "options"
name = "trackcsvfile"
type = "string"
preserve_case = "true"
in_record = "true"
reader = "urword"
tagged = "false"
optional = "false"
longname = "file keyword"
description = "name of the comma-separated value (CSV) file to write tracking information."

[options.track_release]
name = "track_release"
type = "keyword"
block = "options"
description = "keyword to indicate that particle tracking output is to be written when a particle is released"

[options.track_exit]
name = "track_exit"
type = "keyword"
block = "options"
description = "keyword to indicate that particle tracking output is to be written when a particle exits a feature (a model, cell, or subcell)"

[options.track_timestep]
name = "track_timestep"
type = "keyword"
block = "options"
description = "keyword to indicate that particle tracking output is to be written at the end of each time step"

[options.track_terminate]
name = "track_terminate"
type = "keyword"
block = "options"
description = "keyword to indicate that particle tracking output is to be written when a particle terminates for any reason"

[options.track_weaksink]
name = "track_weaksink"
type = "keyword"
block = "options"
description = "keyword to indicate that particle tracking output is to be written when a particle exits a weak sink (a cell which removes some but not all inflow from adjacent cells)"

[options.track_usertime]
name = "track_usertime"
type = "keyword"
block = "options"
description = "keyword to indicate that particle tracking output is to be written at user-specified times, provided as double precision values in the tracktimes block."

[dimensions.ntracktimes]
name = "ntracktimes"
type = "integer"
block = "dimensions"
description = "is the number of user-specified particle tracking times in the tracktimes block."

[tracktimes.tracktimes]
name = "tracktimes"
type = "list"
shape = "(ntracktimes)"
block = "tracktimes"

[tracktimes.tracktimes.tracktimes]
name = "tracktimes"
type = "record"
block = "tracktimes"

[tracktimes.tracktimes.tracktimes.time]
block = "tracktimes"
name = "time"
type = "double precision"
tagged = "false"
in_record = "true"
reader = "urword"
longname = "release time"
description = "real value that defines the tracking time with respect to the simulation start time."

[period.saverecord]
name = "saverecord"
type = "record"
block = "period"

[period.saverecord.save]
block = "period"
name = "save"
type = "keyword"
in_record = "true"
reader = "urword"
tagged = "true"
optional = "false"
longname = "keyword to save"
description = "keyword to indicate that information will be saved this stress period."

[period.saverecord.rtype]
block = "period"
name = "rtype"
type = "string"
in_record = "true"
reader = "urword"
tagged = "false"
optional = "false"
longname = "record type"
description = "type of information to save or print.  Can only be BUDGET."

[period.saverecord.ocsetting]
block = "period"
name = "ocsetting"
type = "keystring all first last frequency steps"
tagged = "false"
in_record = "true"
reader = "urword"
description = "specifies the steps for which the data will be saved."

[period.printrecord]
name = "printrecord"
type = "record"
block = "period"

[period.printrecord.print]
block = "period"
name = "print"
type = "keyword"
in_record = "true"
reader = "urword"
tagged = "true"
optional = "false"
longname = "keyword to save"
description = "keyword to indicate that information will be printed this stress period."

[period.printrecord.rtype]
block = "period"
name = "rtype"
type = "string"
in_record = "true"
reader = "urword"
tagged = "false"
optional = "false"
longname = "record type"
description = "type of information to save or print.  Can only be BUDGET."

[period.printrecord.ocsetting]
block = "period"
name = "ocsetting"
type = "keystring all first last frequency steps"
tagged = "false"
in_record = "true"
reader = "urword"
description = "specifies the steps for which the data will be saved."
