name = "sim-tdis"
multi = false

[options.time_units]
name = "time_units"
type = "string"
block = "options"
description = "is the time units of the simulation.  this is a text string that is used as a label within model output files.  values for time_units may be 'unknown',  'seconds', 'minutes', 'hours', 'days', or 'years'.  the default time unit is 'unknown'."

[options.start_date_time]
name = "start_date_time"
type = "string"
block = "options"
description = "is the starting date and time of the simulation.  this is a text string that is used as a label within the simulation list file.  the value has no effect on the simulation.  the recommended format for the starting date and time is described at https://www.w3.org/tr/note-datetime."

[options.ats_perioddata]
name = "ats_perioddata"
type = "record"
block = "options"
description = "Contains data for the ats package. Data can be stored in a dictionary containing data for the ats package with variable names as keys and package data as values. Data just for the ats_perioddata variable is also acceptable. See ats package documentation for more information"

[options.ats_perioddata.subpackage]
parent = "parent_package"
key = "ats_filerecord"
val = "ats_perioddata"
abbr = "ats"
param = "perioddata"

[dimensions.nper]
name = "nper"
type = "integer"
block = "dimensions"
description = "is the number of stress periods for the simulation."
default = 1

[perioddata.perioddata]
name = "perioddata"
type = "list"
block = "perioddata"
description = ""
default = [[1.0, 1, 1.0]]

[perioddata.perioddata.perioddata]
name = "perioddata"
type = "record"
block = "perioddata"
description = ""

[perioddata.perioddata.perioddata.perlen]
block = "perioddata"
name = "perlen"
type = "double precision"
in_record = "true"
tagged = "false"
reader = "urword"
optional = "false"
longname = "length of stress period"
description = "is the length of a stress period."

[perioddata.perioddata.perioddata.nstp]
block = "perioddata"
name = "nstp"
type = "integer"
in_record = "true"
tagged = "false"
reader = "urword"
optional = "false"
longname = "number of time steps"
description = "is the number of time steps in a stress period."

[perioddata.perioddata.perioddata.tsmult]
block = "perioddata"
name = "tsmult"
type = "double precision"
in_record = "true"
tagged = "false"
reader = "urword"
optional = "false"
longname = "number of time steps"
description = "is the multiplier for the length of successive time steps. The length of a time step is calculated by multiplying the length of the previous time step by TSMULT. The length of the first time step, $Delta t_1$, is related to PERLEN, NSTP, and TSMULT by the relation $Delta t_1= perlen frac{tsmult - 1}{tsmult^{nstp}-1}$."
