name = "sim-nam"
multi = false

[options.continue]
name = "continue"
type = "keyword"
block = "options"
description = "keyword flag to indicate that the simulation should continue even if one or more solutions do not converge."

[options.nocheck]
name = "nocheck"
type = "keyword"
block = "options"
description = "keyword flag to indicate that the model input check routines should not be called prior to each time step. checks are performed by default."

[options.memory_print_option]
name = "memory_print_option"
type = "string"
block = "options"
description = "is a flag that controls printing of detailed memory manager usage to the end of the simulation list file.  none means do not print detailed information. summary means print only the total memory for each simulation component. all means print information for each variable stored in the memory manager. none is default if memory_print_option is not specified."

[options.maxerrors]
name = "maxerrors"
type = "integer"
block = "options"
description = "maximum number of errors that will be stored and printed."

[options.print_input]
name = "print_input"
type = "keyword"
block = "options"
description = "keyword to activate printing of simulation input summaries to the simulation list file (mfsim.lst). with this keyword, input summaries will be written for those packages that support newer input data model routines.  not all packages are supported yet by the newer input data model routines."

[options.hpc_data]
name = "hpc_data"
type = "record"
block = "options"
description = "Contains data for the hpc package. Data can be stored in a dictionary containing data for the hpc package with variable names as keys and package data as values. Data just for the hpc variable is also acceptable. See hpc package documentation for more information"

[options.hpc_data.subpackage]
parent = "parent_package"
key = "hpc_filerecord"
val = "hpc"
abbr = "hpc"
param = "hpc_data"

[timing.tdis6]
name = "tdis6"
type = "string"
block = "timing"
description = "is the name of the temporal discretization (tdis) input file."

[models.models]
name = "models"
type = "list"
block = "models"
description = "is the list of model types, model name files, and model names."

[models.models.models]
name = "models"
type = "record"
block = "models"
description = "is the record of model types, model name files, and model names."

[models.models.models.mtype]
block = "models"
name = "mtype"
in_record = "true"
type = "string"
tagged = "false"
reader = "urword"
longname = "model type"
description = "is the type of model to add to simulation."

[models.models.models.mfname]
block = "models"
name = "mfname"
in_record = "true"
type = "string"
preserve_case = "true"
tagged = "false"
reader = "urword"
longname = "file name for model name file"
description = "is the file name of the model name file."

[models.models.models.mname]
block = "models"
name = "mname"
in_record = "true"
type = "string"
tagged = "false"
reader = "urword"
longname = "name of model"
description = "is the user-assigned name of the model.  The model name cannot exceed 16 characters and must not have blanks within the name.  The model name is case insensitive; any lowercase letters are converted and stored as upper case letters."

[exchanges.exchanges]
name = "exchanges"
type = "list"
block = "exchanges"
description = "is the list of exchange types, exchange files, and model names."

[exchanges.exchanges.exchanges]
name = "exchanges"
type = "record"
block = "exchanges"
description = "is the record of exchange types, exchange files, and model names."

[exchanges.exchanges.exchanges.exgtype]
block = "exchanges"
name = "exgtype"
in_record = "true"
type = "string"
tagged = "false"
reader = "urword"
longname = "exchange type"
description = "is the exchange type."

[exchanges.exchanges.exchanges.exgfile]
block = "exchanges"
name = "exgfile"
in_record = "true"
type = "string"
preserve_case = "true"
tagged = "false"
reader = "urword"
longname = "input file for exchange"
description = "is the input file for the exchange."

[exchanges.exchanges.exchanges.exgmnamea]
block = "exchanges"
name = "exgmnamea"
in_record = "true"
type = "string"
tagged = "false"
reader = "urword"
longname = "name of model A"
description = "is the name of the first model that is part of this exchange."

[exchanges.exchanges.exchanges.exgmnameb]
block = "exchanges"
name = "exgmnameb"
in_record = "true"
type = "string"
tagged = "false"
reader = "urword"
longname = "name of model B"
description = "is the name of the second model that is part of this exchange."

[solutiongroup.mxiter]
name = "mxiter"
type = "integer"
block = "solutiongroup"
description = "is the maximum number of outer iterations for this solution group.  the default value is 1.  if there is only one solution in the solution group, then mxiter must be 1."

[solutiongroup.solutiongroup]
name = "solutiongroup"
type = "list"
block = "solutiongroup"
description = "is the list of solution types and models in the solution."

[solutiongroup.solutiongroup.solutiongroup]
name = "solutiongroup"
type = "record"
block = "solutiongroup"
description = "is the record of solution types and models in the solution."

[solutiongroup.solutiongroup.solutiongroup.slntype]
block = "solutiongroup"
name = "slntype"
type = "string"
valid = "ims6 ems6"
in_record = "true"
tagged = "false"
reader = "urword"
longname = "type of solution"
description = "is the type of solution.  The Integrated Model Solution (IMS6) and Explicit Model Solution (EMS6) are the only supported options in this version."

[solutiongroup.solutiongroup.solutiongroup.slnfname]
block = "solutiongroup"
name = "slnfname"
type = "string"
preserve_case = "true"
in_record = "true"
tagged = "false"
reader = "urword"
longname = "file name for solution input"
description = "name of file containing solution input."

[solutiongroup.solutiongroup.solutiongroup.slnmnames]
block = "solutiongroup"
name = "slnmnames"
type = "string"
in_record = "true"
shape = "(:)"
tagged = "false"
reader = "urword"
longname = "array of model names in this solution"
description = "is the array of model names to add to this solution.  The number of model names is determined by the number of model names the user provides on this line."
