# autogenerated file, do not modify
from typing import Optional

import attrs

from flopy4.mf6.package import Package
from flopy4.mf6.spec import field


@attrs.define(kw_only=True, slots=False)
class Adv(Package):
    scheme: Optional[str] = field(
        default=None,
        block="options",
        dfn_type="string",
        optional=True,
    )
    ats_percel: Optional[float] = field(
        default=None,
        block="options",
        dfn_type="double",
        optional=True,
    )
