# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

import attrs

from flopy4.dimensions import DerivedDim
from flopy4.mf6._types import FloatArrayLike, IntArrayLike
from flopy4.mf6.dis_methods import DisMethods
from flopy4.mf6.grid_dims_methods import GridDimsMethods
from flopy4.mf6.package import Package
from flopy4.mf6.spec import child, field, path
from flopy4.mf6.utl.ncf import Ncf


@attrs.define(kw_only=True, slots=False)
class Dis(DisMethods, GridDimsMethods, Package):
    dfn_name: ClassVar[str] = "gwe-dis"

    length_units: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
        longname="model length units",
    )
    nogrb: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="do not write binary grid file",
    )
    grb_file: Optional[Path] = path(
        default=None,
        converter=attrs.converters.optional(Path),
        block="options",
        optional=True,
        direction="out",
        keyword="grb6",
    )
    xorigin: Optional[float] = field(
        default=None,
        block="options",
        optional=True,
        longname="x-position of the model grid origin",
    )
    yorigin: Optional[float] = field(
        default=None,
        block="options",
        optional=True,
        longname="y-position of the model grid origin",
    )
    angrot: Optional[float] = field(
        default=None,
        block="options",
        optional=True,
        longname="rotation angle",
    )
    export_array_ascii: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="export array variables to layered ascii files.",
    )
    export_array_netcdf: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="export array variables to netcdf output files.",
    )
    crs: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
        longname="CRS user input string",
    )
    ncf: Optional[Ncf] = child(block="options", keyword="ncf6", direction="in")
    nlay: Optional[int] = field(
        default=1,
        block="dimensions",
        longname="number of layers",
    )
    nrow: Optional[int] = field(
        default=2,
        block="dimensions",
        longname="number of rows",
    )
    ncol: Optional[int] = field(
        default=2,
        block="dimensions",
        longname="number of columns",
    )
    delr: FloatArrayLike = field(
        default=1.0,
        block="griddata",
        shape=("ncol",),
        netcdf=True,
        longname="spacing along a row",
    )  # type: ignore[assignment]
    delc: FloatArrayLike = field(
        default=1.0,
        block="griddata",
        shape=("nrow",),
        netcdf=True,
        longname="spacing along a column",
    )  # type: ignore[assignment]
    top: FloatArrayLike = field(
        default=1.0,
        block="griddata",
        shape=("ncpl",),
        netcdf=True,
        longname="cell top elevation",
    )  # type: ignore[assignment]
    botm: FloatArrayLike = field(
        default=0.0,
        block="griddata",
        shape=("nodes",),
        layered=True,
        netcdf=True,
        longname="cell bottom elevation",
    )  # type: ignore[assignment]
    idomain: Optional[IntArrayLike] = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        layered=True,
        netcdf=True,
        optional=True,
        longname="idomain existence array",
    )

    ncpl = DerivedDim("nrow * ncol")
    nodes = DerivedDim("nlay * nrow * ncol")
    ncelldim = DerivedDim("3")
