# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional, Union

import attrs
import numpy as np

from flopy4.mf6.package import Package
from flopy4.mf6.schema import Column, Schema
from flopy4.mf6.spec import field, path


@attrs.define(kw_only=True, slots=False)
class Fmi(Package):
    save_flows: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    flow_imbalance_correction: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    packagedata: Optional[np.recarray] = field(
        default=None,
        block="packagedata",
        schema="__packagedata_schema__",
    )

    class _PackagedataSchema(Schema):
        flowtype = Column("flowtype", role="value", dfn_type="string", dtype="np.object_")
        fname = Column(
            "fname",
            role="value",
            dfn_type="string",
            dtype="np.object_",
            prefix="FILEIN",
        )

    __packagedata_schema__: ClassVar[type[Schema]] = _PackagedataSchema

    @attrs.define
    class PackagedataRow:
        flowtype: Union[float, str]
        fname: Path = path(converter=Path, inout="filein")

        def __iter__(self):
            yield self.flowtype
            yield self.fname

    packagedata_dtype: np.dtype = attrs.field(init=False, factory=lambda: np.dtype([]))
    period_dtype: np.dtype = attrs.field(init=False, factory=lambda: np.dtype([]))


FmiPackagedataRow = Fmi.PackagedataRow
