# autogenerated file, do not modify
# ruff: noqa: E501
from typing import ClassVar, Optional

import attrs
import numpy as np
from attrs import Converter
from numpy.typing import NDArray
from xattree import xattree

from flopy4.mf6.converter import structure_array
from flopy4.mf6.package import Package
from flopy4.mf6.spec import array, dim, field


@xattree(kw_only=True)
class Fmi(Package):
    save_flows: bool = field(
        block="options",
        default=False,
        longname="save calculated flow imbalance correction to budget file",
    )
    flow_imbalance_correction: bool = field(
        block="options", default=False, longname="correct for flow imbalance"
    )
    _packagedata: Optional[dict] = attrs.field(alias="packagedata", default=None, repr=False)
    npackagedata: Optional[int] = dim(block="__dim__", coord=False, default=None)
    flowtype: Optional[NDArray[np.object_]] = array(
        block="packagedata",
        dims=("npackagedata",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="flow type",
    )
    fname: Optional[NDArray[np.object_]] = array(
        block="packagedata",
        dims=("npackagedata",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="file name",
        prefix=("FILEIN",),
    )
    __block_col_maps__: ClassVar[dict] = {
        "packagedata": {
            "flowtype": "flowtype",
            "fname": "fname",
        },
    }

    def __attrs_post_init__(self):
        if self._packagedata is not None:
            self._set_block(
                "packagedata",
                "npackagedata",
                False,
                {
                    "flowtype": "flowtype",
                    "fname": "fname",
                },
                self._packagedata,
            )

    @property
    def packagedata(self):
        return self._get_block(
            {
                "flowtype": "flowtype",
                "fname": "fname",
            }
        )

    @packagedata.setter
    def packagedata(self, value) -> None:
        self._set_block(
            "packagedata",
            "npackagedata",
            False,
            {
                "flowtype": "flowtype",
                "fname": "fname",
            },
            value,
        )
