# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

import attrs
import numpy as np

from flopy4.mf6._types import _optional_path
from flopy4.mf6.package import Package
from flopy4.mf6.schema import Column, Schema
from flopy4.mf6.spec import field, path


@attrs.define(kw_only=True, slots=False)
class Lke(Package):
    multi_package: ClassVar[bool] = True

    flow_package_name: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
    )
    auxiliary: Optional[list[str]] = field(
        default=None,
        block="options",
        shape=(),
        optional=True,
    )
    flow_package_auxiliary_name: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
    )
    boundnames: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    print_input: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    print_temperature: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    print_flows: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    save_flows: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    temperature_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        inout="fileout",
    )
    budget_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        inout="fileout",
    )
    budgetcsv_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        inout="fileout",
    )
    ts_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        inout="filein",
    )
    obs_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        inout="filein",
    )
    packagedata: Optional[np.recarray] = field(
        default=None,
        block="packagedata",
        schema="__packagedata_schema__",
    )
    # TODO: laksetting — type 'union' not yet supported
    _stress_period_data: Optional[dict[int, np.recarray]] = field(
        alias="stress_period_data",
        default=None,
        repr=False,
        block="period",
        schema="__period_schema__",
        fill_forward=True,
    )

    class _PackagedataSchema(Schema):
        lakeno = Column("lakeno", role="feature_id", dfn_type="integer")
        strt = Column("strt", role="value", dfn_type="double")
        ktf = Column("ktf", role="value", dfn_type="double")
        rbthcnd = Column("rbthcnd", role="value", dfn_type="double")
        boundname = Column("boundname", role="boundname", dfn_type="string")

    __packagedata_schema__: ClassVar[type[Schema]] = _PackagedataSchema

    @attrs.define
    class PackagedataRow:
        lakeno: int
        strt: float
        ktf: float
        rbthcnd: float
        boundname: Optional[str] = None

        def __iter__(self):
            yield self.lakeno
            yield self.strt
            yield self.ktf
            yield self.rbthcnd
            yield self.boundname

    @attrs.define
    class Row:
        lakeno: int
        keyword: str
        value: object

        def __iter__(self):
            yield self.lakeno
            yield self.keyword
            yield self.value

    class _PeriodSchema(Schema):
        lakeno = Column("lakeno", role="feature_id", dfn_type="integer")
        keyword = Column("keyword", role="keystring", dfn_type="string")
        value = Column("value", role="keystring_value", dfn_type="object")

    __period_schema__: ClassVar[type[Schema]] = _PeriodSchema

    packagedata_dtype: np.dtype = attrs.field(init=False, factory=lambda: np.dtype([]))
    period_dtype: np.dtype = attrs.field(init=False, factory=lambda: np.dtype([]))


LkeRow = Lke.Row
LkePackagedataRow = Lke.PackagedataRow
