# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional, Union

import attrs

from flopy4.mf6._types import _optional_path
from flopy4.mf6.item import Item
from flopy4.mf6.package import Package
from flopy4.mf6.spec import field, path


@attrs.define(kw_only=True, slots=False)
class Lke(Package):
    dfn_name: ClassVar[str] = "gwe-lke"

    multi_package: ClassVar[bool] = True

    @attrs.define
    class Packagedata(Item):
        lakeno: int = field(index=True, pk=True)
        strt: float = field()
        ktf: float = field()
        rbthcnd: float = field()
        aux: tuple = ()
        boundname: Optional[str] = field(default=None, optional=True)

    @attrs.define
    class Status(Item):
        _keyword: ClassVar[str] = "status"
        lakeno: int = field(index=True, fk="packagedata.lakeno")
        status: Union[float, str] = field()

    @attrs.define
    class Temperature(Item):
        _keyword: ClassVar[str] = "temperature"
        lakeno: int = field(index=True, fk="packagedata.lakeno")
        temperature: Union[float, str] = field(time_series=True)

    @attrs.define
    class Rainfall(Item):
        _keyword: ClassVar[str] = "rainfall"
        lakeno: int = field(index=True, fk="packagedata.lakeno")
        rainfall: Union[float, str] = field(time_series=True)

    @attrs.define
    class Evaporation(Item):
        _keyword: ClassVar[str] = "evaporation"
        lakeno: int = field(index=True, fk="packagedata.lakeno")
        evaporation: Union[float, str] = field(time_series=True)

    @attrs.define
    class Runoff(Item):
        _keyword: ClassVar[str] = "runoff"
        lakeno: int = field(index=True, fk="packagedata.lakeno")
        runoff: Union[float, str] = field(time_series=True)

    @attrs.define
    class ExtInflow(Item):
        _keyword: ClassVar[str] = "ext-inflow"
        lakeno: int = field(index=True, fk="packagedata.lakeno")
        ext_inflow: Union[float, str] = field(time_series=True)

    @attrs.define
    class Auxiliary(Item):
        _keyword: ClassVar[str] = "auxiliary"
        lakeno: int = field(index=True, fk="packagedata.lakeno")
        auxname: Union[float, str] = field()
        auxval: Union[float, str] = field(time_series=True)

    _StressPeriodDataItem = (
        Status | Temperature | Rainfall | Evaporation | Runoff | ExtInflow | Auxiliary
    )

    flow_package_name: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
        longname="keyword to specify name of corresponding flow package",
    )
    auxiliary: Optional[list[str]] = field(
        default=None,
        block="options",
        optional=True,
        longname="keyword to specify aux variables",
    )
    flow_package_auxiliary_name: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
        longname="keyword to specify name of temperature auxiliary variable in flow package",
    )
    boundnames: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    print_input: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="print input to listing file",
    )
    print_temperature: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="print calculated temperatures to listing file",
    )
    print_flows: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="print calculated flows to listing file",
    )
    save_flows: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="save lake flows to budget file",
    )
    temperature_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="out",
        keyword="temperature",
    )
    budget_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="out",
        keyword="budget",
    )
    budgetcsv_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="out",
        keyword="budgetcsv",
    )
    ts_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="in",
        keyword="ts6",
    )
    obs_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="in",
        keyword="obs6",
    )
    packagedata: Optional[list[Packagedata]] = field(
        default=None,
        block="packagedata",
        write_if_empty=True,
    )
    _stress_period_data: Optional[dict[int, list[_StressPeriodDataItem]]] = field(
        alias="stress_period_data",
        default=None,
        repr=False,
        block="period",
        fill_forward=True,
    )


LkePackagedata = Lke.Packagedata
LkeStatus = Lke.Status
LkeTemperature = Lke.Temperature
LkeRainfall = Lke.Rainfall
LkeEvaporation = Lke.Evaporation
LkeRunoff = Lke.Runoff
LkeExtInflow = Lke.ExtInflow
LkeAuxiliary = Lke.Auxiliary
