# autogenerated file, do not modify
from pathlib import Path
from typing import Optional

import attrs

from flopy4.mf6.package import Package
from flopy4.utils import to_path


@attrs.define(kw_only=True, slots=False)
class Mve(Package):
    print_input: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    print_flows: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    save_flows: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    budget_file: Optional[Path] = attrs.field(
        default=None,
        converter=lambda v: None if v is None else to_path(v),
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "fileout",
        },
    )
    budgetcsv_file: Optional[Path] = attrs.field(
        default=None,
        converter=lambda v: None if v is None else to_path(v),
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "fileout",
        },
    )
