# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

import attrs

from flopy4.mf6._types import _optional_path
from flopy4.mf6.package import Package
from flopy4.mf6.record import Record
from flopy4.mf6.spec import field, path


@attrs.define(kw_only=True, slots=False)
class Oc(Package):
    @attrs.define
    class Temperatureprint(Record):
        _keyword: ClassVar[str] = "temperature"
        _extra_tokens: ClassVar[tuple[str, ...]] = ("PRINT_FORMAT",)
        format_: str = attrs.field()
        columns: Optional[int] = attrs.field(default=None, metadata={"tagged": True})
        width: Optional[int] = attrs.field(default=None, metadata={"tagged": True})
        digits: Optional[int] = attrs.field(default=None, metadata={"tagged": True})

    budget_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        inout="fileout",
    )
    budgetcsv_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        inout="fileout",
    )
    temperature_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        inout="fileout",
    )
    temperatureprint: Optional[Temperatureprint] = field(
        default=None,
        block="options",
    )
    save_temperature: Optional[dict[int, list[str]]] = field(
        default=None,
        block="period",
        oc_action="save",
        oc_rtype="temperature",
    )
    save_budget: Optional[dict[int, list[str]]] = field(
        default=None,
        block="period",
        oc_action="save",
        oc_rtype="budget",
    )
    print_temperature: Optional[dict[int, list[str]]] = field(
        default=None,
        block="period",
        oc_action="print",
        oc_rtype="temperature",
    )
    print_budget: Optional[dict[int, list[str]]] = field(
        default=None,
        block="period",
        oc_action="print",
        oc_rtype="budget",
    )
