# autogenerated file, do not modify
from typing import ClassVar, Optional

import attrs
import numpy as np

from flopy4.mf6.package import Package


@attrs.define(kw_only=True, slots=False)
class Ssm(Package):
    print_flows: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    save_flows: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    sources: Optional[np.recarray] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "sources",
            "schema": "__sources_schema__",
            "always_emit": True,
        },
    )
    fileinput: Optional[np.recarray] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "fileinput",
            "schema": "__fileinput_schema__",
        },
    )
    __sources_schema__: ClassVar[list[dict]] = [
        {
            "name": "pname",
            "dfn_type": "string",
            "role": "value",
            "dtype": "np.object_",
        },
        {
            "name": "srctype",
            "dfn_type": "string",
            "role": "value",
            "dtype": "np.object_",
        },
        {
            "name": "auxname",
            "dfn_type": "string",
            "role": "value",
            "dtype": "np.object_",
        },
    ]

    __fileinput_schema__: ClassVar[list[dict]] = [
        {
            "name": "pname",
            "dfn_type": "string",
            "role": "value",
            "dtype": "np.object_",
        },
        {
            "name": "spc6_filename",
            "dfn_type": "string",
            "role": "value",
            "dtype": "np.object_",
            "prefix": "SPC6 FILEIN",
        },
        {
            "name": "mixed",
            "dfn_type": "keyword",
            "role": "inline_keyword",
            "optional": True,
        },
    ]

    sources_dtype: np.dtype = attrs.field(init=False, factory=lambda: np.dtype([]))
    fileinput_dtype: np.dtype = attrs.field(init=False, factory=lambda: np.dtype([]))
    period_dtype: np.dtype = attrs.field(init=False, factory=lambda: np.dtype([]))
