# autogenerated file, do not modify
from typing import ClassVar, Optional

import attrs
import numpy as np

from flopy4.mf6.package import Package
from flopy4.mf6.schema import Column, Schema


@attrs.define(kw_only=True, slots=False)
class Ssm(Package):
    print_flows: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    save_flows: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    sources: Optional[np.recarray] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "sources",
            "schema": "__sources_schema__",
            "always_emit": True,
        },
    )
    fileinput: Optional[np.recarray] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "fileinput",
            "schema": "__fileinput_schema__",
        },
    )

    class _SourcesSchema(Schema):
        pname = Column("pname", role="value", dfn_type="string", dtype="np.object_")
        srctype = Column("srctype", role="value", dfn_type="string", dtype="np.object_")
        auxname = Column("auxname", role="value", dfn_type="string", dtype="np.object_")

    __sources_schema__: ClassVar[type[Schema]] = _SourcesSchema

    class _FileinputSchema(Schema):
        pname = Column("pname", role="value", dfn_type="string", dtype="np.object_")
        spc6_filename = Column(
            "spc6_filename",
            role="value",
            dfn_type="string",
            dtype="np.object_",
            prefix="SPC6 FILEIN",
        )
        mixed = Column("mixed", role="inline_keyword", dfn_type="keyword", optional=True)

    __fileinput_schema__: ClassVar[type[Schema]] = _FileinputSchema

    sources_dtype: np.dtype = attrs.field(init=False, factory=lambda: np.dtype([]))
    fileinput_dtype: np.dtype = attrs.field(init=False, factory=lambda: np.dtype([]))
    period_dtype: np.dtype = attrs.field(init=False, factory=lambda: np.dtype([]))
