# autogenerated file, do not modify
# ruff: noqa: E501
from typing import ClassVar, Optional

import attrs
import numpy as np
from attrs import Converter
from numpy.typing import NDArray
from xattree import xattree

from flopy4.mf6.converter import structure_array
from flopy4.mf6.package import Package
from flopy4.mf6.spec import array, dim, field


@xattree(kw_only=True)
class Ssm(Package):
    print_flows: bool = field(
        block="options", default=False, longname="print calculated flows to listing file"
    )
    save_flows: bool = field(
        block="options", default=False, longname="save calculated flows to budget file"
    )
    _sources: Optional[dict] = attrs.field(alias="sources", default=None, repr=False)
    nsources: Optional[int] = dim(block="__dim__", coord=False, default=None)
    sources_pname: Optional[NDArray[np.object_]] = array(
        block="sources",
        dims=("nsources",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="package name",
    )
    srctype: Optional[NDArray[np.object_]] = array(
        block="sources",
        dims=("nsources",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="source type",
    )
    auxname: Optional[NDArray[np.object_]] = array(
        block="sources",
        dims=("nsources",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="auxiliary variable name",
    )
    _fileinput: Optional[dict] = attrs.field(alias="fileinput", default=None, repr=False)
    nfileinput: Optional[int] = dim(block="__dim__", coord=False, default=None)
    fileinput_pname: Optional[NDArray[np.object_]] = array(
        block="fileinput",
        dims=("nfileinput",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="package name",
    )
    spc6_filename: Optional[NDArray[np.object_]] = array(
        block="fileinput",
        dims=("nfileinput",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="spc file name",
        prefix=("SPC6", "FILEIN"),
    )
    mixed: Optional[NDArray[np.bool_]] = array(
        block="fileinput",
        dims=("nfileinput",),
        default=None,
        longname="mixed keyword",
        row_keyword="MIXED",
    )
    __block_col_maps__: ClassVar[dict] = {
        "sources": {
            "pname": "sources_pname",
            "srctype": "srctype",
            "auxname": "auxname",
        },
        "fileinput": {
            "pname": "fileinput_pname",
            "spc6_filename": "spc6_filename",
            "mixed": "mixed",
        },
    }

    def __attrs_post_init__(self):
        if self._sources is not None:
            self._set_block(
                "sources",
                "nsources",
                False,
                {
                    "pname": "sources_pname",
                    "srctype": "srctype",
                    "auxname": "auxname",
                },
                self._sources,
            )
        if self._fileinput is not None:
            self._set_block(
                "fileinput",
                "nfileinput",
                False,
                {
                    "pname": "fileinput_pname",
                    "spc6_filename": "spc6_filename",
                    "mixed": "mixed",
                },
                self._fileinput,
            )

    @property
    def sources(self):
        return self._get_block(
            {
                "pname": "sources_pname",
                "srctype": "srctype",
                "auxname": "auxname",
            }
        )

    @sources.setter
    def sources(self, value) -> None:
        self._set_block(
            "sources",
            "nsources",
            False,
            {
                "pname": "sources_pname",
                "srctype": "srctype",
                "auxname": "auxname",
            },
            value,
        )

    @property
    def fileinput(self):
        return self._get_block(
            {
                "pname": "fileinput_pname",
                "spc6_filename": "spc6_filename",
                "mixed": "mixed",
            }
        )

    @fileinput.setter
    def fileinput(self, value) -> None:
        self._set_block(
            "fileinput",
            "nfileinput",
            False,
            {
                "pname": "fileinput_pname",
                "spc6_filename": "spc6_filename",
                "mixed": "mixed",
            },
            value,
        )
