# autogenerated file, do not modify
from typing import ClassVar, Optional

import attrs
import numpy as np

from flopy4.mf6.package import Package


@attrs.define(kw_only=True, slots=False)
class Ats(Package):
    maxats: Optional[int] = attrs.field(
        default="1",
        metadata={
            "dfn_block": "dimensions",
            "dfn_type": "integer",
        },
    )  # type: ignore[assignment]
    perioddata: Optional[np.recarray] = attrs.field(
        default=None, metadata={"dfn_block": "perioddata", "schema": "__perioddata_schema__"}
    )
    __perioddata_schema__: ClassVar[list[dict]] = [
        {
            "name": "iperats",
            "dfn_type": "integer",
            "role": "feature_id",
        },
        {
            "name": "dt0",
            "dfn_type": "double",
            "role": "value",
        },
        {
            "name": "dtmin",
            "dfn_type": "double",
            "role": "value",
        },
        {
            "name": "dtmax",
            "dfn_type": "double",
            "role": "value",
        },
        {
            "name": "dtadj",
            "dfn_type": "double",
            "role": "value",
        },
        {
            "name": "dtfailadj",
            "dfn_type": "double",
            "role": "value",
        },
    ]

    perioddata_dtype: np.dtype = attrs.field(init=False, factory=lambda: np.dtype([]))
    period_dtype: np.dtype = attrs.field(init=False, factory=lambda: np.dtype([]))
