# autogenerated file, do not modify
# ruff: noqa: E501
from typing import Optional

import numpy as np
from attrs import Converter
from numpy.typing import NDArray
from xattree import xattree

from flopy4.mf6.converter import structure_array
from flopy4.mf6.package import Package
from flopy4.mf6.spec import array, dim


@xattree(kw_only=True)
class Ats(Package):
    maxats: Optional[int] = dim(
        block="dimensions", coord=False, default="1", longname="number of ATS periods"
    )
    iperats: Optional[NDArray[np.int64]] = array(
        block="perioddata",
        dims=("maxats",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="stress period indicator",
    )
    dt0: Optional[NDArray[np.float64]] = array(
        block="perioddata",
        dims=("maxats",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="initial time step length",
    )
    dtmin: Optional[NDArray[np.float64]] = array(
        block="perioddata",
        dims=("maxats",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="minimum time step length",
    )
    dtmax: Optional[NDArray[np.float64]] = array(
        block="perioddata",
        dims=("maxats",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="maximum time step length",
    )
    dtadj: Optional[NDArray[np.float64]] = array(
        block="perioddata",
        dims=("maxats",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="time step multiplier factor",
    )
    dtfailadj: Optional[NDArray[np.float64]] = array(
        block="perioddata",
        dims=("maxats",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="divisor for failed time steps",
    )
