# autogenerated file, do not modify
from typing import ClassVar, Optional

from pydantic import SkipValidation
from pydantic.dataclasses import dataclass

from flopy4.mf6.item import Item
from flopy4.mf6.package import CFG, Package
from flopy4.mf6.spec import field


@dataclass(config=CFG, kw_only=True)
class Ats(Package):
    dfn_name: ClassVar[str] = "utl-ats"

    @dataclass(config=CFG)
    class Perioddata(Item):
        iperats: int = field(index=True, pk=True)
        dt0: float = field()
        dtmin: float = field()
        dtmax: float = field()
        dtadj: float = field()
        dtfailadj: float = field()

    maxats: Optional[int] = field(
        default=1,
        block="dimensions",
        longname="number of ATS periods",
    )
    perioddata: Optional[SkipValidation[list[Perioddata]]] = field(
        default=None,
        block="perioddata",
        auto_from="perioddata",
    )


AtsPerioddata = Ats.Perioddata
