# autogenerated file, do not modify
# ruff: noqa: E501
from typing import ClassVar, Optional

import attrs
import numpy as np
from attrs import Converter
from numpy.typing import NDArray
from xattree import xattree

from flopy4.mf6.converter import structure_array
from flopy4.mf6.package import Package
from flopy4.mf6.spec import array, dim, field


@xattree(kw_only=True)
class Hpc(Package):
    print_table: bool = field(
        block="options", default=False, longname="model print table to listing file"
    )
    dev_log_mpi: bool = field(block="options", default=False, longname="log mpi traffic")
    _partitions: Optional[dict] = attrs.field(alias="partitions", default=None, repr=False)
    npartitions: Optional[int] = dim(block="__dim__", coord=False, default=None)
    mname: Optional[NDArray[np.object_]] = array(
        block="partitions",
        dims=("npartitions",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="model name",
    )
    mrank: Optional[NDArray[np.int64]] = array(
        block="partitions",
        dims=("npartitions",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="model rank",
    )
    __block_col_maps__: ClassVar[dict] = {
        "partitions": {
            "mname": "mname",
            "mrank": "mrank",
        },
    }

    def __attrs_post_init__(self):
        if self._partitions is not None:
            self._set_block(
                "partitions",
                "npartitions",
                False,
                {
                    "mname": "mname",
                    "mrank": "mrank",
                },
                self._partitions,
            )

    @property
    def partitions(self):
        return self._get_block(
            {
                "mname": "mname",
                "mrank": "mrank",
            }
        )

    @partitions.setter
    def partitions(self, value) -> None:
        self._set_block(
            "partitions",
            "npartitions",
            False,
            {
                "mname": "mname",
                "mrank": "mrank",
            },
            value,
        )
