# autogenerated file, do not modify
from typing import ClassVar, Optional

import attrs
import numpy as np

from flopy4.mf6.package import Package


@attrs.define(kw_only=True, slots=False)
class Hpc(Package):
    print_table: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    dev_log_mpi: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    partitions: Optional[np.recarray] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "partitions",
            "schema": "__partitions_schema__",
        },
    )
    __partitions_schema__: ClassVar[list[dict]] = [
        {
            "name": "mname",
            "dfn_type": "string",
            "role": "value",
            "dtype": "np.object_",
        },
        {
            "name": "mrank",
            "dfn_type": "integer",
            "role": "value",
        },
    ]

    partitions_dtype: np.dtype = attrs.field(init=False, factory=lambda: np.dtype([]))
    period_dtype: np.dtype = attrs.field(init=False, factory=lambda: np.dtype([]))

    _DTYPE_MAP: ClassVar[dict] = {
        "integer": np.int64,
        "double": np.float64,
        "double precision": np.float64,
        "string": np.object_,
        "keyword": np.object_,
        "object": np.object_,
    }

    def __attrs_post_init__(self) -> None:
        _aux_tmp = getattr(self, "auxiliary", None)
        naux = len(_aux_tmp) if _aux_tmp is not None else 0
        ncelldim = self._compute_ncelldim()
        _partitions_f: list[tuple] = []
        for _col in self.__partitions_schema__:
            _role = _col.get("role", "value")
            _dt = _col.get("dtype")
            _dt = (
                eval(_dt)
                if _dt
                else self._DTYPE_MAP.get(_col.get("dfn_type", "string"), np.object_)
            )
            if _role == "cellid":
                _partitions_f.append((_col["name"], np.int64, (ncelldim,)))
            elif _role == "feature_id":
                _partitions_f.append((_col["name"], np.int64))
            elif _role == "boundname":
                if getattr(self, "boundnames", False):
                    _partitions_f.append((_col["name"], np.object_))
            else:
                _partitions_f.append((_col["name"], _dt))
        if "partitions" == "packagedata":
            for _i in range(naux):
                _partitions_f.append((f"aux{_i}", np.object_))
        self.partitions_dtype = np.dtype(_partitions_f)
        _raw_partitions = getattr(self, "partitions", None)
        if _raw_partitions is not None:
            self.partitions = self._coerce_to_recarray(_raw_partitions, self.partitions_dtype)
        if getattr(self, "partitions", None) is not None and getattr(self, "npartitionss", 0) == 0:
            object.__setattr__(self, "npartitionss", len(getattr(self, "partitions")))
        super().__attrs_post_init__()

    @property  # type: ignore[override]
    def stress_period_data(self) -> "Optional[dict[int, np.recarray]]":
        return self._stress_period_data

    @stress_period_data.setter
    def stress_period_data(self, value) -> None:
        self._stress_period_data = value

    def to_dataframe(self) -> "pandas.DataFrame":  # type: ignore[name-defined]
        """Return stress period data as a tidy pd.DataFrame. Zero cost if not called."""
        import pandas as pd

        _spd = self._stress_period_data
        if not _spd:
            return pd.DataFrame()
        frames = []
        for kper in sorted(_spd):
            arr = _spd[kper]
            rows = {}
            for nm in arr.dtype.names or ():
                col = arr[nm]
                rows[nm] = [tuple(v) for v in col] if col.ndim > 1 else col.tolist()
            df = pd.DataFrame(rows)
            df.insert(0, "kper", kper)
            frames.append(df)
        return pd.concat(frames, ignore_index=True)
