# autogenerated file, do not modify
from typing import ClassVar, Optional

import attrs

from flopy4.mf6.item import Item
from flopy4.mf6.package import Package
from flopy4.mf6.spec import field


@attrs.define(kw_only=True, slots=False)
class Laktab(Package):
    dfn_name: ClassVar[str] = "utl-laktab"

    multi_package: ClassVar[bool] = True

    @attrs.define
    class Table(Item):
        stage: float = field()
        volume: float = field()
        sarea: float = field()
        barea: Optional[float] = field(default=None, optional=True)

    nrow: Optional[int] = field(
        default=None,
        block="dimensions",
    )
    ncol: Optional[int] = field(
        default=None,
        block="dimensions",
    )
    table: Optional[list[Table]] = field(
        default=None,
        block="table",
        auto_from="table",
    )

LaktabTable = Laktab.Table
