# autogenerated file, do not modify
# ruff: noqa: E501
from typing import ClassVar, Optional

import attrs
import numpy as np
from attrs import Converter
from numpy.typing import NDArray
from xattree import xattree

from flopy4.mf6.converter import structure_array
from flopy4.mf6.package import Package
from flopy4.mf6.spec import array, dim


@xattree(kw_only=True)
class Laktab(Package):
    multi_package: ClassVar[bool] = True

    nrow: Optional[int] = dim(
        block="dimensions", coord=False, default=None, longname="number of table rows"
    )
    ncol: Optional[int] = dim(
        block="dimensions", coord=False, default=None, longname="number of table columns"
    )
    _table: Optional[dict] = attrs.field(alias="table", default=None, repr=False)
    stage: Optional[NDArray[np.float64]] = array(
        block="table",
        dims=("nrow",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="lake stage",
    )
    volume: Optional[NDArray[np.float64]] = array(
        block="table",
        dims=("nrow",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="lake volume",
    )
    sarea: Optional[NDArray[np.float64]] = array(
        block="table",
        dims=("nrow",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="lake surface area",
    )
    barea: Optional[NDArray[np.float64]] = array(
        block="table",
        dims=("nrow",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="lake-GWF exchange area",
    )
    __block_col_maps__: ClassVar[dict] = {
        "table": {
            "stage": "stage",
            "volume": "volume",
            "sarea": "sarea",
            "barea": "barea",
        },
    }

    def __attrs_post_init__(self):
        if self._table is not None:
            self._set_block(
                "table",
                "nrow",
                True,
                {
                    "stage": "stage",
                    "volume": "volume",
                    "sarea": "sarea",
                    "barea": "barea",
                },
                self._table,
            )

    @property
    def table(self):
        return self._get_block(
            {
                "stage": "stage",
                "volume": "volume",
                "sarea": "sarea",
                "barea": "barea",
            }
        )

    @table.setter
    def table(self, value) -> None:
        self._set_block(
            "table",
            "nrow",
            True,
            {
                "stage": "stage",
                "volume": "volume",
                "sarea": "sarea",
                "barea": "barea",
            },
            value,
        )
