# autogenerated file, do not modify
# ruff: noqa: E501
from typing import ClassVar, Optional

import numpy as np
from attrs import Converter
from numpy.typing import NDArray
from xattree import xattree

from flopy4.mf6.converter import structure_array
from flopy4.mf6.package import Package
from flopy4.mf6.spec import array, dim


@xattree(kw_only=True)
class Laktab(Package):
    multi_package: ClassVar[bool] = True

    nrow: Optional[int] = dim(
        block="dimensions", coord=False, default=None, longname="number of table rows"
    )
    ncol: Optional[int] = dim(
        block="dimensions", coord=False, default=None, longname="number of table columns"
    )
    stage: Optional[NDArray[np.float64]] = array(
        block="table",
        dims=("nrow",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="lake stage",
    )
    volume: Optional[NDArray[np.float64]] = array(
        block="table",
        dims=("nrow",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="lake volume",
    )
    sarea: Optional[NDArray[np.float64]] = array(
        block="table",
        dims=("nrow",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="lake surface area",
    )
    barea: Optional[NDArray[np.float64]] = array(
        block="table",
        dims=("nrow",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="lake-gwf exchange area",
    )
