# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional, Union

import attrs

from flopy4.mf6.block import Block
from flopy4.mf6.item import Item
from flopy4.mf6.package import Package
from flopy4.mf6.spec import field, path


@attrs.define(kw_only=True, slots=False)
class Obs(Package):
    dfn_name: ClassVar[str] = "utl-obs"

    multi_package: ClassVar[bool] = True

    @attrs.define
    class Continuous(Item):
        obsname: Union[float, str] = field()
        obstype: Union[float, str] = field()
        id_: Union[float, str] = field()
        id2: Optional[Union[float, str]] = field(default=None, optional=True)

    @attrs.define
    class Output(Item):
        obs_output_file_name: Path = path(converter=Path, direction="out")
        binary: Optional[str] = field(default=None, tagged=True, optional=True)

    @attrs.define(kw_only=True)
    class ContinuousBlock(Block):
        _header: ClassVar[str] = "output"
        output: "Obs.Output" = attrs.field()
        continuous: "list[Obs.Continuous]" = attrs.field(factory=list)

    digits: Optional[int] = field(
        default=None,
        block="options",
        optional=True,
    )
    print_input: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="print input to listing file",
    )
    continuous: Optional[list[ContinuousBlock]] = field(
        default=None,
        block="continuous",
    )


ObsContinuous = Obs.Continuous
ObsOutput = Obs.Output
