# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

import attrs

from flopy4.mf6._types import ArrayLike, _optional_path
from flopy4.mf6.package import Package
from flopy4.mf6.spec import field, path


@attrs.define(kw_only=True, slots=False)
class Spca(Package):
    multi_package: ClassVar[bool] = True

    readasarrays: bool = field(
        default=True,
        block="options",
        dfn_type="keyword",
    )
    print_input: bool = field(
        default=False,
        block="options",
        dfn_type="keyword",
        optional=True,
    )
    tas_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        dfn_type="record",
        optional=True,
        inout="filein",
    )
    concentration: Optional[ArrayLike] = field(
        default=None,
        block="period",
        reader="readarray",
        dfn_type="double",
        layered=False,
    )
    temperature: Optional[ArrayLike] = field(
        default=None,
        block="period",
        reader="readarray",
        dfn_type="double",
        layered=False,
    )
