# autogenerated file, do not modify
from typing import ClassVar, Optional

import attrs

from flopy4.mf6._types import FloatArrayLike, TimeArraySeriesRef
from flopy4.mf6.package import Package
from flopy4.mf6.spec import child, field
from flopy4.mf6.utl.tas import Tas


@attrs.define(kw_only=True, slots=False)
class Spca(Package):
    dfn_name: ClassVar[str] = "utl-spca"

    multi_package: ClassVar[bool] = True

    readasarrays: bool = field(
        default=True,
        block="options",
        longname="use array-based input",
    )
    print_input: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="print input to listing file",
    )
    tas: list[Tas] = child(
        block="options", keyword="tas6", direction="in", default=attrs.Factory(list)
    )
    concentration: Optional[dict[int, FloatArrayLike | TimeArraySeriesRef]] = field(
        default=None,
        block="period",
        shape=("ncpl",),
        layered=False,
        fill_forward=True,
        time_series=True,
    )
    temperature: Optional[dict[int, FloatArrayLike | TimeArraySeriesRef]] = field(
        default=None,
        block="period",
        shape=("ncpl",),
        layered=False,
        fill_forward=True,
        time_series=True,
    )
