# autogenerated file, do not modify
# ruff: noqa: E501
from pathlib import Path
from typing import ClassVar, Optional

import numpy as np
from attrs import Converter
from numpy.typing import NDArray
from xattree import xattree

from flopy4.mf6.converter import structure_array
from flopy4.mf6.package import Package
from flopy4.mf6.spec import array, field, path
from flopy4.utils import to_path


@xattree(kw_only=True)
class Spca(Package):
    multi_package: ClassVar[bool] = True

    readasarrays: bool = field(block="options", default=True, longname="use array-based input")
    print_input: bool = field(
        block="options", default=False, longname="print input to listing file"
    )
    tas_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="filein"
    )
    concentration: Optional[NDArray[np.float64]] = array(
        block="period",
        dims=("nper", "ncpl"),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="concentration",
    )
    temperature: Optional[NDArray[np.float64]] = array(
        block="period",
        dims=("nper", "ncpl"),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="temperature",
    )
