# autogenerated file, do not modify
from typing import ClassVar, Optional

from pydantic import Field
from pydantic.dataclasses import dataclass

from flopy4.mf6._types import FloatArrayLike
from flopy4.mf6.package import CFG, Package
from flopy4.mf6.record import Record
from flopy4.mf6.spec import field


@dataclass(config=CFG, kw_only=True)
class Tas(Package):
    dfn_name: ClassVar[str] = "utl-tas"

    multi_package: ClassVar[bool] = True

    @dataclass(config=CFG)
    class TimeSeriesName(Record):
        _keyword: ClassVar[str] = "name"
        time_series_name: list[str] = Field()

    @dataclass(config=CFG)
    class InterpolationMethod(Record):
        _keyword: ClassVar[str] = "method"
        interpolation_method: str = Field()

    @dataclass(config=CFG)
    class Sfac(Record):
        _keyword: ClassVar[str] = "sfac"
        sfacval: list[float] = Field()

    time_series_name: Optional[TimeSeriesName] = field(
        default=None,
        block="attributes",
    )
    interpolation_method: Optional[InterpolationMethod] = field(
        default=None,
        block="attributes",
    )
    sfac: Optional[Sfac] = field(
        default=None,
        block="attributes",
    )
    tas_array: Optional[dict[float, FloatArrayLike]] = field(
        default=None,
        block="time",
        shape=("ncpl",),
    )
