# autogenerated file, do not modify
# ruff: noqa: E501
from typing import ClassVar, Optional

import attrs
import numpy as np
from attrs import Converter
from numpy.typing import NDArray
from xattree import xattree

from flopy4.mf6.converter import structure_array
from flopy4.mf6.package import Package
from flopy4.mf6.spec import array, field


@xattree(kw_only=True)
class Tas(Package):
    multi_package: ClassVar[bool] = True

    @attrs.define
    class TimeSeriesName:
        _keyword: ClassVar[str] = "name"
        time_series_name: str = attrs.field()

    @attrs.define
    class InterpolationMethod:
        _keyword: ClassVar[str] = "method"
        interpolation_method: str = attrs.field()

    @attrs.define
    class Sfac:
        _keyword: ClassVar[str] = "sfac"
        sfacval: float = attrs.field()

    time_series_namerecord: Optional[TimeSeriesName] = field(block="attributes", default=None)
    interpolation_methodrecord: Optional[InterpolationMethod] = field(
        block="attributes", default=None
    )
    sfacrecord: Optional[Sfac] = field(block="attributes", default=None)
    tas_array: NDArray[np.float64] = array(
        block="time",
        dims=("unknown",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
    )
