# autogenerated file, do not modify
from typing import ClassVar, Optional

import attrs

from flopy4.mf6.item import Item
from flopy4.mf6.package import Package
from flopy4.mf6.record import Record
from flopy4.mf6.spec import field
from flopy4.mf6.utl.ts_methods import TsMethods


@attrs.define(kw_only=True, slots=False)
class Ts(TsMethods, Package):
    dfn_name: ClassVar[str] = "utl-ts"

    multi_package: ClassVar[bool] = True

    @attrs.define
    class TimeSeriesName(Record):
        _keyword: ClassVar[str] = "names"
        _aliases: ClassVar[tuple[str, ...]] = ("name",)
        time_series_names: list[str] = attrs.field()

    @attrs.define
    class InterpolationMethod(Record):
        _keyword: ClassVar[str] = "methods"
        interpolation_method: list[str] = attrs.field()

    @attrs.define
    class InterpolationMethodrecordSingle(Record):
        _keyword: ClassVar[str] = "method"
        interpolation_method_single: str = attrs.field()

    @attrs.define
    class Sfac(Record):
        _keyword: ClassVar[str] = "sfacs"
        sfacval: list[float] = attrs.field()

    @attrs.define
    class SfacrecordSingle(Record):
        _keyword: ClassVar[str] = "sfac"
        sfacval: float = attrs.field()

    @attrs.define
    class Timeseries(Item):
        ts_time: float = field()
        ts_array: tuple[float, ...] = field(array=True, shape=("time_series_names",))

    time_series_name: Optional[TimeSeriesName] = field(
        default=None,
        converter=lambda v: Ts.TimeSeriesName.convert(v),
        block="attributes",
    )
    interpolation_method: Optional[InterpolationMethod] = field(
        default=None,
        converter=lambda v: Ts.InterpolationMethod.convert(v),
        block="attributes",
    )
    interpolation_methodrecord_single: Optional[InterpolationMethodrecordSingle] = field(
        default=None,
        converter=lambda v: Ts.InterpolationMethodrecordSingle.convert(v),
        block="attributes",
    )
    sfac: Optional[Sfac] = field(
        default=None,
        converter=lambda v: Ts.Sfac.convert(v),
        block="attributes",
    )
    sfacrecord_single: Optional[SfacrecordSingle] = field(
        default=None,
        converter=lambda v: Ts.SfacrecordSingle.convert(v),
        block="attributes",
    )
    timeseries: Optional[list[Timeseries]] = field(
        default=None,
        block="timeseries",
        write_if_empty=True,
    )


TsTimeseries = Ts.Timeseries
