# autogenerated file, do not modify
from typing import ClassVar, Optional, Union

import attrs

from flopy4.mf6.item import Item
from flopy4.mf6.package import Package
from flopy4.mf6.spec import child, field
from flopy4.mf6.utl.ts import Ts


@attrs.define(kw_only=True, slots=False)
class Tvk(Package):
    dfn_name: ClassVar[str] = "utl-tvk"

    @attrs.define
    class K(Item):
        _keyword: ClassVar[str] = "k"
        cellid: tuple = field(cellid=True)
        k: Union[float, str] = field(time_series=True)

    @attrs.define
    class K22(Item):
        _keyword: ClassVar[str] = "k22"
        cellid: tuple = field(cellid=True)
        k22: Union[float, str] = field(time_series=True)

    @attrs.define
    class K33(Item):
        _keyword: ClassVar[str] = "k33"
        cellid: tuple = field(cellid=True)
        k33: Union[float, str] = field(time_series=True)

    _StressPeriodDataItem = K | K22 | K33

    print_input: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="print input to listing file",
    )
    ts: list[Ts] = child(
        block="options", keyword="ts6", direction="in", default=attrs.Factory(list)
    )
    _stress_period_data: Optional[dict[int, list[_StressPeriodDataItem]]] = field(
        alias="stress_period_data",
        default=None,
        repr=False,
        block="period",
        fill_forward=True,
    )


TvkK = Tvk.K
TvkK22 = Tvk.K22
TvkK33 = Tvk.K33
