# autogenerated file, do not modify
from typing import ClassVar, Optional, Union

import attrs

from flopy4.mf6.item import Item
from flopy4.mf6.package import Package
from flopy4.mf6.spec import child, field
from flopy4.mf6.utl.ts import Ts


@attrs.define(kw_only=True, slots=False)
class Tvs(Package):
    dfn_name: ClassVar[str] = "utl-tvs"

    @attrs.define
    class Ss(Item):
        _keyword: ClassVar[str] = "ss"
        cellid: tuple = field(cellid=True)
        ss: Union[float, str] = field(time_series=True)

    @attrs.define
    class Sy(Item):
        _keyword: ClassVar[str] = "sy"
        cellid: tuple = field(cellid=True)
        sy: Union[float, str] = field(time_series=True)

    _StressPeriodDataItem = Ss | Sy

    disable_storage_change_integration: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="deactivate storage change integration",
    )
    print_input: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="print input to listing file",
    )
    ts: list[Ts] = child(
        block="options", keyword="ts6", direction="in", default=attrs.Factory(list)
    )
    _stress_period_data: Optional[dict[int, list[_StressPeriodDataItem]]] = field(
        alias="stress_period_data",
        default=None,
        repr=False,
        block="period",
        fill_forward=True,
    )


TvsSs = Tvs.Ss
TvsSy = Tvs.Sy
