start: readarray
readarray: (single_array | layered_array)
single_array: [netcdf] array
layered_array: layered [netcdf] array+
layered: "layered"i
netcdf: "netcdf"i
array: control [data]
control: constant | internal | external
constant: "constant"i _number
internal: "internal"i [factor] [iprn]
external: "open/close"i filename [factor] [binary] [iprn]
factor: "factor"i _number
iprn: "iprn"i _signed_integer
binary: "(" "binary"i ")"
filename: ESCAPED_STRING | _word
data: _number+
_number: SIGNED_NUMBER | NUMBER
_signed_integer: SIGNED_INT | INT
_word: /[a-zA-Z0-9._'~,-\\(\\)]+/

%import common.NEWLINE -> _NL
%import common.WS
%import common.WS_INLINE
%import common.CNAME
%import common.WORD
%import common.NUMBER
%import common.INT
%import common.SH_COMMENT
%import common.ESCAPED_STRING
%import common.SIGNED_NUMBER
%import common.SIGNED_INT

%ignore WS
%ignore SH_COMMENT
