start: [WS] [_NL*] (block [[WS] _NL*])+ [WS]
block: "begin"i block_name _NL _list "end"i block_name _NL+
block_name: CNAME [INT]
_list: line*
line: [WS] item+ _NL+
item: word | NUMBER
word: /[a-zA-Z0-9._'~,-\\(\\)]+/

%import common.NEWLINE -> _NL
%import common.WS
%import common.WS_INLINE
%import common.CNAME
%import common.WORD
%import common.NUMBER
%import common.INT
%import common.SH_COMMENT
%import common._STRING_INNER

%ignore WS_INLINE
%ignore SH_COMMENT
