integer: SIGNED_INT | INT
double: SIGNED_NUMBER | NUMBER
number: SIGNED_NUMBER | NUMBER
string: ESCAPED_STRING | (_token+ NEWLINE)
array: (single_array | layered_array)
single_array: [netcdf] readarray
layered_array: layered [netcdf] readarray+
layered: "layered"i
netcdf: "netcdf"i
readarray: control [data]
control: constant | internal | external
constant: "constant"i double
internal: "internal"i [factor] [iprn]
external: "open/close"i filename [factor] [binary] [iprn]
factor: "factor"i double
iprn: "iprn"i integer
binary: "(binary)"i
filename: ESCAPED_STRING | word
data: double+
record: token+ NEWLINE
token: number | word
word: /(?!(?i:begin|end))[a-zA-Z0-9._'~,+-\\(\\)]+/
_token: word | number

%import common.NEWLINE
%import common.WS
%import common.WS_INLINE
%import common.CNAME
%import common.WORD
%import common.NUMBER
%import common.INT
%import common.SH_COMMENT
%import common.ESCAPED_STRING
%import common.SIGNED_NUMBER
%import common.SIGNED_INT

%ignore WS
%ignore SH_COMMENT
