integer: SIGNED_INT | INT
double: SIGNED_NUMBER | NUMBER
number: SIGNED_NUMBER | NUMBER
string: (ESCAPED_STRING | _token+) _NL
array: (single_array | layered_array)
single_array: [netcdf] readarray
layered_array: layered [netcdf] readarray+
layered: "layered"i [_remark] _NL
netcdf: "netcdf"i
readarray: control [data]
control: constant | internal | external
constant: "constant"i double [_remark] _NL
internal: "internal"i [factor] [iprn] [_remark] _NL
external: "open/close"i filename [factor] [binary] [iprn] [_remark] _NL
factor: "factor"i double
iprn: "iprn"i integer
binary: "(binary)"i
filename: ESCAPED_STRING | word
data: _data_line+
_data_line: double+ [_remark] _NL
record: token+ _NL
token: number | word
word: /(?!(?i:begin|end))[a-zA-Z0-9'().\/:;<=>?@_~+\[\\-]+/
_token: word | number
_REMARK: /\S+/
_remark: _REMARK+

%import common.NEWLINE -> _NL
%import common.WS_INLINE
%import common.CNAME
%import common.WORD
%import common.NUMBER
%import common.INT
%import common.SH_COMMENT
%import common.ESCAPED_STRING
%import common.SIGNED_NUMBER
%import common.SIGNED_INT

COMMA: ","
%ignore WS_INLINE
%ignore SH_COMMENT
%ignore COMMA
