import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

import flopy4.mf6
from flopy4 import cli
from flopy4.mf6 import _sync
from flopy4.mf6._sync import (
    SyncError,
    SyncResult,
    _local_commit,
    _remote_commit,
    _resolve_release_id,
    find_orphans,
    sync,
)

_HEADER = "# autogenerated file, do not modify\n"


def _read_contract(outdir: Path) -> dict:
    ns: dict = {}
    exec((outdir / "_contract.py").read_text(), ns)
    return ns


def test_exported():
    assert flopy4.mf6.sync is sync
    assert flopy4.mf6.SyncResult is SyncResult
    assert flopy4.mf6.SyncError is SyncError


def test_sync_local_all_packages(dfn_path, tmp_path):
    """A local sync generates every component and writes the contract."""
    result = sync(dfn_path, mf6_version="6.9.0", all_packages=True, outdir=tmp_path)
    assert result.version == "6.9.0"
    assert result.source == str(dfn_path)
    assert result.outdir == tmp_path.resolve()
    assert result.files
    assert all(f.is_file() and f.is_relative_to(result.outdir) for f in result.files)
    contract = _read_contract(tmp_path)
    assert contract["MF6_VERSION"] == "6.9.0"
    assert contract["DFN_SCHEMA_VERSION"]


def test_sync_local_existing_only(dfn_path, tmp_path):
    """Without all_packages, an empty outdir gets only the contract."""
    result = sync(dfn_path, mf6_version="6.9.0", outdir=tmp_path)
    assert result.files == ()
    assert sorted(p.name for p in tmp_path.iterdir()) == ["_contract.py", "dfns"]


def test_sync_local_unknown_version_warns(dfn_path, tmp_path):
    """DFNs outside a modflow6 checkout have no version.txt to read."""
    local = tmp_path / "dfn"
    local.mkdir()
    for f in dfn_path.glob("*.dfn"):
        (local / f.name).write_text(f.read_text())
    with pytest.warns(UserWarning, match="MF6 version is unknown"):
        result = sync(local, outdir=tmp_path / "out")
    assert result.version == "unknown"


def test_sync_missing_dir(tmp_path):
    with pytest.raises(FileNotFoundError):
        sync(tmp_path / "nope", outdir=tmp_path)
    with pytest.raises(FileNotFoundError):
        sync("./nope/dfn", outdir=tmp_path)


def test_sync_bad_release_id(tmp_path):
    with pytest.raises(ValueError, match="owner/repo@ref"):
        sync("modflow6@develop", outdir=tmp_path)


def test_sync_exe_not_supported(tmp_path):
    with pytest.raises(NotImplementedError, match="--spec"):
        sync(exe="mf6", outdir=tmp_path)
    with pytest.raises(ValueError, match="not both"):
        sync("develop", exe="mf6", outdir=tmp_path)


def test_resolve_release_id():
    assert _resolve_release_id("6.6.0") == "MODFLOW-ORG/modflow6@6.6.0"
    assert _resolve_release_id("me/modflow6@develop") == "me/modflow6@develop"


@pytest.fixture(scope="module")
def synced(dfn_path, tmp_path_factory):
    """A directory with every component generated, to copy per test."""
    outdir = tmp_path_factory.mktemp("synced")
    sync(dfn_path, mf6_version="6.9.0", all_packages=True, outdir=outdir)
    return outdir


@pytest.fixture
def outdir(synced, tmp_path):
    return Path(shutil.copytree(synced, tmp_path / "mf6"))


def _snapshot(outdir: Path) -> dict[str, str]:
    return {p.relative_to(outdir).as_posix(): p.read_text() for p in outdir.rglob("*.py")}


def test_contract_lists_files(outdir):
    listed = set(_read_contract(outdir)["GENERATED_FILES"])
    assert listed == set(_snapshot(outdir)) - {"_contract.py"}
    assert not [p for p in outdir.iterdir() if p.name.startswith(".sync-")]


def test_resync_is_stable(dfn_path, outdir):
    before = _snapshot(outdir)
    result = sync(dfn_path, mf6_version="6.9.0", outdir=outdir)
    assert result.kept == result.removed == ()
    assert _snapshot(outdir) == before


def test_orphan_removed(dfn_path, outdir):
    """A generated module the contract doesn't list, with no DFN, goes."""
    orphan = outdir / "gwf" / "zzz.py"
    orphan.write_text(_HEADER)
    assert find_orphans(outdir) == [orphan]
    result = sync(dfn_path, mf6_version="6.9.0", outdir=outdir)
    assert result.removed == (orphan,)
    assert not orphan.exists()
    assert find_orphans(outdir) == []


def test_listed_without_dfn_kept(dfn_path, outdir):
    """A listed module with no DFN stays: other modules may import it."""
    stale = outdir / "gwf" / "zzz.py"
    stale.write_text(_HEADER)
    contract = outdir / "_contract.py"
    contract.write_text(contract.read_text().replace("(\n", '(\n    "gwf/zzz.py",\n', 1))
    with pytest.warns(UserWarning, match="gwf/zzz.py"):
        result = sync(dfn_path, mf6_version="6.9.0", outdir=outdir)
    assert result.kept == (stale,)
    assert stale.exists()
    assert "gwf/zzz.py" in _read_contract(outdir)["GENERATED_FILES"]


def test_no_file_list_keeps_everything(dfn_path, outdir):
    """A contract from before sync tracked files: nothing is removed."""
    stale = outdir / "gwf" / "zzz.py"
    stale.write_text(_HEADER)
    (outdir / "_contract.py").write_text(_HEADER + 'MF6_VERSION = "develop"\n')
    assert find_orphans(outdir) == []
    with pytest.warns(UserWarning, match="gwf/zzz.py"):
        result = sync(dfn_path, mf6_version="6.9.0", outdir=outdir)
    assert result.kept == (stale,)
    assert result.removed == ()
    assert stale.exists()


def test_failed_swap_rolls_back(dfn_path, outdir, monkeypatch):
    """A failure partway through the swap restores every file."""
    (outdir / "gwf" / "zzz.py").write_text(_HEADER)
    (outdir / "gwf" / "chd.py").write_text(_HEADER + "# edited\n")
    before = _snapshot(outdir)
    replace = os.replace
    calls = 0

    def flaky_replace(src, dst):
        nonlocal calls
        calls += 1
        if calls == 50:
            raise OSError("disk full")
        replace(src, dst)

    monkeypatch.setattr(_sync.os, "replace", flaky_replace)
    with pytest.raises(OSError, match="disk full"):
        sync(dfn_path, mf6_version="7.0.0", outdir=outdir)
    assert _snapshot(outdir) == before
    assert not [p for p in outdir.iterdir() if p.name.startswith(".sync-")]


def test_invalid_python_leaves_outdir(dfn_path, outdir, monkeypatch):
    before = _snapshot(outdir)

    def bad_make_module(spec, env, verbose=False, outpath=None):
        outpath.write_text(_HEADER + "def (\n")

    # flopy4.mf6.utils.codegen.make is shadowed by the make() function.
    make = sys.modules["flopy4.mf6.utils.codegen.make"]
    monkeypatch.setattr(make, "make_module", bad_make_module)
    with pytest.raises(SyncError, match="invalid Python"):
        sync(dfn_path, mf6_version="7.0.0", outdir=outdir)
    assert _snapshot(outdir) == before


@pytest.mark.skipif(sys.platform == "win32" or os.geteuid() == 0, reason="needs POSIX permissions")
def test_read_only(dfn_path, tmp_path):
    outdir = tmp_path / "ro"
    outdir.mkdir()
    outdir.chmod(0o555)
    try:
        with pytest.raises(SyncError, match="read-only"):
            sync(dfn_path, mf6_version="6.9.0", outdir=outdir)
    finally:
        outdir.chmod(0o755)


def test_dfns_stored(dfn_path, outdir):
    """Sync stores the source's DFNs, replacing ones it no longer has."""
    stored = outdir / "dfns"
    assert {f.name for f in stored.iterdir()} == {
        f.name for f in dfn_path.iterdir() if f.is_file() and not f.name.startswith(".")
    }
    (stored / "gwf-zzz.dfn").write_text("")
    sync(dfn_path, mf6_version="6.9.0", outdir=outdir)
    assert not (stored / "gwf-zzz.dfn").exists()


def test_reader_uses_stored_dfns():
    """The typed reader's default DFNs are the ones stored in the package."""
    from flopy4.mf6.codec.reader.dfns import get_component_dfn

    assert (Path(flopy4.mf6.__file__).parent / "dfns" / "gwf-chd.dfn").is_file()
    assert get_component_dfn("gwf-chd").name == "gwf-chd"


def test_contract_records_commit(dfn_path, outdir, monkeypatch):
    monkeypatch.setattr(_sync, "_local_commit", lambda path: "abc1234")
    result = sync(dfn_path, mf6_version="6.9.0", outdir=outdir)
    assert result.commit == "abc1234"
    assert _read_contract(outdir)["DFN_COMMIT"] == "abc1234"
    monkeypatch.setattr(_sync, "_local_commit", lambda path: None)
    sync(dfn_path, mf6_version="6.9.0", outdir=outdir)
    assert _read_contract(outdir)["DFN_COMMIT"] is None


@pytest.mark.skipif(shutil.which("git") is None, reason="needs git")
def test_local_commit(tmp_path):
    assert _local_commit(tmp_path) is None
    repo = tmp_path / "repo"
    (repo / "dfn").mkdir(parents=True)
    (repo / "dfn" / "a.dfn").write_text("")

    def git(*args):
        return subprocess.check_output(["git", "-C", str(repo), *args], text=True).strip()

    git("init", "-q")
    git("add", ".")
    git("-c", "user.name=t", "-c", "user.email=t@t", "commit", "-qm", "init")
    sha = git("rev-parse", "HEAD")
    assert _local_commit(repo / "dfn") == sha
    (repo / "dfn" / "a.dfn").write_text("changed")
    assert _local_commit(repo / "dfn") == f"{sha}-dirty"


def test_remote_commit(monkeypatch):
    requests = []

    class Response:
        def __enter__(self):
            return self

        def __exit__(self, *args):
            pass

        def read(self):
            return b"abc1234def\n"

    def urlopen(request, timeout):
        requests.append(request)
        return Response()

    monkeypatch.setattr(_sync.urllib.request, "urlopen", urlopen)
    monkeypatch.setenv("GITHUB_TOKEN", "t0ken")
    assert _remote_commit("MODFLOW-ORG/modflow6@develop") == "abc1234def"
    assert (
        requests[0].full_url == "https://api.github.com/repos/MODFLOW-ORG/modflow6/commits/develop"
    )
    assert requests[0].get_header("Authorization") == "Bearer t0ken"

    def fail(request, timeout):
        raise OSError("offline")

    monkeypatch.setattr(_sync.urllib.request, "urlopen", fail)
    with pytest.warns(UserWarning, match="offline"):
        assert _remote_commit("MODFLOW-ORG/modflow6@develop") is None


@pytest.mark.skipif(not os.environ.get("FLOPY4_RELEASE"), reason="release builds only")
def test_release_contract_names_tag():
    """A release must ship classes synced to a tagged MF6 release."""
    from flopy4.mf6 import _contract

    assert re.fullmatch(r"\d+\.\d+\.\d+", _contract.MF6_VERSION), _contract.MF6_VERSION
    assert _contract.DFN_COMMIT and not _contract.DFN_COMMIT.endswith("-dirty")


def test_cli_wraps_sync(monkeypatch, tmp_path, capsys):
    """The CLI passes its arguments through to sync()."""
    calls = []

    def fake_sync(source, **kwargs):
        calls.append((source, kwargs))
        return SyncResult(
            version="6.6.0", commit=None, source="x", outdir=tmp_path, files=(tmp_path,)
        )

    monkeypatch.setattr("flopy4.mf6._sync.sync", fake_sync)
    monkeypatch.setattr(
        sys, "argv", ["flopy4", "mf6", "sync", "6.6.0", "--all-packages", "--force"]
    )
    cli.main()
    assert calls == [
        (
            "6.6.0",
            {"mf6_version": None, "all_packages": True, "force": True, "verbose": False},
        )
    ]
    out = capsys.readouterr().out
    assert "Generated 1 component modules" in out
    assert "MF6 version: 6.6.0" in out
