# autogenerated file, do not modify
from typing import ClassVar, Optional

import attrs
import numpy as np
from numpy.typing import NDArray

from flopy4.mf6._types import ARRAY_EQ, to_str_array
from flopy4.mf6.exchange import Exchange
from flopy4.mf6.gwt.mvt import Mvt
from flopy4.mf6.item import Item
from flopy4.mf6.spec import child, field
from flopy4.mf6.utl.obs import Obs


@attrs.define(kw_only=True, slots=False)
class Gwtgwt(Exchange):
    dfn_name: ClassVar[str] = "exg-gwtgwt"

    multi_package: ClassVar[bool] = True

    observations: ClassVar[dict[str, tuple[tuple[str, ...], ...]]] = {
        "flow-ja-face": (("index",), ("string",)),
    }

    @attrs.define
    class Exchangedata(Item):
        cellidm1: tuple = field(cellid="1")
        cellidm2: tuple = field(cellid="2")
        ihc: int = field()
        cl1: float = field()
        cl2: float = field()
        hwva: float = field()
        aux: tuple[float, ...] = field(default=(), array=True, shape=("auxiliary",), optional=True)
        boundname: Optional[str] = field(default=None, optional=True)

    gwfmodelname1: str = field(
        default=None,
        block="options",
        longname="keyword to specify name of first corresponding GWF Model",
    )
    gwfmodelname2: str = field(
        default=None,
        block="options",
        longname="keyword to specify name of second corresponding GWF Model",
    )
    auxiliary: Optional[NDArray[np.str_]] = field(
        default=None,
        converter=to_str_array,
        eq=ARRAY_EQ,
        block="options",
        optional=True,
        longname="keyword to specify aux variables",
    )
    boundnames: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    print_input: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="keyword to print input to list file",
    )
    print_flows: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="keyword to print gwfgwf flows to list file",
    )
    save_flows: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="keyword to save GWFGWF flows",
    )
    adv_scheme: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
        longname="advective scheme",
    )
    dsp_xt3d_off: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="deactivate xt3d",
    )
    dsp_xt3d_rhs: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="xt3d on right-hand side",
    )
    mvt: Optional[Mvt] = child(block="options", keyword="mvt6", direction="in")
    obs: Optional[Obs] = child(block="options", keyword="obs6", direction="in")
    nexg: Optional[int] = field(
        default=None,
        block="dimensions",
        longname="number of exchanges",
    )
    exchangedata: Optional[list[Exchangedata]] = field(
        default=None,
        block="exchangedata",
        dim="nexg",
    )


GwtgwtExchangedata = Gwtgwt.Exchangedata
