"""Sync the generated ``flopy4.mf6`` classes to an MF6 version."""

import shutil
import warnings
from dataclasses import dataclass
from os import PathLike
from pathlib import Path

_MF6_ROOT = Path(__file__).parent
_DFN_SCHEMA_VERSION = "2.0.0.dev3"
_DEFAULT_REPO = "MODFLOW-ORG/modflow6"


@dataclass(frozen=True)
class SyncResult:
    """The outcome of a :func:`sync`.

    Attributes
    ----------
    version :
        The MF6 version recorded in ``_contract.py``, or ``"unknown"``.
    source :
        Where the DFNs came from: an ``owner/repo@ref`` release ID or a
        local directory.
    outdir :
        The directory the classes and contract were written to.
    files :
        The generated module files.
    """

    version: str
    source: str
    outdir: Path
    files: tuple[Path, ...]


def _resolve_release_id(release_id: str | None, verbose: bool = False) -> str:
    """Resolve a release_id, falling back to the discovered binary's version
    or the latest release if no release_id is given.
    """
    if release_id is not None:
        if "@" not in release_id:
            return f"{_DEFAULT_REPO}@{release_id}"
        return release_id

    # Try to read the version from a binary on PATH.
    from flopy4.mf6._compat import _query_mf6_version

    for name in ("mf6", "mf6.exe"):
        exe = shutil.which(name)
        if exe:
            version = _query_mf6_version(exe)
            if version:
                if verbose:
                    print(f"Detected MF6 {version} at {exe}")
                return f"{_DEFAULT_REPO}@{version}"

    # Fall back to @latest.
    if verbose:
        print("No MF6 binary found on PATH; resolving to latest release.")
    return f"{_DEFAULT_REPO}@latest"


def _local_mf6_version(path: Path) -> str:
    """The MF6 version of DFNs read from a local directory: the version.txt
    of the modflow6 checkout the DFNs are in (they live at
    doc/mf6io/mf6ivar/dfn), else "unknown".
    """
    if "modflow6" in path.parts and len(path.parents) > 3:
        version_file = path.parents[3] / "version.txt"
        if version_file.is_file():
            return version_file.read_text().strip()
    return "unknown"


def _populate_remote_cache(registry, release_id: str, force: bool = False) -> None:
    """Populate the registry's DFN cache.

    Tries ``registry.sync()`` first (requires a ``dfns.zip`` release asset).
    Falls back to fetching DFNs from the repository tree when that asset is
    not yet available — writes directly into the registry's cache path so
    ``registry.spec()`` finds the files in the expected location.

    Parameters
    ----------
    force :
        Re-fetch even if the cache already exists. Should be True for
        branch refs (mutable) and False for pinned release tags.
    """
    if not force and registry.cache_path.exists() and any(registry.cache_path.iterdir()):
        return
    try:
        registry.sync()
    except Exception:
        # dfns.zip not yet a release asset; fetch from the git tree instead.
        from modflow_devtools.dfns import fetch_dfns

        owner_repo, tag = release_id.split("@", 1)
        owner, repo = owner_repo.split("/")
        registry.cache_path.mkdir(parents=True, exist_ok=True)
        fetch_dfns(owner=owner, repo=repo, ref=tag, outdir=registry.cache_path)


def _write_contract(outdir: Path, mf6_version: str) -> None:
    (outdir / "_contract.py").write_text(
        "# autogenerated file, do not modify\n"
        f'MF6_VERSION = "{mf6_version}"\n'
        f'DFN_SCHEMA_VERSION = "{_DFN_SCHEMA_VERSION}"\n'
    )


def sync(
    source: str | PathLike | None = None,
    *,
    exe: str | PathLike | None = None,
    mf6_version: str | None = None,
    all_packages: bool = False,
    force: bool = False,
    outdir: str | PathLike | None = None,
    verbose: bool = False,
) -> SyncResult:
    """Regenerate the ``flopy4.mf6`` classes for an MF6 version.

    Fetches or reads the DFNs, regenerates the component classes, and
    records the MF6 version in ``_contract.py``. Does not install an MF6
    binary.

    Parameters
    ----------
    source :
        Where to get the DFNs: a release ID (``owner/repo@ref``), a bare
        ref (``6.6.0``, ``develop``; the repo defaults to
        ``MODFLOW-ORG/modflow6``), or a local DFN directory. If omitted,
        uses the version of the ``mf6`` binary on PATH, else the latest
        release.
    exe :
        An MF6 executable to read the DFNs from (``mf6 --spec``). Not
        supported yet. Mutually exclusive with ``source``.
    mf6_version :
        The MF6 version to record, overriding the one inferred from the
        source.
    all_packages :
        Generate every component, including ones with no module yet. By
        default only existing modules are regenerated.
    force :
        Re-fetch remote DFNs even if they are cached. Branch refs are
        always re-fetched.
    outdir :
        Where to write the classes and contract. Defaults to the installed
        ``flopy4.mf6`` package.
    verbose :
        Print progress.

    Returns
    -------
    SyncResult
    """
    if exe is not None:
        if source is not None:
            raise ValueError("Pass either source or exe, not both.")
        raise NotImplementedError(
            "Syncing from an MF6 executable needs `mf6 --spec`, which MF6 doesn't support yet."
        )

    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", message=".*modflow_devtools.dfns.*experimental.*")
        from modflow_devtools.dfns import LocalDfnRegistry, RemoteDfnRegistry

    from flopy4.mf6.utils.codegen.make import make_modules

    outdir = Path(outdir).expanduser().resolve() if outdir is not None else _MF6_ROOT

    path = Path(source).expanduser() if source is not None else None
    if path is not None and not path.is_dir():
        # A path-like source without a ref (a Path, or a string with a
        # separator but no "@") is a local directory that doesn't exist,
        # not a release ID.
        if isinstance(source, PathLike) or ("/" in str(source) and "@" not in str(source)):
            raise FileNotFoundError(f"DFN directory not found: {path}")
    if path is not None and path.is_dir():
        if verbose:
            print(f"Generating flopy4.mf6 from local DFNs: {path}")
        registry = LocalDfnRegistry(path=path)
        source = str(path)
        version = mf6_version or _local_mf6_version(path)
    else:
        release_id = _resolve_release_id(
            str(source) if source is not None else None, verbose=verbose
        )
        if verbose:
            print(f"Generating flopy4.mf6 from remote release: {release_id}")
        if "/" not in release_id.split("@")[0]:
            raise ValueError(
                f"source must be 'owner/repo@ref', a ref, or a local directory; got: {release_id!r}"
            )
        registry = RemoteDfnRegistry(release_id=release_id)
        source = release_id
        version = mf6_version or registry.latest_tag() or "unknown"
        # Branch refs are mutable: always re-fetch unless the version is a
        # pinned semver tag (first char is a digit).
        is_branch = not version[0].isdigit()
        _populate_remote_cache(registry, release_id, force=force or is_branch)

    if version == "unknown":
        warnings.warn(
            f"MF6 version is unknown for DFNs from '{source}'. "
            "Pass mf6_version to record it explicitly in _contract.py.",
            stacklevel=2,
        )

    from flopy4.mf6.utils.codegen.dfn2py import _SKIP, check_mixins

    dfns = registry.spec(schema_version=_DFN_SCHEMA_VERSION).components
    check_mixins(dfns)
    outdir.mkdir(parents=True, exist_ok=True)
    specs = make_modules(
        dfns=dfns,
        outdir=outdir,
        skip=_SKIP,
        makedirs=all_packages,
        existing_only=not all_packages,
        verbose=verbose,
    )
    _write_contract(outdir, version)

    return SyncResult(
        version=version,
        source=str(source),
        outdir=outdir,
        files=tuple(spec.outpath for spec in specs),
    )
