# autogenerated file, do not modify
from typing import ClassVar

from pydantic.dataclasses import dataclass

from flopy4.mf6.solution import CFG, Solution


@dataclass(config=CFG, kw_only=True)
class Ems(Solution):
    dfn_name: ClassVar[str] = "sln-ems"

    slntype: ClassVar[str] = "ems"
