# autogenerated file, do not modify
# ruff: noqa: E501
from typing import ClassVar

from xattree import xattree

from flopy4.mf6.solution import Solution


@xattree(kw_only=True)
class Ems(Solution):
    slntype: ClassVar[str] = "ems"
