# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

import attrs

from flopy4.mf6._types import _optional_path
from flopy4.mf6.record import Record
from flopy4.mf6.solution import Solution
from flopy4.mf6.spec import field, path


@attrs.define(kw_only=True, slots=False)
class Ims(Solution):
    slntype: ClassVar[str] = "ims"

    @attrs.define
    class NoPtc(Record):
        _keyword: ClassVar[str] = "no_ptc"
        no_ptc_option: Optional[str] = attrs.field(default=None)

    @attrs.define
    class Rclose(Record):
        _keyword: ClassVar[str] = ""
        inner_rclose: float = attrs.field(metadata={"tagged": True})
        rclose_option: Optional[str] = attrs.field(default=None)

    print_option: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
    )
    complexity: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
    )
    csv_output_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        inout="fileout",
    )
    csv_outer_output_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        inout="fileout",
    )
    csv_inner_output_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        inout="fileout",
    )
    no_ptc: Optional[NoPtc] = field(
        default=None,
        block="options",
    )
    ats_outer_maximum_fraction: Optional[float] = field(
        default=None,
        block="options",
        optional=True,
    )
    outer_hclose: Optional[float] = field(
        default=None,
        block="nonlinear",
        optional=True,
    )
    outer_dvclose: float = field(
        default=None,
        block="nonlinear",
    )
    outer_rclosebnd: Optional[float] = field(
        default=None,
        block="nonlinear",
        optional=True,
    )
    outer_maximum: int = field(
        default=None,
        block="nonlinear",
    )
    under_relaxation: Optional[str] = field(
        default=None,
        block="nonlinear",
        optional=True,
    )
    under_relaxation_gamma: Optional[float] = field(
        default=None,
        block="nonlinear",
        optional=True,
    )
    under_relaxation_theta: Optional[float] = field(
        default=None,
        block="nonlinear",
        optional=True,
    )
    under_relaxation_kappa: Optional[float] = field(
        default=None,
        block="nonlinear",
        optional=True,
    )
    under_relaxation_momentum: Optional[float] = field(
        default=None,
        block="nonlinear",
        optional=True,
    )
    backtracking_number: Optional[int] = field(
        default=None,
        block="nonlinear",
        optional=True,
    )
    backtracking_tolerance: Optional[float] = field(
        default=None,
        block="nonlinear",
        optional=True,
    )
    backtracking_reduction_factor: Optional[float] = field(
        default=None,
        block="nonlinear",
        optional=True,
    )
    backtracking_residual_limit: Optional[float] = field(
        default=None,
        block="nonlinear",
        optional=True,
    )
    inner_maximum: int = field(
        default=None,
        block="linear",
    )
    inner_hclose: Optional[float] = field(
        default=None,
        block="linear",
        optional=True,
    )
    inner_dvclose: float = field(
        default=None,
        block="linear",
    )
    rclose: Optional[Rclose] = field(
        default=None,
        block="linear",
    )
    linear_acceleration: str = field(
        default=None,
        block="linear",
    )
    relaxation_factor: Optional[float] = field(
        default=None,
        block="linear",
        optional=True,
    )
    preconditioner_levels: Optional[int] = field(
        default=None,
        block="linear",
        optional=True,
    )
    preconditioner_drop_tolerance: Optional[float] = field(
        default=None,
        block="linear",
        optional=True,
    )
    number_orthogonalizations: Optional[int] = field(
        default=None,
        block="linear",
        optional=True,
    )
    scaling_method: Optional[str] = field(
        default=None,
        block="linear",
        optional=True,
    )
    reordering_method: Optional[str] = field(
        default=None,
        block="linear",
        optional=True,
    )
