# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

import attrs

from flopy4.mf6._types import _optional_path
from flopy4.mf6.record import Record
from flopy4.mf6.solution import Solution


@attrs.define(kw_only=True, slots=False)
class Pts(Solution):
    slntype: ClassVar[str] = "pts"

    @attrs.define
    class NoPtc(Record):
        _keyword: ClassVar[str] = "no_ptc"
        no_ptc_option: Optional[str] = attrs.field(default=None)

    print_option: Optional[str] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "options",
            "dfn_type": "string",
            "optional": True,
        },
    )
    complexity: Optional[str] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "options",
            "dfn_type": "string",
            "optional": True,
        },
    )
    csv_output_file: Optional[Path] = attrs.field(
        default=None,
        converter=_optional_path,
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "fileout",
        },
    )
    csv_outer_output_file: Optional[Path] = attrs.field(
        default=None,
        converter=_optional_path,
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "fileout",
        },
    )
    csv_inner_output_file: Optional[Path] = attrs.field(
        default=None,
        converter=_optional_path,
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "fileout",
        },
    )
    no_ptc: Optional[NoPtc] = attrs.field(default=None, metadata={"dfn_block": "options"})
    ats_outer_maximum_fraction: Optional[float] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "options",
            "dfn_type": "double",
            "optional": True,
        },
    )
    outer_maximum: int = attrs.field(
        default=None,
        metadata={
            "dfn_block": "nonlinear",
            "dfn_type": "integer",
        },
    )
