# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

from pydantic import Field
from pydantic.dataclasses import dataclass

from flopy4.mf6._types import _optional_path
from flopy4.mf6.record import Record
from flopy4.mf6.solution import CFG, Solution
from flopy4.mf6.spec import field, path


@dataclass(config=CFG, kw_only=True)
class Pts(Solution):
    dfn_name: ClassVar[str] = "sln-pts"

    slntype: ClassVar[str] = "pts"

    @dataclass(config=CFG)
    class NoPtc(Record):
        _keyword: ClassVar[str] = "no_ptc"
        no_ptc_option: Optional[str] = Field(default=None)

    print_option: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
        longname="print option",
    )
    complexity: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
        longname="print option",
    )
    csv_output_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="out",
    )
    csv_outer_output_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="out",
    )
    csv_inner_output_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="out",
    )
    no_ptc: Optional[NoPtc] = field(
        default=None,
        block="options",
    )
    ats_outer_maximum_fraction: Optional[float] = field(
        default=None,
        block="options",
        optional=True,
        longname="fraction of outer maximum used with ats",
    )
    outer_maximum: int = field(
        default=None,
        block="nonlinear",
        longname="outer maximum iterations",
    )
