# autogenerated file, do not modify
from typing import ClassVar, Optional

import attrs

from flopy4.mf6.context import Context
from flopy4.mf6.exchange import Exchange
from flopy4.mf6.model import Model
from flopy4.mf6.simulation_methods import SimulationMethods
from flopy4.mf6.solution import Solution
from flopy4.mf6.spec import child, field
from flopy4.mf6.tdis import Tdis
from flopy4.mf6.utl.hpc import Hpc


@attrs.define(kw_only=True, slots=False)
class Simulation(SimulationMethods, Context):
    dfn_name: ClassVar[str] = "sim-nam"

    continue_: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="continue if not converged",
    )
    nocheck: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="turn off checking",
    )
    memory_print_option: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
        longname="memory print option",
    )
    profile_option: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
        longname="profiling option",
    )
    maxerrors: Optional[int] = field(
        default=None,
        block="options",
        optional=True,
        longname="maximum number of errors",
    )
    print_input: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="print input to listing file",
    )
    hpc: Optional[Hpc] = child(block="options", keyword="hpc6", direction="in")
    tdis: Tdis = child(block="timing", keyword="tdis6", default=attrs.Factory(Tdis))
    models: dict[str, Model] = child(block="models", default=attrs.Factory(dict))
    exchanges: dict[str, Exchange] = child(block="exchanges", default=attrs.Factory(dict))
    mxiter: Optional[int] = field(
        default=None,
        block="solutiongroup",
        optional=True,
        longname="maximum solution group iterations",
    )
    solutiongroup: dict[str, Solution] = child(block="solutiongroup", default=attrs.Factory(dict))
