# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

import attrs

from flopy4.mf6._types import _optional_path
from flopy4.mf6.item import Item
from flopy4.mf6.spec import field, path
from flopy4.mf6.tdis_base import TdisBase


@attrs.define(kw_only=True, slots=False)
class Tdis(TdisBase):
    dfn_name: ClassVar[str] = "sim-tdis"

    @attrs.define
    class Perioddata(Item):
        perlen: float = field()
        nstp: int = field()
        tsmult: float = field()

    time_units: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
        longname="time unit",
    )
    start_date_time: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
        longname="starting date and time",
    )
    ats_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="in",
        keyword="ats6",
    )
    nper: Optional[int] = field(
        default=1,
        block="dimensions",
        longname="number of stress periods",
    )
    perioddata: Optional[list[Perioddata]] = field(
        default=None,
        block="perioddata",
        auto_from="perioddata",
    )


TdisPerioddata = Tdis.Perioddata
