title: flopy4 / pyphoenix
author: MODFLOW Development Team
logo: ""

execute:
  execute_notebooks: "off"

html:
  use_issues_button: true
  use_repository_button: true

repository:
  url: https://github.com/modflowpy/pyphoenix-project
  branch: develop
  path_to_book: docs

sphinx:
  extra_extensions: []
