# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

from xattree import xattree

from flopy4.mf6.package import Package
from flopy4.mf6.spec import field, path
from flopy4.utils import to_path


@xattree(kw_only=True)
class Api(Package):
    multi_package: ClassVar[bool] = True

    boundnames: bool = field(block="options", default=False)
    print_input: bool = field(
        block="options", default=False, longname="print input to listing file"
    )
    print_flows: bool = field(
        block="options", default=False, longname="print calculated flows to listing file"
    )
    save_flows: bool = field(
        block="options", default=False, longname="save api flows to budget file"
    )
    obs_filerecord: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="filein"
    )
    mover: bool = field(block="options", default=False)
    maxbound: Optional[int] = field(
        block="dimensions",
        default=None,
        init=False,
        longname="maximum number of user-defined api boundaries",
    )
