# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

import attrs

from flopy4.mf6._types import _optional_path
from flopy4.mf6.package import Package
from flopy4.mf6.spec import field, path


@attrs.define(kw_only=True, slots=False)
class Api(Package):
    multi_package: ClassVar[bool] = True

    boundnames: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    print_input: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    print_flows: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    save_flows: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    obs_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        inout="filein",
    )
    mover: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    maxbound: Optional[int] = field(
        default=0,
        block="dimensions",
        auto_from="stress_period_data",
    )
