# autogenerated file, do not modify
# ruff: noqa: E501
from pathlib import Path
from typing import ClassVar, Optional

import attrs
import numpy as np
from attrs import Converter
from numpy.typing import NDArray
from xattree import xattree

from flopy4.mf6.converter import structure_array
from flopy4.mf6.package import Package
from flopy4.mf6.spec import array, dim, field, path
from flopy4.utils import to_path


@xattree(kw_only=True)
class Buy(Package):
    hhformulation_rhs: bool = field(
        block="options", default=False, longname="hh formulation on right-hand side"
    )
    denseref: Optional[float] = field(block="options", default=None, longname="reference density")
    density_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="fileout"
    )
    dev_efh_formulation: bool = field(
        block="options", default=False, longname="use equivalent freshwater head formulation"
    )
    nrhospecies: Optional[int] = dim(
        block="dimensions",
        coord=False,
        default=None,
        longname="number of species used in density equation of state",
    )
    _packagedata: Optional[dict] = attrs.field(alias="packagedata", default=None, repr=False)
    irhospec: Optional[NDArray[np.int64]] = array(
        block="packagedata",
        dims=("nrhospecies",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="species number for this entry",
        cellid=True,
    )
    drhodc: Optional[NDArray[np.float64]] = array(
        block="packagedata",
        dims=("nrhospecies",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="slope of the density-concentration line",
    )
    crhoref: Optional[NDArray[np.float64]] = array(
        block="packagedata",
        dims=("nrhospecies",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="reference concentration value",
    )
    modelname: Optional[NDArray[np.object_]] = array(
        block="packagedata",
        dims=("nrhospecies",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="modelname",
    )
    auxspeciesname: Optional[NDArray[np.object_]] = array(
        block="packagedata",
        dims=("nrhospecies",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="auxspeciesname",
    )
    __block_col_maps__: ClassVar[dict] = {
        "packagedata": {
            "irhospec": "irhospec",
            "drhodc": "drhodc",
            "crhoref": "crhoref",
            "modelname": "modelname",
            "auxspeciesname": "auxspeciesname",
        },
    }

    def __attrs_post_init__(self):
        if self._packagedata is not None:
            self._set_block(
                "packagedata",
                "nrhospecies",
                True,
                {
                    "irhospec": "irhospec",
                    "drhodc": "drhodc",
                    "crhoref": "crhoref",
                    "modelname": "modelname",
                    "auxspeciesname": "auxspeciesname",
                },
                self._packagedata,
            )

    @property
    def packagedata(self):
        return self._get_block(
            {
                "irhospec": "irhospec",
                "drhodc": "drhodc",
                "crhoref": "crhoref",
                "modelname": "modelname",
                "auxspeciesname": "auxspeciesname",
            }
        )

    @packagedata.setter
    def packagedata(self, value) -> None:
        self._set_block(
            "packagedata",
            "nrhospecies",
            True,
            {
                "irhospec": "irhospec",
                "drhodc": "drhodc",
                "crhoref": "crhoref",
                "modelname": "modelname",
                "auxspeciesname": "auxspeciesname",
            },
            value,
        )
