# Hand-written; kept out of codegen (_SKIP) because packagedata arrays require
# a row-per-record table format that the autogenerated separate-array approach
# does not produce. Specify packagedata as a list of tuples:
#   [(irhospec, drhodc, crhoref, modelname, auxspeciesname), ...]
from pathlib import Path
from typing import Optional

from xattree import xattree

from flopy4.mf6.package import Package
from flopy4.mf6.spec import field, path
from flopy4.utils import to_path


@xattree(kw_only=True)
class Buy(Package):
    hhformulation_rhs: bool = field(
        block="options", default=False, longname="hh formulation on right-hand side"
    )
    denseref: Optional[float] = field(block="options", default=None, longname="reference density")
    density_filerecord: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="fileout"
    )
    dev_efh_formulation: bool = field(
        block="options", default=False, longname="use equivalent freshwater head formulation"
    )
    nrhospecies: int = field(
        block="dimensions",
        default=0,
        longname="number of species used in density equation of state",
    )
    # Each row: (irhospec, drhodc, crhoref, modelname, auxspeciesname)
    # TODO: replace with named column fields (irhospec, drhodc, crhoref, modelname,
    # auxspeciesname) once the unstructure layer combines packagedata-block arrays
    # into an xr.Dataset the way period data is combined, so they write as a
    # row-per-record table instead of separate named arrays.
    packagedata: Optional[list] = field(block="packagedata", default=None)
