# autogenerated file, do not modify
# ruff: noqa: E501
from pathlib import Path
from typing import Optional

import numpy as np
from attrs import Converter
from numpy.typing import NDArray
from xattree import xattree

from flopy4.mf6.converter import structure_array
from flopy4.mf6.package import Package
from flopy4.mf6.spec import array, dim, field, path
from flopy4.utils import to_path


@xattree(kw_only=True)
class Buy(Package):
    hhformulation_rhs: bool = field(
        block="options", default=False, longname="hh formulation on right-hand side"
    )
    denseref: Optional[float] = field(block="options", default=None, longname="reference density")
    density_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="fileout"
    )
    dev_efh_formulation: bool = field(
        block="options", default=False, longname="use equivalent freshwater head formulation"
    )
    nrhospecies: Optional[int] = dim(
        block="dimensions",
        coord=False,
        default=None,
        longname="number of species used in density equation of state",
    )
    irhospec: Optional[NDArray[np.int64]] = array(
        block="packagedata",
        dims=("nrhospecies",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="species number for this entry",
    )
    drhodc: Optional[NDArray[np.float64]] = array(
        block="packagedata",
        dims=("nrhospecies",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="slope of the density-concentration line",
    )
    crhoref: Optional[NDArray[np.float64]] = array(
        block="packagedata",
        dims=("nrhospecies",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="reference concentration value",
    )
    modelname: Optional[NDArray[np.object_]] = array(
        block="packagedata",
        dims=("nrhospecies",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="modelname",
    )
    auxspeciesname: Optional[NDArray[np.object_]] = array(
        block="packagedata",
        dims=("nrhospecies",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="auxspeciesname",
    )
