# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional, TypeAlias, Union

import attrs
from numpy.typing import NDArray

from flopy4.mf6.package import Package
from flopy4.utils import to_path

try:
    import dask.array as da

    ArrayLike: TypeAlias = Union[NDArray, da.Array]
except ImportError:
    ArrayLike: TypeAlias = NDArray  # type: ignore[misc, no-redef]  # dask optional


@attrs.define(kw_only=True, slots=False)
class Chdg(Package):
    multi_package: ClassVar[bool] = True

    readarraygrid: bool = attrs.field(
        default=True,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
        },
    )
    auxiliary: Optional[list[str]] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "options",
            "dfn_type": "string",
            "shape": (),
            "optional": True,
        },
    )
    auxmultname: Optional[str] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "options",
            "dfn_type": "string",
            "optional": True,
        },
    )
    print_input: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    print_flows: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    save_flows: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    obs_file: Optional[Path] = attrs.field(
        default=None,
        converter=lambda v: None if v is None else to_path(v),
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "filein",
        },
    )
    export_array_netcdf: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    dev_no_newton: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    maxbound: Optional[int] = attrs.field(
        default=0,
        metadata={
            "dfn_block": "dimensions",
            "dfn_type": "integer",
            "optional": True,
            "auto_from": "stress_period_data",
        },
    )
    head: Optional[ArrayLike] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "period",
            "reader": "readarray",
            "dfn_type": "double",
            "layered": True,
        },
    )
    aux: Optional[ArrayLike] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "period",
            "reader": "readarray",
            "dfn_type": "double",
            "layered": True,
        },
    )
