# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

import attrs

from flopy4.mf6._types import FloatArrayLike, _optional_path
from flopy4.mf6.package import Package
from flopy4.mf6.spec import field, path


@attrs.define(kw_only=True, slots=False)
class Chdg(Package):
    dfn_name: ClassVar[str] = "gwf-chdg"

    multi_package: ClassVar[bool] = True

    readarraygrid: bool = field(
        default=True,
        block="options",
        longname="use array-based grid input",
    )
    auxiliary: Optional[list[str]] = field(
        default=None,
        block="options",
        optional=True,
        longname="keyword to specify aux variables",
    )
    auxmultname: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
        longname="name of auxiliary variable for multiplier",
    )
    print_input: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="print input to listing file",
    )
    print_flows: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="print CHD flows to listing file",
    )
    save_flows: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="save CHD flows to budget file",
    )
    obs_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="in",
    )
    export_array_netcdf: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="export array variables to netcdf output files.",
    )
    maxbound: Optional[int] = field(
        default=0,
        block="dimensions",
        optional=True,
        auto_from="stress_period_data",
        longname="maximum number of constant head cells in any stress period",
    )
    head: Optional[FloatArrayLike] = field(
        default=None,
        block="period",
        reader="readarray",
        layered=True,
    )
    aux: Optional[FloatArrayLike] = field(
        default=None,
        block="period",
        reader="readarray",
        layered=True,
    )
