# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional, TypeAlias, Union

import attrs
import numpy as np
from numpy.typing import NDArray

from flopy4.mf6.package import Package
from flopy4.utils import to_path

try:
    import dask.array as da

    ArrayLike: TypeAlias = Union[NDArray, da.Array]
except ImportError:
    ArrayLike: TypeAlias = NDArray  # type: ignore[misc, no-redef]  # dask optional


@attrs.define(kw_only=True, slots=False)
class Csub(Package):
    boundnames: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    print_input: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    save_flows: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    gammaw: Optional[float] = attrs.field(
        default="9806.65",
        metadata={
            "dfn_block": "options",
            "dfn_type": "double",
            "optional": True,
        },
    )  # type: ignore[assignment]
    beta: Optional[float] = attrs.field(
        default="4.6512e-10",
        metadata={
            "dfn_block": "options",
            "dfn_type": "double",
            "optional": True,
        },
    )  # type: ignore[assignment]
    head_based: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    initial_preconsolidation_head: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    ndelaycells: Optional[int] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "options",
            "dfn_type": "integer",
            "optional": True,
        },
    )
    compression_indices: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    update_material_properties: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    cell_fraction: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    specified_initial_interbed_state: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    specified_initial_preconsolidation_stress: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    specified_initial_delay_head: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    effective_stress_lag: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    strainib_file: Optional[Path] = attrs.field(
        default=None,
        converter=lambda v: None if v is None else to_path(v),
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "fileout",
        },
    )
    straincg_file: Optional[Path] = attrs.field(
        default=None,
        converter=lambda v: None if v is None else to_path(v),
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "fileout",
        },
    )
    compaction_file: Optional[Path] = attrs.field(
        default=None,
        converter=lambda v: None if v is None else to_path(v),
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "fileout",
        },
    )
    compaction_elastic_file: Optional[Path] = attrs.field(
        default=None,
        converter=lambda v: None if v is None else to_path(v),
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "fileout",
        },
    )
    compaction_inelastic_file: Optional[Path] = attrs.field(
        default=None,
        converter=lambda v: None if v is None else to_path(v),
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "fileout",
        },
    )
    compaction_interbed_file: Optional[Path] = attrs.field(
        default=None,
        converter=lambda v: None if v is None else to_path(v),
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "fileout",
        },
    )
    compaction_coarse_file: Optional[Path] = attrs.field(
        default=None,
        converter=lambda v: None if v is None else to_path(v),
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "fileout",
        },
    )
    zdisplacement_file: Optional[Path] = attrs.field(
        default=None,
        converter=lambda v: None if v is None else to_path(v),
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "fileout",
        },
    )
    package_convergence_file: Optional[Path] = attrs.field(
        default=None,
        converter=lambda v: None if v is None else to_path(v),
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "fileout",
        },
    )
    ts_file: Optional[Path] = attrs.field(
        default=None,
        converter=lambda v: None if v is None else to_path(v),
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "filein",
        },
    )
    obs_file: Optional[Path] = attrs.field(
        default=None,
        converter=lambda v: None if v is None else to_path(v),
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "filein",
        },
    )
    ninterbeds: Optional[int] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "dimensions",
            "dfn_type": "integer",
        },
    )
    maxsig0: Optional[int] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "dimensions",
            "dfn_type": "integer",
            "optional": True,
        },
    )
    packagedata: Optional[np.recarray] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "packagedata",
            "schema": "__packagedata_schema__",
            "auto_from": "packagedata",
        },
    )
    cg_ske_cr: ArrayLike = attrs.field(
        default="1e-5",
        metadata={
            "dfn_block": "griddata",
            "dfn_type": "double",
            "shape": ("nodes",),
            "layered": True,
            "chunk_axis": "nlay",
            "netcdf": True,
        },
    )  # type: ignore[assignment]
    cg_theta: ArrayLike = attrs.field(
        default="0.2",
        metadata={
            "dfn_block": "griddata",
            "dfn_type": "double",
            "shape": ("nodes",),
            "layered": True,
            "chunk_axis": "nlay",
            "netcdf": True,
        },
    )  # type: ignore[assignment]
    sgm: Optional[ArrayLike] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "griddata",
            "dfn_type": "double",
            "shape": ("nodes",),
            "layered": True,
            "chunk_axis": "nlay",
            "netcdf": True,
            "optional": True,
        },
    )
    sgs: Optional[ArrayLike] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "griddata",
            "dfn_type": "double",
            "shape": ("nodes",),
            "layered": True,
            "chunk_axis": "nlay",
            "netcdf": True,
            "optional": True,
        },
    )
    _stress_period_data: Optional[dict[int, np.recarray]] = attrs.field(
        alias="stress_period_data",
        default=None,
        repr=False,
        metadata={
            "dfn_block": "period",
            "schema": "__period_schema__",
            "fill_forward": True,
        },
    )
    __packagedata_schema__: ClassVar[list[dict]] = [
        {
            "name": "icsubno",
            "dfn_type": "integer",
            "role": "feature_id",
        },
        {
            "name": "cellid",
            "dfn_type": "integer",
            "role": "cellid",
        },
        {
            "name": "cdelay",
            "dfn_type": "string",
            "role": "value",
            "dtype": "np.object_",
        },
        {
            "name": "pcs0",
            "dfn_type": "double",
            "role": "value",
        },
        {
            "name": "thick_frac",
            "dfn_type": "double",
            "role": "value",
        },
        {
            "name": "rnb",
            "dfn_type": "double",
            "role": "value",
        },
        {
            "name": "ssv_cc",
            "dfn_type": "double",
            "role": "value",
        },
        {
            "name": "sse_cr",
            "dfn_type": "double",
            "role": "value",
        },
        {
            "name": "theta",
            "dfn_type": "double",
            "role": "value",
        },
        {
            "name": "kv",
            "dfn_type": "double",
            "role": "value",
        },
        {
            "name": "h0",
            "dfn_type": "double",
            "role": "value",
        },
        {
            "name": "boundname",
            "dfn_type": "string",
            "role": "boundname",
        },
    ]

    __period_schema__: ClassVar[list[dict]] = [
        {
            "name": "cellid",
            "dfn_type": "integer",
            "role": "cellid",
            "shape": "ncelldim",
            "optional": False,
        },
        {
            "name": "sig0",
            "dfn_type": "double",
            "optional": False,
            "role": "value",
            "time_series": True,
            "dtype": "np.object_",
        },
    ]

    packagedata_dtype: np.dtype = attrs.field(init=False, factory=lambda: np.dtype([]))
    period_dtype: np.dtype = attrs.field(init=False, factory=lambda: np.dtype([]))

    _DTYPE_MAP: ClassVar[dict] = {
        "integer": np.int64,
        "double": np.float64,
        "double precision": np.float64,
        "string": np.object_,
        "keyword": np.object_,
        "object": np.object_,
    }

    def __attrs_post_init__(self) -> None:
        _aux_tmp = getattr(self, "auxiliary", None)
        naux = len(_aux_tmp) if _aux_tmp is not None else 0
        ncelldim = self._compute_ncelldim()
        _packagedata_f: list[tuple] = []
        for _col in self.__packagedata_schema__:
            _role = _col.get("role", "value")
            _dt = _col.get("dtype")
            _dt = (
                eval(_dt)
                if _dt
                else self._DTYPE_MAP.get(_col.get("dfn_type", "string"), np.object_)
            )
            if _role == "cellid":
                _packagedata_f.append((_col["name"], np.int64, (ncelldim,)))
            elif _role == "feature_id":
                _packagedata_f.append((_col["name"], np.int64))
            elif _role == "boundname":
                if getattr(self, "boundnames", False):
                    _packagedata_f.append((_col["name"], np.object_))
            else:
                _packagedata_f.append((_col["name"], _dt))
        if "packagedata" == "packagedata":
            for _i in range(naux):
                _packagedata_f.append((f"aux{_i}", np.object_))
        self.packagedata_dtype = np.dtype(_packagedata_f)
        _raw_packagedata = getattr(self, "packagedata", None)
        if _raw_packagedata is not None:
            self.packagedata = self._coerce_to_recarray(_raw_packagedata, self.packagedata_dtype)
        if (
            getattr(self, "packagedata", None) is not None
            and getattr(self, "npackagedatas", 0) == 0
        ):
            object.__setattr__(self, "npackagedatas", len(getattr(self, "packagedata")))
        _has_keystring = any(
            col.get("role") in ("keystring", "keystring_value") for col in self.__period_schema__
        )
        fields: list[tuple] = []
        for col in self.__period_schema__:
            role = col.get("role", "value")
            if role == "cellid":
                fields.append((col["name"], np.int64, (ncelldim,)))
            elif role in ("keystring", "keystring_value"):
                fields.append((col["name"], np.object_))
            elif col.get("time_series"):
                fields.append((col["name"], np.object_))
            elif not col.get("optional", False):
                _dt = col.get("dtype")
                _col_dt = (
                    eval(_dt)
                    if _dt
                    else self._DTYPE_MAP.get(col.get("dfn_type", "double"), np.float64)
                )
                fields.append((col["name"], _col_dt))
        if not _has_keystring:
            for i in range(naux):
                fields.append((f"aux{i}", np.object_))
            if getattr(self, "boundnames", False):
                fields.append(("boundname", np.object_))
        self.period_dtype = np.dtype(fields)
        if self._stress_period_data is not None:
            self._stress_period_data = {
                kper: self._coerce_to_recarray(rows, self.period_dtype)
                for kper, rows in self._stress_period_data.items()
            }
        _spd = self._stress_period_data
        if _spd and getattr(self, "maxbound", None) == 0:
            self.maxbound = max(len(v) for v in _spd.values())
        super().__attrs_post_init__()

    @property  # type: ignore[override]
    def stress_period_data(self) -> "Optional[dict[int, np.recarray]]":
        return self._stress_period_data

    @stress_period_data.setter
    def stress_period_data(self, value) -> None:
        self._stress_period_data = value

    def to_dataframe(self) -> "pandas.DataFrame":  # type: ignore[name-defined]
        """Return stress period data as a tidy pd.DataFrame. Zero cost if not called."""
        import pandas as pd

        _spd = self._stress_period_data
        if not _spd:
            return pd.DataFrame()
        frames = []
        for kper in sorted(_spd):
            arr = _spd[kper]
            rows = {}
            for nm in arr.dtype.names or ():
                col = arr[nm]
                rows[nm] = [tuple(v) for v in col] if col.ndim > 1 else col.tolist()
            df = pd.DataFrame(rows)
            df.insert(0, "kper", kper)
            frames.append(df)
        return pd.concat(frames, ignore_index=True)
