# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional, Union

import attrs

from flopy4.mf6._types import FloatArrayLike, _optional_path
from flopy4.mf6.item import Item
from flopy4.mf6.package import Package
from flopy4.mf6.spec import field, path


@attrs.define(kw_only=True, slots=False)
class Csub(Package):
    dfn_name: ClassVar[str] = "gwf-csub"

    @attrs.define
    class Packagedata(Item):
        icsubno: int = field(index=True, pk=True)
        cellid: tuple = field(cellid=True)
        cdelay: Union[float, str] = field()
        pcs0: float = field()
        thick_frac: float = field()
        rnb: float = field()
        ssv_cc: float = field()
        sse_cr: float = field()
        theta: float = field()
        kv: float = field()
        h0: float = field()
        aux: tuple = ()
        boundname: Optional[str] = field(default=None, optional=True)

    @attrs.define
    class StressPeriodData(Item):
        cellid: tuple = field(cellid=True)
        sig0: Union[float, str] = field(time_series=True)
        aux: tuple = ()

    boundnames: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    print_input: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="print input to listing file",
    )
    save_flows: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="keyword to save CSUB flows",
    )
    gammaw: Optional[float] = field(
        default=9806.65,
        block="options",
        optional=True,
        longname="unit weight of water",
    )
    beta: Optional[float] = field(
        default=4.6512e-10,
        block="options",
        optional=True,
        longname="compressibility of water",
    )
    elastic_inelastic_smoothing: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="elastic to inelastic smoothing",
    )
    strict_effective_stress: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="terminate on negative effective stress",
    )
    head_based: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="keyword to indicate the head-based formulation will be used",
    )
    initial_preconsolidation_head: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="keyword to indicate that preconsolidation heads will be specified",
    )
    ndelaycells: Optional[int] = field(
        default=None,
        block="options",
        optional=True,
        longname="number of interbed cell nodes",
    )
    compression_indices: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="keyword to indicate CR and CC are read instead of SSE and SSV",
    )
    update_material_properties: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="keyword to indicate material properties can change during the simulations",
    )
    cell_fraction: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="keyword to indicate cell fraction interbed thickness",
    )
    specified_initial_interbed_state: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="keyword to indicate that absolute initial states will be specified",
    )
    specified_initial_preconsolidation_stress: bool = field(
        default=False,
        block="options",
        optional=True,
        longname=(
            "keyword to indicate that absolute initial preconsolidation stresses (head) will be "
            "specified"
        ),
    )
    specified_initial_delay_head: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="keyword to indicate that absolute initial delay bed heads will be specified",
    )
    effective_stress_lag: bool = field(
        default=False,
        block="options",
        optional=True,
        longname=(
            "keyword to indicate that specific storage will be calculate using the effective "
            "stress from the previous time step"
        ),
    )
    strainib_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="out",
        keyword="strain_csv_interbed",
    )
    straincg_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="out",
        keyword="strain_csv_coarse",
    )
    compaction_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="out",
        keyword="compaction",
    )
    compaction_elastic_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="out",
        keyword="compaction_elastic",
    )
    compaction_inelastic_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="out",
        keyword="compaction_inelastic",
    )
    compaction_interbed_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="out",
        keyword="compaction_interbed",
    )
    compaction_coarse_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="out",
        keyword="compaction_coarse",
    )
    zdisplacement_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="out",
        keyword="zdisplacement",
    )
    package_convergence_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="out",
        keyword="package_convergence",
    )
    ts_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="in",
        keyword="ts6",
    )
    obs_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="in",
        keyword="obs6",
    )
    ninterbeds: Optional[int] = field(
        default=None,
        block="dimensions",
        longname="number of CSUB interbed systems",
    )
    maxsig0: Optional[int] = field(
        default=None,
        block="dimensions",
        optional=True,
        longname="maximum number of stress offset cells",
    )
    packagedata: Optional[list[Packagedata]] = field(
        default=None,
        block="packagedata",
        auto_from="packagedata",
    )
    cg_ske_cr: FloatArrayLike = field(
        default=1e-05,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
        longname="elastic coarse specific storage",
    )  # type: ignore[assignment]
    cg_theta: FloatArrayLike = field(
        default=0.2,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
        longname="initial coarse-grained material porosity",
    )  # type: ignore[assignment]
    sgm: Optional[FloatArrayLike] = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
        optional=True,
        longname="specific gravity of moist sediments",
    )
    sgs: Optional[FloatArrayLike] = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
        optional=True,
        longname="specific gravity of saturated sediments",
    )
    _stress_period_data: Optional[dict[int, list[StressPeriodData]]] = field(
        alias="stress_period_data",
        default=None,
        repr=False,
        block="period",
        fill_forward=True,
    )


CsubStressPeriodData = Csub.StressPeriodData
CsubPackagedata = Csub.Packagedata
