# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional, Union

import attrs

from flopy4.mf6._types import FloatArrayLike, _optional_path
from flopy4.mf6.item import Item
from flopy4.mf6.package import Package
from flopy4.mf6.spec import field, path


@attrs.define(kw_only=True, slots=False)
class Csub(Package):
    dfn_name: ClassVar[str] = "gwf-csub"

    @attrs.define
    class Packagedata(Item):
        icsubno: int = field(index=True, pk=True)
        cellid: tuple = field(cellid=True)
        cdelay: Union[float, str] = field()
        pcs0: float = field()
        thick_frac: float = field()
        rnb: float = field()
        ssv_cc: float = field()
        sse_cr: float = field()
        theta: float = field()
        kv: float = field()
        h0: float = field()
        aux: tuple = ()
        boundname: Optional[str] = field(default=None, optional=True)

    @attrs.define
    class StressPeriodData(Item):
        cellid: tuple = field(cellid=True)
        sig0: Union[float, str] = field(time_series=True)
        aux: tuple = ()

    boundnames: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    print_input: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    save_flows: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    gammaw: Optional[float] = field(
        default=9806.65,
        block="options",
        optional=True,
    )
    beta: Optional[float] = field(
        default=4.6512e-10,
        block="options",
        optional=True,
    )
    elastic_inelastic_smoothing: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    strict_effective_stress: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    head_based: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    initial_preconsolidation_head: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    ndelaycells: Optional[int] = field(
        default=None,
        block="options",
        optional=True,
    )
    compression_indices: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    update_material_properties: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    cell_fraction: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    specified_initial_interbed_state: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    specified_initial_preconsolidation_stress: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    specified_initial_delay_head: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    effective_stress_lag: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    strainib_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        inout="fileout",
    )
    straincg_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        inout="fileout",
    )
    compaction_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        inout="fileout",
    )
    compaction_elastic_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        inout="fileout",
    )
    compaction_inelastic_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        inout="fileout",
    )
    compaction_interbed_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        inout="fileout",
    )
    compaction_coarse_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        inout="fileout",
    )
    zdisplacement_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        inout="fileout",
    )
    package_convergence_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        inout="fileout",
    )
    ts_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        inout="filein",
    )
    obs_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        inout="filein",
    )
    ninterbeds: Optional[int] = field(
        default=None,
        block="dimensions",
    )
    maxsig0: Optional[int] = field(
        default=None,
        block="dimensions",
        optional=True,
    )
    packagedata: Optional[list[Packagedata]] = field(
        default=None,
        block="packagedata",
        auto_from="packagedata",
    )
    cg_ske_cr: FloatArrayLike = field(
        default=1e-05,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
    )  # type: ignore[assignment]
    cg_theta: FloatArrayLike = field(
        default=0.2,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
    )  # type: ignore[assignment]
    sgm: Optional[FloatArrayLike] = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
        optional=True,
    )
    sgs: Optional[FloatArrayLike] = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
        optional=True,
    )
    _stress_period_data: Optional[dict[int, list[StressPeriodData]]] = field(
        alias="stress_period_data",
        default=None,
        repr=False,
        block="period",
        fill_forward=True,
    )

CsubStressPeriodData = Csub.StressPeriodData
CsubPackagedata = Csub.Packagedata
