# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

import attrs
import numpy as np

from flopy4.mf6._types import _optional_path
from flopy4.mf6.package import Package


@attrs.define(kw_only=True, slots=False)
class Drn(Package):
    multi_package: ClassVar[bool] = True

    auxiliary: Optional[list[str]] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "options",
            "dfn_type": "string",
            "shape": (),
            "optional": True,
        },
    )
    auxmultname: Optional[str] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "options",
            "dfn_type": "string",
            "optional": True,
        },
    )
    auxdepthname: Optional[str] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "options",
            "dfn_type": "string",
            "optional": True,
        },
    )
    boundnames: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    print_input: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    print_flows: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    save_flows: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    ts_file: Optional[Path] = attrs.field(
        default=None,
        converter=_optional_path,
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "filein",
        },
    )
    obs_file: Optional[Path] = attrs.field(
        default=None,
        converter=_optional_path,
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "filein",
        },
    )
    mover: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    dev_cubic_scaling: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    maxbound: Optional[int] = attrs.field(
        default=0,
        metadata={
            "dfn_block": "dimensions",
            "dfn_type": "integer",
            "auto_from": "stress_period_data",
        },
    )
    _stress_period_data: Optional[dict[int, np.recarray]] = attrs.field(
        alias="stress_period_data",
        default=None,
        repr=False,
        metadata={
            "dfn_block": "period",
            "schema": "__period_schema__",
            "fill_forward": True,
        },
    )
    __period_schema__: ClassVar[list[dict]] = [
        {
            "name": "cellid",
            "dfn_type": "integer",
            "role": "cellid",
            "shape": "ncelldim",
            "optional": False,
        },
        {
            "name": "elev",
            "dfn_type": "double",
            "optional": False,
            "role": "value",
            "time_series": True,
            "dtype": "np.object_",
        },
        {
            "name": "cond",
            "dfn_type": "double",
            "optional": False,
            "role": "value",
            "time_series": True,
            "dtype": "np.object_",
        },
        {
            "name": "boundname",
            "dfn_type": "string",
            "optional": True,
            "role": "boundname",
            "dtype": "np.object_",
        },
    ]

    period_dtype: np.dtype = attrs.field(init=False, factory=lambda: np.dtype([]))
