# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional, Union

import attrs

from flopy4.mf6._types import _optional_path
from flopy4.mf6.item import Item
from flopy4.mf6.package import Package
from flopy4.mf6.spec import field, path


@attrs.define(kw_only=True, slots=False)
class Drn(Package):
    dfn_name: ClassVar[str] = "gwf-drn"

    multi_package: ClassVar[bool] = True

    @attrs.define
    class StressPeriodData(Item):
        cellid: tuple = field(cellid=True)
        elev: Union[float, str] = field(time_series=True)
        cond: Union[float, str] = field(time_series=True)
        aux: tuple = ()
        boundname: Optional[str] = field(default=None, optional=True)

    auxiliary: Optional[list[str]] = field(
        default=None,
        block="options",
        optional=True,
        longname="keyword to specify aux variables",
    )
    auxmultname: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
        longname="name of auxiliary variable for multiplier",
    )
    auxdepthname: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
        longname="name of auxiliary variable for drainage depth",
    )
    boundnames: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    print_input: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="print input to listing file",
    )
    print_flows: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="print calculated flows to listing file",
    )
    save_flows: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="save DRN flows to budget file",
    )
    ts_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="in",
    )
    obs_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="in",
    )
    mover: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    _stress_period_data: Optional[dict[int, list[StressPeriodData]]] = field(
        alias="stress_period_data",
        default=None,
        repr=False,
        block="period",
        fill_forward=True,
    )

    @property
    def maxbound(self) -> int:
        """Maximum number of active entries in any stress period.

        Computed live from `stress_period_data`'s row counts -- not
        stored or independently settable.
        """
        if not self.stress_period_data:
            return 0
        return max(len(v) for v in self.stress_period_data.values())


DrnStressPeriodData = Drn.StressPeriodData
