# autogenerated file, do not modify
from typing import ClassVar, Optional

import attrs
import numpy as np
from numpy.typing import NDArray

from flopy4.mf6._types import ARRAY_EQ, FloatArrayLike, to_array
from flopy4.mf6.package import Package
from flopy4.mf6.spec import child, field
from flopy4.mf6.utl.obs import Obs


@attrs.define(kw_only=True, slots=False)
class Drng(Package):
    dfn_name: ClassVar[str] = "gwf-drng"

    multi_package: ClassVar[bool] = True

    observations: ClassVar[dict[str, tuple[tuple[str, ...], ...]]] = {
        "drn": (("cellid",), ("string",)),
        "to-mvr": (("cellid",), ("string",)),
    }

    readarraygrid: bool = field(
        default=True,
        block="options",
        longname="use array-based grid input",
    )
    auxiliary: Optional[NDArray[np.str_]] = field(
        default=None,
        converter=attrs.converters.optional(to_array(np.str_)),
        eq=ARRAY_EQ,
        block="options",
        optional=True,
        longname="keyword to specify aux variables",
    )
    auxmultname: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
        longname="name of auxiliary variable for multiplier",
    )
    auxdepthname: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
        longname="name of auxiliary variable for drainage depth",
    )
    print_input: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="print input to listing file",
    )
    print_flows: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="print calculated flows to listing file",
    )
    save_flows: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="save DRNG flows to budget file",
    )
    obs: Optional[Obs] = child(block="options", keyword="obs6", direction="in")
    mover: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    export_array_netcdf: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="export array variables to netcdf output files.",
    )
    maxbound: Optional[int] = field(
        default=None,
        block="dimensions",
        optional=True,
        longname="maximum number of drain cells in any stress period",
    )
    elev: Optional[dict[int, FloatArrayLike]] = field(
        default=None,
        block="period",
        shape=("nodes",),
        layered=True,
        netcdf=True,
        fill_forward=True,
    )
    cond: Optional[dict[int, FloatArrayLike]] = field(
        default=None,
        block="period",
        shape=("nodes",),
        layered=True,
        netcdf=True,
        fill_forward=True,
    )
    aux: Optional[dict[int, dict[str, FloatArrayLike]]] = field(
        default=None,
        block="period",
        shape=("nodes",),
        layered=True,
        netcdf=True,
        fill_forward=True,
        fk="options.auxiliary",
    )
