# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

import numpy as np
from attrs import Converter
from numpy.typing import NDArray
from xattree import xattree

from flopy4.mf6.constants import LENBOUNDNAME
from flopy4.mf6.converter import structure_array
from flopy4.mf6.package import Package
from flopy4.mf6.spec import array, dim, field, path
from flopy4.mf6.utils.grid import update_maxbound
from flopy4.utils import to_path


@xattree(kw_only=True)
class Evt(Package):
    multi_package: ClassVar[bool] = True

    fixed_cell: bool = field(
        block="options",
        default=False,
        longname="if cell is dry do not apply evapotranspiration to underlying cell",
    )
    auxiliary: Optional[list[str]] = array(
        block="options", default=None, longname="keyword to specify aux variables"
    )
    auxmultname: Optional[str] = field(
        block="options", default=None, longname="name of auxiliary variable for multiplier"
    )
    boundnames: bool = field(block="options", default=False)
    print_input: bool = field(
        block="options", default=False, longname="print input to listing file"
    )
    print_flows: bool = field(
        block="options", default=False, longname="print evapotranspiration rates to listing file"
    )
    save_flows: bool = field(
        block="options", default=False, longname="save evapotranspiration rates to budget file"
    )
    ts_filerecord: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="filein"
    )
    obs_filerecord: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="filein"
    )
    surf_rate_specified: bool = field(
        block="options",
        default=False,
        longname="specify proportion of evapotranspiration rate at et surface",
    )
    maxbound: Optional[int] = field(
        block="dimensions",
        default=None,
        init=False,
        longname="maximum number of evapotranspiration cells",
    )
    nseg: Optional[int] = dim(
        block="dimensions", coord=False, default=None, longname="number of et segments"
    )
    surface: Optional[NDArray[np.float64]] = array(
        block="period",
        dims=("nper", "nodes"),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        on_setattr=update_maxbound,
        longname="et surface",
    )
    rate: Optional[NDArray[np.float64]] = array(
        block="period",
        dims=("nper", "nodes"),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        on_setattr=update_maxbound,
        longname="maximum et rate",
    )
    depth: Optional[NDArray[np.float64]] = array(
        block="period",
        dims=("nper", "nodes"),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        on_setattr=update_maxbound,
        longname="et extinction depth",
    )
    pxdp: Optional[NDArray[np.float64]] = array(
        block="period",
        dims=("nper", "nodes"),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        on_setattr=update_maxbound,
        longname="proportion of et extinction depth",
    )
    petm: Optional[NDArray[np.float64]] = array(
        block="period",
        dims=("nper", "nodes"),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        on_setattr=update_maxbound,
        longname="proportion of maximum et rate",
    )
    petm0: Optional[NDArray[np.float64]] = array(
        block="period",
        dims=("nper", "nodes"),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        on_setattr=update_maxbound,
        longname="proportion of maximum et rate at et surface",
    )
    aux: Optional[NDArray[np.float64]] = array(
        block="period",
        dims=("nper", "nodes"),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        on_setattr=update_maxbound,
        longname="auxiliary variables",
    )
    boundname: Optional[NDArray[np.str_]] = array(
        dtype=f"<U{LENBOUNDNAME}",
        block="period",
        dims=("nper", "nodes"),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        on_setattr=update_maxbound,
        longname="evapotranspiration name",
    )
