# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

import attrs

from flopy4.mf6._types import ArrayLike, _optional_path
from flopy4.mf6.package import Package


@attrs.define(kw_only=True, slots=False)
class Evta(Package):
    multi_package: ClassVar[bool] = True

    readasarrays: bool = attrs.field(
        default=True,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
        },
    )
    fixed_cell: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    auxiliary: Optional[list[str]] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "options",
            "dfn_type": "string",
            "shape": (),
            "optional": True,
        },
    )
    auxmultname: Optional[str] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "options",
            "dfn_type": "string",
            "optional": True,
        },
    )
    print_input: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    print_flows: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    save_flows: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    tas_file: Optional[Path] = attrs.field(
        default=None,
        converter=_optional_path,
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "filein",
        },
    )
    obs_file: Optional[Path] = attrs.field(
        default=None,
        converter=_optional_path,
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "filein",
        },
    )
    export_array_netcdf: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    ievt: Optional[ArrayLike] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "period",
            "reader": "readarray",
            "dfn_type": "integer",
            "layered": False,
        },
    )
    surface: Optional[ArrayLike] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "period",
            "reader": "readarray",
            "dfn_type": "double",
            "layered": False,
        },
    )
    rate: Optional[ArrayLike] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "period",
            "reader": "readarray",
            "dfn_type": "double",
            "layered": False,
        },
    )
    depth: Optional[ArrayLike] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "period",
            "reader": "readarray",
            "dfn_type": "double",
            "layered": False,
        },
    )
    aux: Optional[ArrayLike] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "period",
            "reader": "readarray",
            "dfn_type": "double",
            "layered": False,
        },
    )
