# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

import numpy as np
from attrs import Converter
from numpy.typing import NDArray
from xattree import xattree

from flopy4.mf6.converter import structure_array
from flopy4.mf6.package import Package
from flopy4.mf6.spec import array, field, path
from flopy4.mf6.utils.grid import update_maxbound
from flopy4.utils import to_path


@xattree(kw_only=True)
class Ghbg(Package):
    multi_package: ClassVar[bool] = True

    readarraygrid: bool = field(
        block="options", default=True, longname="use array-based grid input"
    )
    auxiliary: Optional[list[str]] = array(
        block="options", default=None, longname="keyword to specify aux variables"
    )
    auxmultname: Optional[str] = field(
        block="options", default=None, longname="name of auxiliary variable for multiplier"
    )
    print_input: bool = field(
        block="options", default=False, longname="print input to listing file"
    )
    print_flows: bool = field(
        block="options", default=False, longname="print calculated flows to listing file"
    )
    save_flows: bool = field(
        block="options", default=False, longname="save ghbg flows to budget file"
    )
    obs_filerecord: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="filein"
    )
    mover: bool = field(block="options", default=False)
    export_array_netcdf: bool = field(
        block="options", default=False, longname="export array variables to netcdf output files."
    )
    maxbound: Optional[int] = field(
        block="dimensions",
        default=None,
        init=False,
        longname="maximum number of general-head boundaries in any stress period",
    )
    bhead: Optional[NDArray[np.float64]] = array(
        block="period",
        dims=("nper", "nodes"),
        default=None,
        netcdf=True,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        on_setattr=update_maxbound,
        longname="boundary head",
    )
    cond: Optional[NDArray[np.float64]] = array(
        block="period",
        dims=("nper", "nodes"),
        default=None,
        netcdf=True,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        on_setattr=update_maxbound,
        longname="boundary conductance",
    )
    aux: Optional[NDArray[np.float64]] = array(
        block="period",
        dims=("nper", "nodes"),
        default=None,
        netcdf=True,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        on_setattr=update_maxbound,
        longname="general-head boundary auxiliary variable iaux",
    )
