# autogenerated file, do not modify
from typing import TypeAlias, Union

import attrs
from numpy.typing import NDArray

from flopy4.mf6.package import Package

try:
    import dask.array as da

    ArrayLike: TypeAlias = Union[NDArray, da.Array]
except ImportError:
    ArrayLike: TypeAlias = NDArray  # type: ignore[misc, no-redef]  # dask optional


@attrs.define(kw_only=True, slots=False)
class Ic(Package):
    export_array_ascii: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    export_array_netcdf: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    strt: ArrayLike = attrs.field(
        default=1.0,
        metadata={
            "dfn_block": "griddata",
            "dfn_type": "double",
            "shape": ("nodes",),
            "layered": True,
            "chunk_axis": "nlay",
            "netcdf": True,
        },
    )  # type: ignore[assignment]
