# autogenerated file, do not modify
import attrs

from flopy4.mf6._types import ArrayLike
from flopy4.mf6.package import Package
from flopy4.mf6.spec import field


@attrs.define(kw_only=True, slots=False)
class Ic(Package):
    export_array_ascii: bool = field(
        default=False,
        block="options",
        dfn_type="keyword",
        optional=True,
    )
    export_array_netcdf: bool = field(
        default=False,
        block="options",
        dfn_type="keyword",
        optional=True,
    )
    strt: ArrayLike = field(
        default=1.0,
        block="griddata",
        dfn_type="double",
        shape=("nodes",),
        layered=True,
        netcdf=True,
    )  # type: ignore[assignment]
