# autogenerated file, do not modify
# ruff: noqa: E501
from pathlib import Path
from typing import ClassVar, Optional

import attrs
import numpy as np
from attrs import Converter
from numpy.typing import NDArray
from xattree import xattree

from flopy4.mf6.converter import structure_array
from flopy4.mf6.package import Package
from flopy4.mf6.spec import array, dim, embedded_keystring, field, path
from flopy4.utils import to_path


@xattree(kw_only=True)
class Lak(Package):
    multi_package: ClassVar[bool] = True

    auxiliary: Optional[list[str]] = array(
        block="options", default=None, longname="keyword to specify aux variables"
    )
    boundnames: bool = field(block="options", default=False)
    print_input: bool = field(
        block="options", default=False, longname="print input to listing file"
    )
    print_stage: bool = field(
        block="options", default=False, longname="print calculated stages to listing file"
    )
    print_flows: bool = field(
        block="options", default=False, longname="print calculated flows to listing file"
    )
    save_flows: bool = field(
        block="options", default=False, longname="save lake flows to budget file"
    )
    stage_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="fileout"
    )
    budget_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="fileout"
    )
    budgetcsv_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="fileout"
    )
    package_convergence_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="fileout"
    )
    ts_file: Optional[Path] = path(block="options", default=None, converter=to_path, inout="filein")
    obs_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="filein"
    )
    mover: bool = field(block="options", default=False)
    surfdep: Optional[float] = field(
        block="options", default=None, longname="surface depression depth"
    )
    maximum_iterations: Optional[int] = field(
        block="options", default=None, longname="lak newton-raphson iterations"
    )
    maximum_stage_change: Optional[float] = field(
        block="options", default=None, longname="stage closure tolerance"
    )
    time_conversion: Optional[float] = field(
        block="options", default=None, longname="time conversion factor"
    )
    length_conversion: Optional[float] = field(
        block="options", default=None, longname="length conversion factor"
    )
    nlakes: Optional[int] = dim(
        block="dimensions", coord=False, default=None, longname="number of lakes"
    )
    noutlets: Optional[int] = dim(
        block="dimensions", coord=False, default=None, longname="number of outlets"
    )
    ntables: Optional[int] = dim(
        block="dimensions", coord=False, default=None, longname="number of tables"
    )
    _packagedata: Optional[dict] = attrs.field(alias="packagedata", default=None, repr=False)
    naux: Optional[int] = dim(block="__dim__", coord=False, default=None)
    packagedata_ifno: Optional[NDArray[np.int64]] = array(
        block="packagedata",
        dims=("nlakes",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="lake number for this entry",
        cellid=True,
    )
    strt: Optional[NDArray[np.float64]] = array(
        block="packagedata",
        dims=("nlakes",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="starting lake stage",
    )
    nlakeconn: Optional[NDArray[np.int64]] = array(
        block="packagedata",
        dims=("nlakes",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="number of lake connections",
    )
    aux: Optional[NDArray[np.float64]] = array(
        block="packagedata",
        dims=("nlakes", "naux"),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="auxiliary variables",
    )
    boundname: Optional[NDArray[np.object_]] = array(
        block="packagedata",
        dims=("nlakes",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="well name",
    )
    _connectiondata: Optional[dict] = attrs.field(alias="connectiondata", default=None, repr=False)
    nconnectiondata: Optional[int] = dim(block="__dim__", coord=False, default=None)
    connectiondata_ifno: Optional[NDArray[np.int64]] = array(
        block="connectiondata",
        dims=("nconnectiondata",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="lake number for this entry",
        cellid=True,
    )
    iconn: Optional[NDArray[np.int64]] = array(
        block="connectiondata",
        dims=("nconnectiondata",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="connection number for this entry",
        cellid=True,
    )
    cellid: Optional[NDArray[np.object_]] = array(
        block="connectiondata",
        dims=("nconnectiondata",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="cell identifier",
        cellid=True,
    )
    claktype: Optional[NDArray[np.object_]] = array(
        block="connectiondata",
        dims=("nconnectiondata",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="lake connection type",
    )
    bedleak: Optional[NDArray[np.object_]] = array(
        block="connectiondata",
        dims=("nconnectiondata",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="bed leakance",
    )
    belev: Optional[NDArray[np.float64]] = array(
        block="connectiondata",
        dims=("nconnectiondata",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="bottom elevation",
    )
    telev: Optional[NDArray[np.float64]] = array(
        block="connectiondata",
        dims=("nconnectiondata",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="top elevation",
    )
    connlen: Optional[NDArray[np.float64]] = array(
        block="connectiondata",
        dims=("nconnectiondata",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="connection length",
    )
    connwidth: Optional[NDArray[np.float64]] = array(
        block="connectiondata",
        dims=("nconnectiondata",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="connection width",
    )
    _tables: Optional[dict] = attrs.field(alias="tables", default=None, repr=False)
    tables_ifno: Optional[NDArray[np.int64]] = array(
        block="tables",
        dims=("ntables",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="lake number for this entry",
        cellid=True,
    )
    tab6_filename: Optional[NDArray[np.object_]] = array(
        block="tables",
        dims=("ntables",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="table file name",
        prefix=("TAB6", "FILEIN"),
    )
    _outlets: Optional[dict] = attrs.field(alias="outlets", default=None, repr=False)
    outletno: Optional[NDArray[np.int64]] = array(
        block="outlets",
        dims=("noutlets",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="outlet number for this entry",
        cellid=True,
    )
    lakein: Optional[NDArray[np.int64]] = array(
        block="outlets",
        dims=("noutlets",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="lake number for upstream lake",
        cellid=True,
    )
    lakeout: Optional[NDArray[np.int64]] = array(
        block="outlets",
        dims=("noutlets",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="lake number for downstream lake",
        cellid=True,
    )
    couttype: Optional[NDArray[np.object_]] = array(
        block="outlets",
        dims=("noutlets",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="outlet type",
    )
    outlets_invert: Optional[NDArray[np.float64]] = array(
        block="outlets",
        dims=("noutlets",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="invert elevation",
    )
    outlets_width: Optional[NDArray[np.float64]] = array(
        block="outlets",
        dims=("noutlets",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="outlet width",
    )
    outlets_rough: Optional[NDArray[np.float64]] = array(
        block="outlets",
        dims=("noutlets",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="roughness coefficient",
    )
    outlets_slope: Optional[NDArray[np.float64]] = array(
        block="outlets",
        dims=("noutlets",),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        longname="bed slope",
    )
    status: Optional[NDArray[np.object_]] = embedded_keystring(
        "STATUS",
        "nlakes",
        dtype=np.object_,
        block="period",
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
    )
    stage: Optional[NDArray[np.float64]] = embedded_keystring(
        "STAGE",
        "nlakes",
        block="period",
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
    )
    rainfall: Optional[NDArray[np.float64]] = embedded_keystring(
        "RAINFALL",
        "nlakes",
        block="period",
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
    )
    evaporation: Optional[NDArray[np.float64]] = embedded_keystring(
        "EVAPORATION",
        "nlakes",
        block="period",
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
    )
    runoff: Optional[NDArray[np.float64]] = embedded_keystring(
        "RUNOFF",
        "nlakes",
        block="period",
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
    )
    inflow: Optional[NDArray[np.float64]] = embedded_keystring(
        "INFLOW",
        "nlakes",
        block="period",
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
    )
    withdrawal: Optional[NDArray[np.float64]] = embedded_keystring(
        "WITHDRAWAL",
        "nlakes",
        block="period",
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
    )
    rate: Optional[NDArray[np.float64]] = embedded_keystring(
        "RATE",
        "noutlets",
        block="period",
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
    )
    invert: Optional[NDArray[np.float64]] = embedded_keystring(
        "INVERT",
        "noutlets",
        block="period",
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
    )
    width: Optional[NDArray[np.float64]] = embedded_keystring(
        "WIDTH",
        "noutlets",
        block="period",
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
    )
    slope: Optional[NDArray[np.float64]] = embedded_keystring(
        "SLOPE",
        "noutlets",
        block="period",
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
    )
    rough: Optional[NDArray[np.float64]] = embedded_keystring(
        "ROUGH",
        "noutlets",
        block="period",
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
    )
    __block_col_maps__: ClassVar[dict] = {
        "packagedata": {
            "ifno": "packagedata_ifno",
            "strt": "strt",
            "nlakeconn": "nlakeconn",
            "aux": "aux",
            "boundname": "boundname",
        },
        "connectiondata": {
            "ifno": "connectiondata_ifno",
            "iconn": "iconn",
            "cellid": "cellid",
            "claktype": "claktype",
            "bedleak": "bedleak",
            "belev": "belev",
            "telev": "telev",
            "connlen": "connlen",
            "connwidth": "connwidth",
        },
        "tables": {
            "ifno": "tables_ifno",
            "tab6_filename": "tab6_filename",
        },
        "outlets": {
            "outletno": "outletno",
            "lakein": "lakein",
            "lakeout": "lakeout",
            "couttype": "couttype",
            "invert": "outlets_invert",
            "width": "outlets_width",
            "rough": "outlets_rough",
            "slope": "outlets_slope",
        },
    }

    def __attrs_post_init__(self):
        if self.auxiliary is not None:
            _aux = self.auxiliary
            self.naux = int(_aux.values.size) if hasattr(_aux, "values") else len(_aux)
        if self._packagedata is not None:
            self._set_block(
                "packagedata",
                "nlakes",
                True,
                {
                    "ifno": "packagedata_ifno",
                    "strt": "strt",
                    "nlakeconn": "nlakeconn",
                    "aux": "aux",
                    "boundname": "boundname",
                },
                self._packagedata,
            )
        if self._connectiondata is not None:
            self._set_block(
                "connectiondata",
                "nconnectiondata",
                False,
                {
                    "ifno": "connectiondata_ifno",
                    "iconn": "iconn",
                    "cellid": "cellid",
                    "claktype": "claktype",
                    "bedleak": "bedleak",
                    "belev": "belev",
                    "telev": "telev",
                    "connlen": "connlen",
                    "connwidth": "connwidth",
                },
                self._connectiondata,
            )
        if self._tables is not None:
            self._set_block(
                "tables",
                "ntables",
                True,
                {
                    "ifno": "tables_ifno",
                    "tab6_filename": "tab6_filename",
                },
                self._tables,
            )
        if self._outlets is not None:
            self._set_block(
                "outlets",
                "noutlets",
                True,
                {
                    "outletno": "outletno",
                    "lakein": "lakein",
                    "lakeout": "lakeout",
                    "couttype": "couttype",
                    "invert": "outlets_invert",
                    "width": "outlets_width",
                    "rough": "outlets_rough",
                    "slope": "outlets_slope",
                },
                self._outlets,
            )

    @property
    def packagedata(self):
        return self._get_block(
            {
                "ifno": "packagedata_ifno",
                "strt": "strt",
                "nlakeconn": "nlakeconn",
                "aux": "aux",
                "boundname": "boundname",
            }
        )

    @packagedata.setter
    def packagedata(self, value) -> None:
        self._set_block(
            "packagedata",
            "nlakes",
            True,
            {
                "ifno": "packagedata_ifno",
                "strt": "strt",
                "nlakeconn": "nlakeconn",
                "aux": "aux",
                "boundname": "boundname",
            },
            value,
        )

    @property
    def connectiondata(self):
        return self._get_block(
            {
                "ifno": "connectiondata_ifno",
                "iconn": "iconn",
                "cellid": "cellid",
                "claktype": "claktype",
                "bedleak": "bedleak",
                "belev": "belev",
                "telev": "telev",
                "connlen": "connlen",
                "connwidth": "connwidth",
            }
        )

    @connectiondata.setter
    def connectiondata(self, value) -> None:
        self._set_block(
            "connectiondata",
            "nconnectiondata",
            False,
            {
                "ifno": "connectiondata_ifno",
                "iconn": "iconn",
                "cellid": "cellid",
                "claktype": "claktype",
                "bedleak": "bedleak",
                "belev": "belev",
                "telev": "telev",
                "connlen": "connlen",
                "connwidth": "connwidth",
            },
            value,
        )

    @property
    def tables(self):
        return self._get_block(
            {
                "ifno": "tables_ifno",
                "tab6_filename": "tab6_filename",
            }
        )

    @tables.setter
    def tables(self, value) -> None:
        self._set_block(
            "tables",
            "ntables",
            True,
            {
                "ifno": "tables_ifno",
                "tab6_filename": "tab6_filename",
            },
            value,
        )

    @property
    def outlets(self):
        return self._get_block(
            {
                "outletno": "outletno",
                "lakein": "lakein",
                "lakeout": "lakeout",
                "couttype": "couttype",
                "invert": "outlets_invert",
                "width": "outlets_width",
                "rough": "outlets_rough",
                "slope": "outlets_slope",
            }
        )

    @outlets.setter
    def outlets(self, value) -> None:
        self._set_block(
            "outlets",
            "noutlets",
            True,
            {
                "outletno": "outletno",
                "lakein": "lakein",
                "lakeout": "lakeout",
                "couttype": "couttype",
                "invert": "outlets_invert",
                "width": "outlets_width",
                "rough": "outlets_rough",
                "slope": "outlets_slope",
            },
            value,
        )
