# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional, Union

import attrs
import numpy as np
from numpy.typing import NDArray

from flopy4.mf6._types import ARRAY_EQ, to_array
from flopy4.mf6.item import Item
from flopy4.mf6.package import Package
from flopy4.mf6.spec import child, field, path
from flopy4.mf6.utl.laktab import Laktab
from flopy4.mf6.utl.obs import Obs
from flopy4.mf6.utl.ts import Ts


@attrs.define(kw_only=True, slots=False)
class Lak(Package):
    dfn_name: ClassVar[str] = "gwf-lak"

    multi_package: ClassVar[bool] = True

    observations: ClassVar[dict[str, tuple[tuple[str, ...], ...]]] = {
        "conductance": (("index", "index"), ("index", "string"), ("string",)),
        "constant": (("index",), ("string",)),
        "evaporation": (("index",), ("string",)),
        "ext-inflow": (("index",), ("string",)),
        "ext-outflow": (("index",), ("string",)),
        "from-mvr": (("index",), ("string",)),
        "inflow": (("index",), ("string",)),
        "lak": (("index", "index"), ("index", "string"), ("string",)),
        "outlet": (("index",), ("string",)),
        "outlet-inflow": (("index",), ("string",)),
        "rainfall": (("index",), ("string",)),
        "runoff": (("index",), ("string",)),
        "stage": (("index",), ("string",)),
        "storage": (("index",), ("string",)),
        "surface-area": (("index",), ("string",)),
        "to-mvr": (("index",), ("string",)),
        "volume": (("index",), ("string",)),
        "wetted-area": (("index", "index"), ("index", "string"), ("string",)),
        "withdrawal": (("index",), ("string",)),
    }

    dim_exprs: ClassVar[dict[str, str]] = {
        "nlakes": "nlakes",
        "noutlets": "noutlets",
        "ntables": "ntables",
        "auxiliary": "len(auxiliary)",
        "nlakeconn": "sum(packagedata.nlakeconn)",
    }

    @attrs.define
    class Packagedata(Item):
        ifno: int = field(index=True, pk=True)
        strt: float = field()
        nlakeconn: int = field()
        aux: tuple[Union[float, str], ...] = field(
            default=(), array=True, shape=("auxiliary",), time_series=True, optional=True
        )
        boundname: Optional[str] = field(default=None, optional=True)

    @attrs.define
    class Connectiondata(Item):
        ifno: int = field(index=True, fk="packagedata.ifno")
        iconn: int = field(index=True)
        cellid: tuple = field(cellid=True)
        claktype: Union[float, str] = field()
        bedleak: Union[float, str] = field()
        belev: float = field()
        telev: float = field()
        connlen: float = field()
        connwidth: float = field()

    @attrs.define
    class Tables(Item):
        ifno: int = field(index=True, fk="packagedata.ifno")
        laktab: Laktab = child(keyword="tab6", direction="in", default=attrs.NOTHING)

    @attrs.define
    class Outlets(Item):
        outletno: int = field(index=True, pk=True)
        lakein: int = field(index=True, fk="packagedata.ifno")
        lakeout: int = field(index=True, fk="packagedata.ifno")
        couttype: Union[float, str] = field()
        invert: Union[float, str] = field(time_series=True)
        width: Union[float, str] = field(time_series=True)
        rough: Union[float, str] = field(time_series=True)
        slope: Union[float, str] = field(time_series=True)

    @attrs.define
    class Status(Item):
        _keyword: ClassVar[str] = "status"
        lakeno: int = field(index=True, fk="packagedata.ifno")
        status: Union[float, str] = field()

    @attrs.define
    class Stage(Item):
        _keyword: ClassVar[str] = "stage"
        lakeno: int = field(index=True, fk="packagedata.ifno")
        stage: Union[float, str] = field(time_series=True)

    @attrs.define
    class Rainfall(Item):
        _keyword: ClassVar[str] = "rainfall"
        lakeno: int = field(index=True, fk="packagedata.ifno")
        rainfall: Union[float, str] = field(time_series=True)

    @attrs.define
    class Evaporation(Item):
        _keyword: ClassVar[str] = "evaporation"
        lakeno: int = field(index=True, fk="packagedata.ifno")
        evaporation: Union[float, str] = field(time_series=True)

    @attrs.define
    class Runoff(Item):
        _keyword: ClassVar[str] = "runoff"
        lakeno: int = field(index=True, fk="packagedata.ifno")
        runoff: Union[float, str] = field(time_series=True)

    @attrs.define
    class Inflow(Item):
        _keyword: ClassVar[str] = "inflow"
        lakeno: int = field(index=True, fk="packagedata.ifno")
        inflow: Union[float, str] = field(time_series=True)

    @attrs.define
    class Withdrawal(Item):
        _keyword: ClassVar[str] = "withdrawal"
        lakeno: int = field(index=True, fk="packagedata.ifno")
        withdrawal: Union[float, str] = field(time_series=True)

    @attrs.define
    class Rate(Item):
        _keyword: ClassVar[str] = "rate"
        outletno: int = field(index=True, fk="outlets.outletno")
        rate: Union[float, str] = field(time_series=True)

    @attrs.define
    class Invert(Item):
        _keyword: ClassVar[str] = "invert"
        outletno: int = field(index=True, fk="outlets.outletno")
        invert: Union[float, str] = field(time_series=True)

    @attrs.define
    class Width(Item):
        _keyword: ClassVar[str] = "width"
        outletno: int = field(index=True, fk="outlets.outletno")
        width: Union[float, str] = field(time_series=True)

    @attrs.define
    class Slope(Item):
        _keyword: ClassVar[str] = "slope"
        outletno: int = field(index=True, fk="outlets.outletno")
        slope: Union[float, str] = field(time_series=True)

    @attrs.define
    class Rough(Item):
        _keyword: ClassVar[str] = "rough"
        outletno: int = field(index=True, fk="outlets.outletno")
        rough: Union[float, str] = field(time_series=True)

    @attrs.define
    class Auxiliary(Item):
        _keyword: ClassVar[str] = "auxiliary"
        lakeno: int = field(index=True, fk="packagedata.ifno")
        auxname: Union[float, str] = field()
        auxval: Union[float, str] = field(time_series=True)

    _StressPeriodDataItem = (
        Status
        | Stage
        | Rainfall
        | Evaporation
        | Runoff
        | Inflow
        | Withdrawal
        | Rate
        | Invert
        | Width
        | Slope
        | Rough
        | Auxiliary
    )

    auxiliary: Optional[NDArray[np.str_]] = field(
        default=None,
        converter=attrs.converters.optional(to_array(np.str_)),
        eq=ARRAY_EQ,
        block="options",
        optional=True,
        longname="keyword to specify aux variables",
    )
    boundnames: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    print_input: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="print input to listing file",
    )
    print_stage: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="print calculated stages to listing file",
    )
    print_flows: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="print calculated flows to listing file",
    )
    save_flows: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="save lake flows to budget file",
    )
    stage_file: Optional[Path] = path(
        default=None,
        converter=attrs.converters.optional(Path),
        block="options",
        optional=True,
        direction="out",
        keyword="stage",
    )
    budget_file: Optional[Path] = path(
        default=None,
        converter=attrs.converters.optional(Path),
        block="options",
        optional=True,
        direction="out",
        keyword="budget",
    )
    budgetcsv_file: Optional[Path] = path(
        default=None,
        converter=attrs.converters.optional(Path),
        block="options",
        optional=True,
        direction="out",
        keyword="budgetcsv",
    )
    package_convergence_file: Optional[Path] = path(
        default=None,
        converter=attrs.converters.optional(Path),
        block="options",
        optional=True,
        direction="out",
        keyword="package_convergence",
    )
    ts: list[Ts] = child(
        block="options", keyword="ts6", direction="in", default=attrs.Factory(list)
    )
    obs: Optional[Obs] = child(block="options", keyword="obs6", direction="in")
    mover: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    surfdep: Optional[float] = field(
        default=None,
        block="options",
        optional=True,
        longname="surface depression depth",
    )
    implicit: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="solve lake stage in the groundwater flow matrix",
    )
    maximum_iterations: Optional[int] = field(
        default=None,
        block="options",
        optional=True,
        longname="LAK Newton-Raphson iterations",
    )
    maximum_stage_change: Optional[float] = field(
        default=None,
        block="options",
        optional=True,
        longname="stage closure tolerance",
    )
    time_conversion: Optional[float] = field(
        default=None,
        block="options",
        optional=True,
        longname="time conversion factor",
    )
    length_conversion: Optional[float] = field(
        default=None,
        block="options",
        optional=True,
        longname="length conversion factor",
    )
    nlakes: Optional[int] = field(
        default=None,
        block="dimensions",
        longname="number of lakes",
    )
    noutlets: Optional[int] = field(
        default=None,
        block="dimensions",
        longname="number of outlets",
    )
    ntables: Optional[int] = field(
        default=None,
        block="dimensions",
        longname="number of tables",
    )
    packagedata: Optional[list[Packagedata]] = field(
        default=None,
        block="packagedata",
        dim="nlakes",
    )
    connectiondata: Optional[list[Connectiondata]] = field(
        default=None,
        block="connectiondata",
        write_if_empty=True,
    )
    tables: Optional[list[Tables]] = field(
        default=None,
        block="tables",
        dim="ntables",
    )
    outlets: Optional[list[Outlets]] = field(
        default=None,
        block="outlets",
        dim="noutlets",
    )
    _stress_period_data: Optional[dict[int, list[_StressPeriodDataItem]]] = field(
        alias="stress_period_data",
        default=None,
        repr=False,
        block="period",
        fill_forward=True,
    )


LakPackagedata = Lak.Packagedata
LakConnectiondata = Lak.Connectiondata
LakTables = Lak.Tables
LakOutlets = Lak.Outlets
LakStatus = Lak.Status
LakStage = Lak.Stage
LakRainfall = Lak.Rainfall
LakEvaporation = Lak.Evaporation
LakRunoff = Lak.Runoff
LakInflow = Lak.Inflow
LakWithdrawal = Lak.Withdrawal
LakRate = Lak.Rate
LakInvert = Lak.Invert
LakWidth = Lak.Width
LakSlope = Lak.Slope
LakRough = Lak.Rough
LakAuxiliary = Lak.Auxiliary
