# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional, Union

import attrs
import numpy as np
from numpy.typing import NDArray

from flopy4.mf6._types import ARRAY_EQ, to_array
from flopy4.mf6.item import Item
from flopy4.mf6.package import Package
from flopy4.mf6.spec import child, field, path
from flopy4.mf6.utl.obs import Obs
from flopy4.mf6.utl.ts import Ts


@attrs.define(kw_only=True, slots=False)
class Maw(Package):
    dfn_name: ClassVar[str] = "gwf-maw"

    multi_package: ClassVar[bool] = True

    observations: ClassVar[dict[str, tuple[tuple[str, ...], ...]]] = {
        "conductance": (("index", "index"), ("index", "string"), ("string",)),
        "constant": (("index",), ("string",)),
        "from-mvr": (("index",), ("string",)),
        "fw-conductance": (("index",), ("string",)),
        "fw-rate": (("index",), ("string",)),
        "fw-to-mvr": (("index",), ("string",)),
        "head": (("index",), ("string",)),
        "maw": (("index", "index"), ("index", "string"), ("string",)),
        "rate": (("index",), ("string",)),
        "rate-to-mvr": (("index",), ("string",)),
        "storage": (("index",), ("string",)),
    }

    @attrs.define
    class Packagedata(Item):
        ifno: int = field(index=True, pk=True)
        radius: float = field()
        bottom: float = field()
        strt: Union[float, str] = field(time_series=True)
        condeqn: Union[float, str] = field()
        ngwfnodes: int = field()
        aux: tuple[Union[float, str], ...] = field(
            default=(), array=True, shape=("auxiliary",), time_series=True, optional=True
        )
        boundname: Optional[str] = field(default=None, optional=True)

    @attrs.define
    class Connectiondata(Item):
        ifno: int = field(index=True, fk="packagedata.ifno")
        icon: int = field(index=True)
        cellid: tuple = field(cellid=True)
        scrn_top: float = field()
        scrn_bot: float = field()
        hk_skin: float = field()
        radius_skin: float = field()

    @attrs.define
    class Angledata(Item):
        ifno: int = field(index=True, fk="packagedata.ifno")
        icon: int = field(index=True)
        angle: float = field()
        conn_length: Optional[float] = field(default=None, optional=True)

    @attrs.define
    class Status(Item):
        _keyword: ClassVar[str] = "status"
        ifno: int = field(index=True, fk="packagedata.ifno")
        status: Union[float, str] = field()

    @attrs.define
    class ConnectionStatus(Item):
        _keyword: ClassVar[str] = "connection_status"
        ifno: int = field(index=True, fk="packagedata.ifno")
        icon: int = field(index=True)
        connstatus: Union[float, str] = field()

    @attrs.define
    class Bottom(Item):
        _keyword: ClassVar[str] = "bottom"
        ifno: int = field(index=True, fk="packagedata.ifno")
        bottom: float = field()

    @attrs.define
    class FlowingWell(Item):
        _keyword: ClassVar[str] = "flowing_well"
        ifno: int = field(index=True, fk="packagedata.ifno")
        fwelev: float = field()
        fwcond: float = field()
        fwrlen: float = field()

    @attrs.define
    class Rate(Item):
        _keyword: ClassVar[str] = "rate"
        ifno: int = field(index=True, fk="packagedata.ifno")
        rate: Union[float, str] = field(time_series=True)

    @attrs.define
    class WellHead(Item):
        _keyword: ClassVar[str] = "well_head"
        ifno: int = field(index=True, fk="packagedata.ifno")
        well_head: Union[float, str] = field(time_series=True)

    @attrs.define
    class HeadLimit(Item):
        _keyword: ClassVar[str] = "head_limit"
        ifno: int = field(index=True, fk="packagedata.ifno")
        head_limit: Union[float, str] = field()

    @attrs.define
    class Shutoff(Item):
        _keyword: ClassVar[str] = "shut_off"
        ifno: int = field(index=True, fk="packagedata.ifno")
        minrate: float = field()
        maxrate: float = field()

    @attrs.define
    class RateScaling(Item):
        _keyword: ClassVar[str] = "rate_scaling"
        ifno: int = field(index=True, fk="packagedata.ifno")
        pump_elevation: float = field()
        scaling_length: float = field()

    @attrs.define
    class Auxiliary(Item):
        _keyword: ClassVar[str] = "auxiliary"
        ifno: int = field(index=True, fk="packagedata.ifno")
        auxname: Union[float, str] = field()
        auxval: Union[float, str] = field(time_series=True)

    _StressPeriodDataItem = (
        Status
        | ConnectionStatus
        | Bottom
        | FlowingWell
        | Rate
        | WellHead
        | HeadLimit
        | Shutoff
        | RateScaling
        | Auxiliary
    )

    auxiliary: Optional[NDArray[np.str_]] = field(
        default=None,
        converter=attrs.converters.optional(to_array(np.str_)),
        eq=ARRAY_EQ,
        block="options",
        optional=True,
        longname="keyword to specify aux variables",
    )
    boundnames: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    print_input: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="print input to listing file",
    )
    print_head: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="print calculated heads to listing file",
    )
    print_flows: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="print calculated flows to listing file",
    )
    save_flows: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="save well flows to budget file",
    )
    head_file: Optional[Path] = path(
        default=None,
        converter=attrs.converters.optional(Path),
        block="options",
        optional=True,
        direction="out",
        keyword="head",
    )
    budget_file: Optional[Path] = path(
        default=None,
        converter=attrs.converters.optional(Path),
        block="options",
        optional=True,
        direction="out",
        keyword="budget",
    )
    budgetcsv_file: Optional[Path] = path(
        default=None,
        converter=attrs.converters.optional(Path),
        block="options",
        optional=True,
        direction="out",
        keyword="budgetcsv",
    )
    no_well_storage: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="deactivate well storage",
    )
    flow_correction: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="activate flow correction",
    )
    non_vertical_wells: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="activate non-vertical well connections",
    )
    flowing_wells: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="activate flowing wells",
    )
    shutdown_theta: Optional[float] = field(
        default=None,
        block="options",
        optional=True,
        longname="shutdown theta",
    )
    shutdown_kappa: Optional[float] = field(
        default=None,
        block="options",
        optional=True,
        longname="shutdown kappa",
    )
    mfrcsv_file: Optional[Path] = path(
        default=None,
        converter=attrs.converters.optional(Path),
        block="options",
        optional=True,
        direction="out",
        keyword="maw_flow_reduce_csv",
    )
    ts: list[Ts] = child(
        block="options", keyword="ts6", direction="in", default=attrs.Factory(list)
    )
    obs: Optional[Obs] = child(block="options", keyword="obs6", direction="in")
    mover: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    nmawwells: Optional[int] = field(
        default=None,
        block="dimensions",
        longname="number of MAW wells",
    )
    packagedata: Optional[list[Packagedata]] = field(
        default=None,
        block="packagedata",
        dim="nmawwells",
    )
    connectiondata: Optional[list[Connectiondata]] = field(
        default=None,
        block="connectiondata",
        write_if_empty=True,
    )
    angledata: Optional[list[Angledata]] = field(
        default=None,
        block="angledata",
    )
    _stress_period_data: Optional[dict[int, list[_StressPeriodDataItem]]] = field(
        alias="stress_period_data",
        default=None,
        repr=False,
        block="period",
        fill_forward=True,
    )


MawPackagedata = Maw.Packagedata
MawConnectiondata = Maw.Connectiondata
MawAngledata = Maw.Angledata
MawStatus = Maw.Status
MawConnectionStatus = Maw.ConnectionStatus
MawBottom = Maw.Bottom
MawFlowingWell = Maw.FlowingWell
MawRate = Maw.Rate
MawWellHead = Maw.WellHead
MawHeadLimit = Maw.HeadLimit
MawShutoff = Maw.Shutoff
MawRateScaling = Maw.RateScaling
MawAuxiliary = Maw.Auxiliary
