# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional, Union

import attrs

from flopy4.mf6._types import _optional_path
from flopy4.mf6.item import Item
from flopy4.mf6.package import Package
from flopy4.mf6.spec import field, path


@attrs.define(kw_only=True, slots=False)
class Mvr(Package):
    dfn_name: ClassVar[str] = "gwf-mvr"

    @attrs.define
    class Packages(Item):
        pname: Union[float, str] = field()
        mname: Optional[Union[float, str]] = field(default=None, optional=True)

    @attrs.define
    class StressPeriodData(Item):
        pname1: Union[float, str] = field()
        id1: int = field(index=True)
        pname2: Union[float, str] = field()
        id2: int = field(index=True)
        mvrtype: Union[float, str] = field()
        value: float = field()
        mname1: Optional[Union[float, str]] = field(default=None, optional=True)
        mname2: Optional[Union[float, str]] = field(default=None, optional=True)
        aux: tuple = ()

    print_input: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    print_flows: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    modelnames: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    budget_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="out",
    )
    budgetcsv_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="out",
    )
    maxmvr: Optional[int] = field(
        default=None,
        block="dimensions",
    )
    maxpackages: Optional[int] = field(
        default=None,
        block="dimensions",
    )
    packages: Optional[list[Packages]] = field(
        default=None,
        block="packages",
        auto_from="packages",
    )
    _stress_period_data: Optional[dict[int, list[StressPeriodData]]] = field(
        alias="stress_period_data",
        default=None,
        repr=False,
        block="period",
        fill_forward=True,
    )


MvrStressPeriodData = Mvr.StressPeriodData
MvrPackages = Mvr.Packages
