# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

import attrs
import numpy as np

from flopy4.mf6.package import Package
from flopy4.utils import to_path


@attrs.define(kw_only=True, slots=False)
class Mvr(Package):
    print_input: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    print_flows: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    modelnames: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    budget_file: Optional[Path] = attrs.field(
        default=None,
        converter=lambda v: None if v is None else to_path(v),
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "fileout",
        },
    )
    budgetcsv_file: Optional[Path] = attrs.field(
        default=None,
        converter=lambda v: None if v is None else to_path(v),
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "fileout",
        },
    )
    maxmvr: Optional[int] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "dimensions",
            "dfn_type": "integer",
        },
    )
    maxpackages: Optional[int] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "dimensions",
            "dfn_type": "integer",
        },
    )
    packages: Optional[np.recarray] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "packages",
            "schema": "__packages_schema__",
            "auto_from": "packages",
        },
    )
    _stress_period_data: Optional[dict[int, np.recarray]] = attrs.field(
        alias="stress_period_data",
        default=None,
        repr=False,
        metadata={
            "dfn_block": "period",
            "schema": "__period_schema__",
            "fill_forward": True,
        },
    )
    __packages_schema__: ClassVar[list[dict]] = [
        {
            "name": "mname",
            "dfn_type": "string",
            "role": "value",
            "dtype": "np.object_",
        },
        {
            "name": "pname",
            "dfn_type": "string",
            "role": "value",
            "dtype": "np.object_",
        },
    ]

    __period_schema__: ClassVar[list[dict]] = [
        {
            "name": "cellid",
            "dfn_type": "integer",
            "role": "cellid",
            "shape": "ncelldim",
            "optional": False,
        },
        {
            "name": "mname1",
            "dfn_type": "string",
            "optional": True,
            "role": "value",
        },
        {
            "name": "pname1",
            "dfn_type": "string",
            "optional": False,
            "role": "value",
        },
        {
            "name": "id1",
            "dfn_type": "integer",
            "optional": False,
            "role": "value",
        },
        {
            "name": "mname2",
            "dfn_type": "string",
            "optional": True,
            "role": "value",
        },
        {
            "name": "pname2",
            "dfn_type": "string",
            "optional": False,
            "role": "value",
        },
        {
            "name": "id2",
            "dfn_type": "integer",
            "optional": False,
            "role": "value",
        },
        {
            "name": "mvrtype",
            "dfn_type": "string",
            "optional": False,
            "role": "value",
        },
        {
            "name": "value",
            "dfn_type": "double",
            "optional": False,
            "role": "value",
        },
    ]

    packages_dtype: np.dtype = attrs.field(init=False, factory=lambda: np.dtype([]))
    period_dtype: np.dtype = attrs.field(init=False, factory=lambda: np.dtype([]))

    _DTYPE_MAP: ClassVar[dict] = {
        "integer": np.int64,
        "double": np.float64,
        "double precision": np.float64,
        "string": np.object_,
        "keyword": np.object_,
        "object": np.object_,
    }

    def __attrs_post_init__(self) -> None:
        _aux_tmp = getattr(self, "auxiliary", None)
        naux = len(_aux_tmp) if _aux_tmp is not None else 0
        ncelldim = self._compute_ncelldim()
        _packages_f: list[tuple] = []
        for _col in self.__packages_schema__:
            _role = _col.get("role", "value")
            _dt = _col.get("dtype")
            _dt = (
                eval(_dt)
                if _dt
                else self._DTYPE_MAP.get(_col.get("dfn_type", "string"), np.object_)
            )
            if _role == "cellid":
                _packages_f.append((_col["name"], np.int64, (ncelldim,)))
            elif _role == "feature_id":
                _packages_f.append((_col["name"], np.int64))
            elif _role == "boundname":
                if getattr(self, "boundnames", False):
                    _packages_f.append((_col["name"], np.object_))
            else:
                _packages_f.append((_col["name"], _dt))
        if "packages" == "packagedata":
            for _i in range(naux):
                _packages_f.append((f"aux{_i}", np.object_))
        self.packages_dtype = np.dtype(_packages_f)
        _raw_packages = getattr(self, "packages", None)
        if _raw_packages is not None:
            self.packages = self._coerce_to_recarray(_raw_packages, self.packages_dtype)
        if getattr(self, "packages", None) is not None and getattr(self, "npackagess", 0) == 0:
            object.__setattr__(self, "npackagess", len(getattr(self, "packages")))
        _has_keystring = any(
            col.get("role") in ("keystring", "keystring_value") for col in self.__period_schema__
        )
        fields: list[tuple] = []
        for col in self.__period_schema__:
            role = col.get("role", "value")
            if role == "cellid":
                fields.append((col["name"], np.int64, (ncelldim,)))
            elif role in ("keystring", "keystring_value"):
                fields.append((col["name"], np.object_))
            elif col.get("time_series"):
                fields.append((col["name"], np.object_))
            elif not col.get("optional", False):
                _dt = col.get("dtype")
                _col_dt = (
                    eval(_dt)
                    if _dt
                    else self._DTYPE_MAP.get(col.get("dfn_type", "double"), np.float64)
                )
                fields.append((col["name"], _col_dt))
        if not _has_keystring:
            for i in range(naux):
                fields.append((f"aux{i}", np.object_))
            if getattr(self, "boundnames", False):
                fields.append(("boundname", np.object_))
        self.period_dtype = np.dtype(fields)
        if self._stress_period_data is not None:
            self._stress_period_data = {
                kper: self._coerce_to_recarray(rows, self.period_dtype)
                for kper, rows in self._stress_period_data.items()
            }
        _spd = self._stress_period_data
        if _spd and getattr(self, "maxbound", None) == 0:
            self.maxbound = max(len(v) for v in _spd.values())
        super().__attrs_post_init__()

    @property  # type: ignore[override]
    def stress_period_data(self) -> "Optional[dict[int, np.recarray]]":
        return self._stress_period_data

    @stress_period_data.setter
    def stress_period_data(self, value) -> None:
        self._stress_period_data = value

    def to_dataframe(self) -> "pandas.DataFrame":  # type: ignore[name-defined]
        """Return stress period data as a tidy pd.DataFrame. Zero cost if not called."""
        import pandas as pd

        _spd = self._stress_period_data
        if not _spd:
            return pd.DataFrame()
        frames = []
        for kper in sorted(_spd):
            arr = _spd[kper]
            rows = {}
            for nm in arr.dtype.names or ():
                col = arr[nm]
                rows[nm] = [tuple(v) for v in col] if col.ndim > 1 else col.tolist()
            df = pd.DataFrame(rows)
            df.insert(0, "kper", kper)
            frames.append(df)
        return pd.concat(frames, ignore_index=True)
