# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional, Union

import attrs
import numpy as np

from flopy4.mf6._types import _optional_path
from flopy4.mf6.package import Package
from flopy4.mf6.schema import Column, Schema
from flopy4.mf6.spec import field, path


@attrs.define(kw_only=True, slots=False)
class Mvr(Package):
    print_input: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    print_flows: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    modelnames: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    budget_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        inout="fileout",
    )
    budgetcsv_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        inout="fileout",
    )
    maxmvr: Optional[int] = field(
        default=None,
        block="dimensions",
    )
    maxpackages: Optional[int] = field(
        default=None,
        block="dimensions",
    )
    packages: Optional[np.recarray] = field(
        default=None,
        block="packages",
        schema="__packages_schema__",
        auto_from="packages",
    )
    _stress_period_data: Optional[dict[int, np.recarray]] = field(
        alias="stress_period_data",
        default=None,
        repr=False,
        block="period",
        schema="__period_schema__",
        fill_forward=True,
    )

    class _PackagesSchema(Schema):
        mname = Column("mname", role="value", dfn_type="string", optional=True, dtype="np.object_")
        pname = Column("pname", role="value", dfn_type="string", dtype="np.object_")

    __packages_schema__: ClassVar[type[Schema]] = _PackagesSchema

    @attrs.define
    class PackagesRow:
        pname: Union[float, str]
        mname: Optional[Union[float, str]] = None

        def __iter__(self):
            yield self.pname
            yield self.mname

    @attrs.define
    class Row:
        pname1: Union[float, str]
        id1: int
        pname2: Union[float, str]
        id2: int
        mvrtype: Union[float, str]
        value: float
        aux: tuple = ()
        mname1: Optional[Union[float, str]] = None
        mname2: Optional[Union[float, str]] = None

        def __iter__(self):
            yield self.pname1
            yield self.id1
            yield self.pname2
            yield self.id2
            yield self.mvrtype
            yield self.value
            yield from self.aux
            yield self.mname1
            yield self.mname2

    class _PeriodSchema(Schema):
        mname1 = Column(
            "mname1",
            role="value",
            dfn_type="string",
            optional=True,
            dtype="np.object_",
        )
        pname1 = Column("pname1", role="value", dfn_type="string", dtype="np.object_")
        id1 = Column("id1", role="value", dfn_type="integer")
        mname2 = Column(
            "mname2",
            role="value",
            dfn_type="string",
            optional=True,
            dtype="np.object_",
        )
        pname2 = Column("pname2", role="value", dfn_type="string", dtype="np.object_")
        id2 = Column("id2", role="value", dfn_type="integer")
        mvrtype = Column("mvrtype", role="value", dfn_type="string", dtype="np.object_")
        value = Column("value", role="value", dfn_type="double")

    __period_schema__: ClassVar[type[Schema]] = _PeriodSchema

    packages_dtype: np.dtype = attrs.field(init=False, factory=lambda: np.dtype([]))
    period_dtype: np.dtype = attrs.field(init=False, factory=lambda: np.dtype([]))


MvrRow = Mvr.Row
MvrPackagesRow = Mvr.PackagesRow
