# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional, TypeAlias, Union

import attrs
from numpy.typing import NDArray

from flopy4.mf6.package import Package
from flopy4.mf6.record import Record
from flopy4.utils import to_path

try:
    import dask.array as da

    ArrayLike: TypeAlias = Union[NDArray, da.Array]
except ImportError:
    ArrayLike: TypeAlias = NDArray  # type: ignore[misc, no-redef]  # dask optional


@attrs.define(kw_only=True, slots=False)
class Npf(Package):
    @attrs.define
    class Cvoptions(Record):
        _keyword: ClassVar[str] = "variablecv"
        dewatered: Optional[bool] = attrs.field(default=None)

    @attrs.define
    class Rewet(Record):
        _keyword: ClassVar[str] = "rewet"
        wetfct: float = attrs.field(metadata={"tagged": True})
        iwetit: int = attrs.field(metadata={"tagged": True})
        ihdwet: int = attrs.field(metadata={"tagged": True})

    @attrs.define
    class Xt3doptions(Record):
        _keyword: ClassVar[str] = "xt3d"
        rhs: Optional[bool] = attrs.field(default=None)

    save_flows: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    print_flows: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    alternative_cell_averaging: Optional[str] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "options",
            "dfn_type": "string",
            "optional": True,
        },
    )
    thickstrt: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    cvoptions: Optional[Cvoptions] = attrs.field(default=None, metadata={"dfn_block": "options"})
    perched: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    rewet: Optional[Rewet] = attrs.field(default=None, metadata={"dfn_block": "options"})
    xt3doptions: Optional[Xt3doptions] = attrs.field(
        default=None, metadata={"dfn_block": "options"}
    )
    highest_cell_saturation: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    save_specific_discharge: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    save_saturation: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    k22overk: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    k33overk: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    tvk_file: Optional[Path] = attrs.field(
        default=None,
        converter=lambda v: None if v is None else to_path(v),
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "filein",
        },
    )
    export_array_ascii: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    export_array_netcdf: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    dev_no_newton: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    dev_omega: Optional[float] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "options",
            "dfn_type": "double",
            "optional": True,
        },
    )
    icelltype: ArrayLike = attrs.field(
        default=0,
        metadata={
            "dfn_block": "griddata",
            "dfn_type": "integer",
            "shape": ("nodes",),
            "layered": True,
            "chunk_axis": "nlay",
            "netcdf": True,
        },
    )  # type: ignore[assignment]
    k: ArrayLike = attrs.field(
        default=1.0,
        metadata={
            "dfn_block": "griddata",
            "dfn_type": "double",
            "shape": ("nodes",),
            "layered": True,
            "chunk_axis": "nlay",
            "netcdf": True,
        },
    )  # type: ignore[assignment]
    k22: Optional[ArrayLike] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "griddata",
            "dfn_type": "double",
            "shape": ("nodes",),
            "layered": True,
            "chunk_axis": "nlay",
            "netcdf": True,
            "optional": True,
        },
    )
    k33: Optional[ArrayLike] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "griddata",
            "dfn_type": "double",
            "shape": ("nodes",),
            "layered": True,
            "chunk_axis": "nlay",
            "netcdf": True,
            "optional": True,
        },
    )
    angle1: Optional[ArrayLike] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "griddata",
            "dfn_type": "double",
            "shape": ("nodes",),
            "layered": True,
            "chunk_axis": "nlay",
            "netcdf": True,
            "optional": True,
        },
    )
    angle2: Optional[ArrayLike] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "griddata",
            "dfn_type": "double",
            "shape": ("nodes",),
            "layered": True,
            "chunk_axis": "nlay",
            "netcdf": True,
            "optional": True,
        },
    )
    angle3: Optional[ArrayLike] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "griddata",
            "dfn_type": "double",
            "shape": ("nodes",),
            "layered": True,
            "chunk_axis": "nlay",
            "netcdf": True,
            "optional": True,
        },
    )
    wetdry: Optional[ArrayLike] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "griddata",
            "dfn_type": "double",
            "shape": ("nodes",),
            "layered": True,
            "chunk_axis": "nlay",
            "netcdf": True,
            "optional": True,
        },
    )
