# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

import attrs

from flopy4.mf6._types import FloatArrayLike, IntArrayLike, _optional_path
from flopy4.mf6.package import Package
from flopy4.mf6.record import Record
from flopy4.mf6.spec import field, path


@attrs.define(kw_only=True, slots=False)
class Npf(Package):
    dfn_name: ClassVar[str] = "gwf-npf"

    @attrs.define
    class Cvoptions(Record):
        _keyword: ClassVar[str] = "variablecv"
        dewatered: Optional[bool] = attrs.field(default=None, metadata={"tagged": True})

    @attrs.define
    class Rewet(Record):
        _keyword: ClassVar[str] = "rewet"
        wetfct: float = attrs.field(metadata={"tagged": True})
        iwetit: int = attrs.field(metadata={"tagged": True})
        ihdwet: int = attrs.field(metadata={"tagged": True})

    @attrs.define
    class Xt3doptions(Record):
        _keyword: ClassVar[str] = "xt3d"
        rhs: Optional[bool] = attrs.field(default=None, metadata={"tagged": True})

    save_flows: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="keyword to save NPF flows",
    )
    print_flows: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="keyword to print NPF flows to listing file",
    )
    alternative_cell_averaging: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
        longname="conductance weighting option",
    )
    thickstrt: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="keyword to activate THICKSTRT option",
    )
    cvoptions: Optional[Cvoptions] = field(
        default=None,
        block="options",
    )
    perched: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="keyword to activate PERCHED option",
    )
    rewet: Optional[Rewet] = field(
        default=None,
        block="options",
    )
    xt3doptions: Optional[Xt3doptions] = field(
        default=None,
        block="options",
    )
    highest_cell_saturation: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="keyword to activate HIGHEST_CELL_SATURATION option",
    )
    save_specific_discharge: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="keyword to save specific discharge",
    )
    save_saturation: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="keyword to save saturation",
    )
    k22overk: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="keyword to indicate that specified K22 is a ratio",
    )
    k33overk: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="keyword to indicate that specified K33 is a ratio",
    )
    tvk_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="in",
    )
    export_array_ascii: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="export array variables to layered ascii files.",
    )
    export_array_netcdf: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="export array variables to netcdf output files.",
    )
    icelltype: Optional[IntArrayLike] = field(
        default=0,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
        optional=True,
        longname="confined or convertible indicator",
    )  # type: ignore[assignment]
    k: Optional[FloatArrayLike] = field(
        default=1.0,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
        optional=True,
        longname="hydraulic conductivity (L/T)",
    )  # type: ignore[assignment]
    k22: Optional[FloatArrayLike] = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
        optional=True,
        longname="hydraulic conductivity of second ellipsoid axis",
    )
    k33: Optional[FloatArrayLike] = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
        optional=True,
        longname="hydraulic conductivity of third ellipsoid axis (L/T)",
    )
    angle1: Optional[FloatArrayLike] = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
        optional=True,
        longname="first anisotropy rotation angle (degrees)",
    )
    angle2: Optional[FloatArrayLike] = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
        optional=True,
        longname="second anisotropy rotation angle (degrees)",
    )
    angle3: Optional[FloatArrayLike] = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
        optional=True,
        longname="third anisotropy rotation angle (degrees)",
    )
    wetdry: Optional[FloatArrayLike] = field(
        default=None,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
        optional=True,
        longname="wetdry threshold and factor",
    )
