# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

import attrs

from flopy4.mf6._types import _optional_path
from flopy4.mf6.package import Package
from flopy4.mf6.record import Record


@attrs.define(kw_only=True, slots=False)
class Oc(Package):
    @attrs.define
    class Headprint(Record):
        _keyword: ClassVar[str] = "head"
        _extra_tokens: ClassVar[tuple[str, ...]] = ("PRINT_FORMAT",)
        format_: str = attrs.field()
        columns: Optional[int] = attrs.field(default=None, metadata={"tagged": True})
        width: Optional[int] = attrs.field(default=None, metadata={"tagged": True})
        digits: Optional[int] = attrs.field(default=None, metadata={"tagged": True})

    budget_file: Optional[Path] = attrs.field(
        default=None,
        converter=_optional_path,
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "fileout",
        },
    )
    budgetcsv_file: Optional[Path] = attrs.field(
        default=None,
        converter=_optional_path,
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "fileout",
        },
    )
    head_file: Optional[Path] = attrs.field(
        default=None,
        converter=_optional_path,
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "fileout",
        },
    )
    headprint: Optional[Headprint] = attrs.field(default=None, metadata={"dfn_block": "options"})
    save_head: Optional[dict[int, list[str]]] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "period",
            "dfn_type": "string",
            "oc_action": "save",
            "oc_rtype": "head",
        },
    )
    save_budget: Optional[dict[int, list[str]]] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "period",
            "dfn_type": "string",
            "oc_action": "save",
            "oc_rtype": "budget",
        },
    )
    print_head: Optional[dict[int, list[str]]] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "period",
            "dfn_type": "string",
            "oc_action": "print",
            "oc_rtype": "head",
        },
    )
    print_budget: Optional[dict[int, list[str]]] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "period",
            "dfn_type": "string",
            "oc_action": "print",
            "oc_rtype": "budget",
        },
    )
