# autogenerated file, do not modify
from typing import ClassVar, Optional, Union

import attrs
import numpy as np
from numpy.typing import NDArray

from flopy4.mf6._types import ARRAY_EQ, to_str_array
from flopy4.mf6.item import Item
from flopy4.mf6.package import Package
from flopy4.mf6.spec import child, field
from flopy4.mf6.utl.obs import Obs
from flopy4.mf6.utl.ts import Ts


@attrs.define(kw_only=True, slots=False)
class Rch(Package):
    dfn_name: ClassVar[str] = "gwf-rch"

    multi_package: ClassVar[bool] = True

    observations: ClassVar[dict[str, tuple[tuple[str, ...], ...]]] = {
        "rch": (("cellid",), ("string",)),
    }

    @attrs.define
    class StressPeriodData(Item):
        cellid: tuple = field(cellid=True)
        recharge: Union[float, str] = field(time_series=True)
        aux: tuple[Union[float, str], ...] = field(
            default=(), array=True, shape=("auxiliary",), time_series=True, optional=True
        )
        boundname: Optional[str] = field(default=None, optional=True)

    fixed_cell: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="if cell is dry do not apply recharge to underlying cell",
    )
    auxiliary: Optional[NDArray[np.str_]] = field(
        default=None,
        converter=to_str_array,
        eq=ARRAY_EQ,
        block="options",
        optional=True,
        longname="keyword to specify aux variables",
    )
    auxmultname: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
        longname="name of auxiliary variable for multiplier",
    )
    boundnames: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    print_input: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="print input to listing file",
    )
    print_flows: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="print recharge rates to listing file",
    )
    save_flows: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="save recharge to budget file",
    )
    ts: list[Ts] = child(
        block="options", keyword="ts6", direction="in", default=attrs.Factory(list)
    )
    obs: Optional[Obs] = child(block="options", keyword="obs6", direction="in")
    _stress_period_data: Optional[dict[int, list[StressPeriodData]]] = field(
        alias="stress_period_data",
        default=None,
        repr=False,
        block="period",
        fill_forward=True,
    )

    @property
    def maxbound(self) -> int:
        """Maximum number of active entries in any stress period.

        Computed live from `stress_period_data`'s row counts -- not
        stored or independently settable.
        """
        if not self.stress_period_data:
            return 0
        return max(len(v) for v in self.stress_period_data.values())


RchStressPeriodData = Rch.StressPeriodData
