# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

import attrs
import numpy as np

from flopy4.mf6._types import _optional_path
from flopy4.mf6.package import Package
from flopy4.mf6.schema import Column, Schema


@attrs.define(kw_only=True, slots=False)
class Rch(Package):
    multi_package: ClassVar[bool] = True

    fixed_cell: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    auxiliary: Optional[list[str]] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "options",
            "dfn_type": "string",
            "shape": (),
            "optional": True,
        },
    )
    auxmultname: Optional[str] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "options",
            "dfn_type": "string",
            "optional": True,
        },
    )
    boundnames: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    print_input: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    print_flows: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    save_flows: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    ts_file: Optional[Path] = attrs.field(
        default=None,
        converter=_optional_path,
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "filein",
        },
    )
    obs_file: Optional[Path] = attrs.field(
        default=None,
        converter=_optional_path,
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "filein",
        },
    )
    maxbound: Optional[int] = attrs.field(
        default=0,
        metadata={
            "dfn_block": "dimensions",
            "dfn_type": "integer",
            "auto_from": "stress_period_data",
        },
    )
    _stress_period_data: Optional[dict[int, np.recarray]] = attrs.field(
        alias="stress_period_data",
        default=None,
        repr=False,
        metadata={
            "dfn_block": "period",
            "schema": "__period_schema__",
            "fill_forward": True,
        },
    )

    class _PeriodSchema(Schema):
        cellid = Column("cellid", role="cellid", dfn_type="integer", shape="ncelldim")
        recharge = Column(
            "recharge",
            role="value",
            dfn_type="double",
            time_series=True,
            dtype="np.object_",
        )
        boundname = Column(
            "boundname",
            role="boundname",
            dfn_type="string",
            optional=True,
            dtype="np.object_",
        )

    __period_schema__: ClassVar[type[Schema]] = _PeriodSchema

    period_dtype: np.dtype = attrs.field(init=False, factory=lambda: np.dtype([]))
