# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

import attrs
import numpy as np
from numpy.typing import NDArray

from flopy4.mf6._types import ARRAY_EQ, FloatArrayLike, IntArrayLike, to_array, to_list
from flopy4.mf6.package import Package
from flopy4.mf6.spec import field, path


@attrs.define(kw_only=True, slots=False)
class Rcha(Package):
    dfn_name: ClassVar[str] = "gwf-rcha"

    multi_package: ClassVar[bool] = True

    readasarrays: bool = field(
        default=True,
        block="options",
        longname="use array-based input",
    )
    fixed_cell: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="if cell is dry do not apply recharge to underlying cell",
    )
    auxiliary: Optional[NDArray[np.str_]] = field(
        default=None,
        converter=attrs.converters.optional(to_array(np.str_)),
        eq=ARRAY_EQ,
        block="options",
        optional=True,
        longname="keyword to specify aux variables",
    )
    auxmultname: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
        longname="name of auxiliary variable for multiplier",
    )
    print_input: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="print input to listing file",
    )
    print_flows: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="print recharge rates to listing file",
    )
    save_flows: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="save RCHA flows to budget file",
    )
    tas_file: Optional[list[Path]] = path(
        default=None,
        converter=attrs.converters.optional(to_list(Path)),
        block="options",
        optional=True,
        direction="in",
        keyword="tas6",
    )
    obs_file: Optional[Path] = path(
        default=None,
        converter=attrs.converters.optional(Path),
        block="options",
        optional=True,
        direction="in",
        keyword="obs6",
    )
    export_array_netcdf: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="export array variables to netcdf output files.",
    )
    irch: Optional[IntArrayLike] = field(
        default=None,
        block="period",
        shape=("ncpl",),
        layered=False,
        index=True,
        netcdf=True,
        fill_forward=True,
    )
    recharge: Optional[FloatArrayLike] = field(
        default=None,
        block="period",
        shape=("ncpl",),
        layered=False,
        netcdf=True,
        fill_forward=True,
    )
    aux: Optional[dict[str, FloatArrayLike]] = field(
        default=None,
        block="period",
        shape=("ncpl",),
        layered=False,
        netcdf=True,
        fill_forward=True,
        fk="options.auxiliary",
    )
