# autogenerated file, do not modify
# ruff: noqa: E501
from pathlib import Path
from typing import ClassVar, Optional

import numpy as np
from attrs import Converter
from numpy.typing import NDArray
from xattree import xattree

from flopy4.mf6.constants import LENBOUNDNAME
from flopy4.mf6.converter import structure_array
from flopy4.mf6.package import Package
from flopy4.mf6.spec import array, dim, field, path
from flopy4.mf6.utils.grid import update_maxbound
from flopy4.utils import to_path


@xattree(kw_only=True)
class Riv(Package):
    multi_package: ClassVar[bool] = True

    auxiliary: Optional[list[str]] = array(
        block="options", default=None, longname="keyword to specify aux variables"
    )
    auxmultname: Optional[str] = field(
        block="options", default=None, longname="name of auxiliary variable for multiplier"
    )
    boundnames: bool = field(block="options", default=False)
    print_input: bool = field(
        block="options", default=False, longname="print input to listing file"
    )
    print_flows: bool = field(
        block="options", default=False, longname="print calculated flows to listing file"
    )
    save_flows: bool = field(
        block="options", default=False, longname="save riv flows to budget file"
    )
    ts_file: Optional[Path] = path(block="options", default=None, converter=to_path, inout="filein")
    obs_file: Optional[Path] = path(
        block="options", default=None, converter=to_path, inout="filein"
    )
    mover: bool = field(block="options", default=False)
    maxbound: Optional[int] = field(
        block="dimensions", default=None, init=False, longname="maximum number of rivers"
    )
    naux: Optional[int] = dim(block="__dim__", coord=False, default=None)
    stage: Optional[NDArray[np.float64]] = array(
        block="period",
        dims=("nper", "nodes"),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        on_setattr=update_maxbound,
        longname="river stage",
    )
    cond: Optional[NDArray[np.float64]] = array(
        block="period",
        dims=("nper", "nodes"),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        on_setattr=update_maxbound,
        longname="river conductance",
    )
    rbot: Optional[NDArray[np.float64]] = array(
        block="period",
        dims=("nper", "nodes"),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        on_setattr=update_maxbound,
        longname="river bottom elevation",
    )
    aux: Optional[NDArray[np.float64]] = array(
        block="period",
        dims=("nper", "nodes", "naux"),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        on_setattr=update_maxbound,
        longname="auxiliary variables",
    )
    boundname: Optional[NDArray[np.str_]] = array(
        dtype=f"<U{LENBOUNDNAME}",
        block="period",
        dims=("nper", "nodes"),
        default=None,
        converter=Converter(structure_array, takes_self=True, takes_field=True),
        on_setattr=update_maxbound,
        longname="river name",
    )
    __period_col_maps__: ClassVar[dict] = {
        "stage": "stage",
        "cond": "cond",
        "rbot": "rbot",
    }
