# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

import attrs

from flopy4.mf6._types import FloatArrayLike, _optional_path
from flopy4.mf6.package import Package
from flopy4.mf6.spec import field, path


@attrs.define(kw_only=True, slots=False)
class Rivg(Package):
    dfn_name: ClassVar[str] = "gwf-rivg"

    multi_package: ClassVar[bool] = True

    readarraygrid: bool = field(
        default=True,
        block="options",
    )
    auxiliary: Optional[list[str]] = field(
        default=None,
        block="options",
        optional=True,
    )
    auxmultname: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
    )
    print_input: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    print_flows: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    save_flows: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    obs_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        inout="filein",
    )
    mover: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    export_array_netcdf: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    maxbound: Optional[int] = field(
        default=0,
        block="dimensions",
        optional=True,
        auto_from="stress_period_data",
    )
    stage: Optional[FloatArrayLike] = field(
        default=None,
        block="period",
        reader="readarray",
        layered=True,
    )
    cond: Optional[FloatArrayLike] = field(
        default=None,
        block="period",
        reader="readarray",
        layered=True,
    )
    rbot: Optional[FloatArrayLike] = field(
        default=None,
        block="period",
        reader="readarray",
        layered=True,
    )
    aux: Optional[FloatArrayLike] = field(
        default=None,
        block="period",
        reader="readarray",
        layered=True,
    )
