# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

import attrs

from flopy4.mf6._types import FloatArrayLike, IntArrayLike, _optional_path
from flopy4.mf6.item import Item
from flopy4.mf6.package import Package
from flopy4.mf6.spec import field, path


@attrs.define(kw_only=True, slots=False)
class Sto(Package):
    dfn_name: ClassVar[str] = "gwf-sto"

    @attrs.define
    class StressPeriodData(Item):
        storage: str = field()

    save_flows: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    storagecoefficient: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    ss_confined_only: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    tvs_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        direction="in",
    )
    export_array_ascii: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    export_array_netcdf: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    iconvert: IntArrayLike = field(
        default=0,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
    )  # type: ignore[assignment]
    ss: FloatArrayLike = field(
        default=1e-05,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
    )  # type: ignore[assignment]
    sy: FloatArrayLike = field(
        default=0.15,
        block="griddata",
        shape=("nodes",),
        netcdf=True,
    )  # type: ignore[assignment]
    _stress_period_data: Optional[dict[int, list[StressPeriodData]]] = field(
        alias="stress_period_data",
        default=None,
        repr=False,
        block="period",
        fill_forward=True,
    )

StoStressPeriodData = Sto.StressPeriodData
