# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

import attrs
import numpy as np

from flopy4.mf6._types import ArrayLike, _optional_path
from flopy4.mf6.package import Package
from flopy4.mf6.schema import Column, Schema


@attrs.define(kw_only=True, slots=False)
class Sto(Package):
    save_flows: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    storagecoefficient: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    ss_confined_only: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    tvs_file: Optional[Path] = attrs.field(
        default=None,
        converter=_optional_path,
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "filein",
        },
    )
    export_array_ascii: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    export_array_netcdf: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    dev_original_specific_storage: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    dev_oldstorageformulation: bool = attrs.field(
        default=False,
        metadata={
            "dfn_block": "options",
            "dfn_type": "keyword",
            "optional": True,
        },
    )
    iconvert: ArrayLike = attrs.field(
        default=0,
        metadata={
            "dfn_block": "griddata",
            "dfn_type": "integer",
            "shape": ("nodes",),
            "layered": True,
            "chunk_axis": "nlay",
            "netcdf": True,
        },
    )  # type: ignore[assignment]
    ss: ArrayLike = attrs.field(
        default="1.e-5",
        metadata={
            "dfn_block": "griddata",
            "dfn_type": "double",
            "shape": ("nodes",),
            "layered": True,
            "chunk_axis": "nlay",
            "netcdf": True,
        },
    )  # type: ignore[assignment]
    sy: ArrayLike = attrs.field(
        default="0.15",
        metadata={
            "dfn_block": "griddata",
            "dfn_type": "double",
            "shape": ("nodes",),
            "layered": True,
            "chunk_axis": "nlay",
            "netcdf": True,
        },
    )  # type: ignore[assignment]
    _stress_period_data: Optional[dict[int, np.recarray]] = attrs.field(
        alias="stress_period_data",
        default=None,
        repr=False,
        metadata={
            "dfn_block": "period",
            "schema": "__period_schema__",
            "fill_forward": True,
        },
    )

    class _PeriodSchema(Schema):
        storagestate = Column("storagestate", role="keystring", dfn_type="keyword")

    __period_schema__: ClassVar[type[Schema]] = _PeriodSchema

    period_dtype: np.dtype = attrs.field(init=False, factory=lambda: np.dtype([]))
