# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional, Union

import attrs
import numpy as np
from numpy.typing import NDArray

from flopy4.mf6._types import to_array, to_list
from flopy4.mf6.item import Item
from flopy4.mf6.package import Package
from flopy4.mf6.spec import field, path


@attrs.define(kw_only=True, slots=False)
class Uzf(Package):
    dfn_name: ClassVar[str] = "gwf-uzf"

    multi_package: ClassVar[bool] = True

    @attrs.define
    class Packagedata(Item):
        ifno: int = field(index=True, pk=True)
        cellid: tuple = field(cellid=True)
        landflag: int = field()
        ivertcon: int = field(index=True, fk="packagedata.ifno")
        surfdep: float = field()
        vks: float = field()
        thtr: float = field()
        thts: float = field()
        thti: float = field()
        eps: float = field()
        boundname: Optional[str] = field(default=None, optional=True)

    @attrs.define
    class StressPeriodData(Item):
        ifno: int = field(index=True, fk="packagedata.ifno")
        finf: Union[float, str] = field(time_series=True)
        pet: Union[float, str] = field(time_series=True)
        extdp: Union[float, str] = field(time_series=True)
        extwc: Union[float, str] = field(time_series=True)
        ha: Union[float, str] = field(time_series=True)
        hroot: Union[float, str] = field(time_series=True)
        rootact: Union[float, str] = field(time_series=True)
        aux: tuple = field(default=(), shape=("auxiliary",))

    auxiliary: Optional[NDArray[np.str_]] = field(
        default=None,
        converter=attrs.converters.optional(to_array(np.str_)),
        block="options",
        optional=True,
        longname="keyword to specify aux variables",
    )
    auxmultname: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
        longname="name of auxiliary variable for multiplier",
    )
    boundnames: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    print_input: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="print input to listing file",
    )
    print_flows: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="print calculated flows to listing file",
    )
    save_flows: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="save well flows to budget file",
    )
    wc_file: Optional[Path] = path(
        default=None,
        converter=attrs.converters.optional(Path),
        block="options",
        optional=True,
        direction="out",
        keyword="water_content",
    )
    budget_file: Optional[Path] = path(
        default=None,
        converter=attrs.converters.optional(Path),
        block="options",
        optional=True,
        direction="out",
        keyword="budget",
    )
    budgetcsv_file: Optional[Path] = path(
        default=None,
        converter=attrs.converters.optional(Path),
        block="options",
        optional=True,
        direction="out",
        keyword="budgetcsv",
    )
    package_convergence_file: Optional[Path] = path(
        default=None,
        converter=attrs.converters.optional(Path),
        block="options",
        optional=True,
        direction="out",
        keyword="package_convergence",
    )
    ts_file: Optional[list[Path]] = path(
        default=None,
        converter=attrs.converters.optional(to_list(Path)),
        block="options",
        optional=True,
        direction="in",
        keyword="ts6",
    )
    obs_file: Optional[Path] = path(
        default=None,
        converter=attrs.converters.optional(Path),
        block="options",
        optional=True,
        direction="in",
        keyword="obs6",
    )
    mover: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    simulate_et: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    linear_gwet: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="use linear evapotranspiration",
    )
    square_gwet: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="use square evapotranspiration",
    )
    simulate_gwseep: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="activate seepage",
    )
    unsat_etwc: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="use PET for theta greater than extwc",
    )
    unsat_etae: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="use root potential",
    )
    nuzfcells: Optional[int] = field(
        default=None,
        block="dimensions",
        longname="number of UZF cells",
    )
    ntrailwaves: Optional[int] = field(
        default=7,
        block="dimensions",
        longname="number of trailing waves",
    )
    nwavesets: Optional[int] = field(
        default=40,
        block="dimensions",
        longname="number of wave sets",
    )
    packagedata: Optional[list[Packagedata]] = field(
        default=None,
        block="packagedata",
        dim="nuzfcells",
    )
    _stress_period_data: Optional[dict[int, list[StressPeriodData]]] = field(
        alias="stress_period_data",
        default=None,
        repr=False,
        block="period",
        fill_forward=True,
    )


UzfPackagedata = Uzf.Packagedata
UzfStressPeriodData = Uzf.StressPeriodData
