# autogenerated file, do not modify
from pathlib import Path
from typing import Optional, Union

import attrs

from flopy4.mf6._types import _optional_path
from flopy4.mf6.package import Package
from flopy4.mf6.row import Row
from flopy4.mf6.spec import field, path


@attrs.define(kw_only=True, slots=False)
class Vsc(Package):
    @attrs.define
    class PackagedataRow(Row):
        iviscspec: int = field(pk=True)
        dviscdc: float
        cviscref: float
        modelname: Union[float, str]
        auxspeciesname: Union[float, str]
        aux: tuple = ()

    viscref: Optional[float] = field(
        default=1.0,
        block="options",
        optional=True,
    )
    temperature_species_name: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
    )
    thermal_formulation: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
    )
    thermal_a2: Optional[float] = field(
        default=10.0,
        block="options",
        optional=True,
    )
    thermal_a3: Optional[float] = field(
        default=248.37,
        block="options",
        optional=True,
    )
    thermal_a4: Optional[float] = field(
        default=133.15,
        block="options",
        optional=True,
    )
    viscosity_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        optional=True,
        inout="fileout",
    )
    nviscspecies: Optional[int] = field(
        default=None,
        block="dimensions",
    )
    packagedata: Optional[list[PackagedataRow]] = field(
        default=None,
        block="packagedata",
        auto_from="packagedata",
    )


VscPackagedataRow = Vsc.PackagedataRow
