# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

import attrs
import numpy as np

from flopy4.mf6.package import Package
from flopy4.utils import to_path


@attrs.define(kw_only=True, slots=False)
class Vsc(Package):
    viscref: Optional[float] = attrs.field(
        default="1.0",
        metadata={
            "dfn_block": "options",
            "dfn_type": "double",
            "optional": True,
        },
    )  # type: ignore[assignment]
    temperature_species_name: Optional[str] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "options",
            "dfn_type": "string",
            "optional": True,
        },
    )
    thermal_formulation: Optional[str] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "options",
            "dfn_type": "string",
            "optional": True,
        },
    )
    thermal_a2: Optional[float] = attrs.field(
        default="10.",
        metadata={
            "dfn_block": "options",
            "dfn_type": "double",
            "optional": True,
        },
    )  # type: ignore[assignment]
    thermal_a3: Optional[float] = attrs.field(
        default="248.37",
        metadata={
            "dfn_block": "options",
            "dfn_type": "double",
            "optional": True,
        },
    )  # type: ignore[assignment]
    thermal_a4: Optional[float] = attrs.field(
        default="133.15",
        metadata={
            "dfn_block": "options",
            "dfn_type": "double",
            "optional": True,
        },
    )  # type: ignore[assignment]
    viscosity_file: Optional[Path] = attrs.field(
        default=None,
        converter=lambda v: None if v is None else to_path(v),
        metadata={
            "dfn_block": "options",
            "dfn_type": "record",
            "optional": True,
            "inout": "fileout",
        },
    )
    nviscspecies: Optional[int] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "dimensions",
            "dfn_type": "integer",
        },
    )
    packagedata: Optional[np.recarray] = attrs.field(
        default=None,
        metadata={
            "dfn_block": "packagedata",
            "schema": "__packagedata_schema__",
            "auto_from": "packagedata",
        },
    )
    __packagedata_schema__: ClassVar[list[dict]] = [
        {
            "name": "iviscspec",
            "dfn_type": "integer",
            "role": "feature_id",
        },
        {
            "name": "dviscdc",
            "dfn_type": "double",
            "role": "value",
        },
        {
            "name": "cviscref",
            "dfn_type": "double",
            "role": "value",
        },
        {
            "name": "modelname",
            "dfn_type": "string",
            "role": "value",
            "dtype": "np.object_",
        },
        {
            "name": "auxspeciesname",
            "dfn_type": "string",
            "role": "value",
            "dtype": "np.object_",
        },
    ]

    packagedata_dtype: np.dtype = attrs.field(init=False, factory=lambda: np.dtype([]))
    period_dtype: np.dtype = attrs.field(init=False, factory=lambda: np.dtype([]))
