# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional, Union

import attrs
import numpy as np

from flopy4.mf6._types import _optional_path
from flopy4.mf6.package import Package
from flopy4.mf6.schema import Column, Schema
from flopy4.mf6.spec import field, path


@attrs.define(kw_only=True, slots=False)
class Vsc(Package):
    viscref: Optional[float] = field(
        default=1.0,
        block="options",
        dfn_type="double",
        optional=True,
    )
    temperature_species_name: Optional[str] = field(
        default=None,
        block="options",
        dfn_type="string",
        optional=True,
    )
    thermal_formulation: Optional[str] = field(
        default=None,
        block="options",
        dfn_type="string",
        optional=True,
    )
    thermal_a2: Optional[float] = field(
        default=10.0,
        block="options",
        dfn_type="double",
        optional=True,
    )
    thermal_a3: Optional[float] = field(
        default=248.37,
        block="options",
        dfn_type="double",
        optional=True,
    )
    thermal_a4: Optional[float] = field(
        default=133.15,
        block="options",
        dfn_type="double",
        optional=True,
    )
    viscosity_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        dfn_type="record",
        optional=True,
        inout="fileout",
    )
    nviscspecies: Optional[int] = field(
        default=None,
        block="dimensions",
        dfn_type="integer",
    )
    packagedata: Optional[np.recarray] = field(
        default=None,
        block="packagedata",
        schema="__packagedata_schema__",
        auto_from="packagedata",
    )

    class _PackagedataSchema(Schema):
        iviscspec = Column("iviscspec", role="feature_id", dfn_type="integer")
        dviscdc = Column("dviscdc", role="value", dfn_type="double")
        cviscref = Column("cviscref", role="value", dfn_type="double")
        modelname = Column("modelname", role="value", dfn_type="string", dtype="np.object_")
        auxspeciesname = Column(
            "auxspeciesname",
            role="value",
            dfn_type="string",
            dtype="np.object_",
        )

    __packagedata_schema__: ClassVar[type[Schema]] = _PackagedataSchema

    @attrs.define
    class PackagedataRow:
        iviscspec: int
        dviscdc: float
        cviscref: float
        modelname: Union[float, str]
        auxspeciesname: Union[float, str]

        def __iter__(self):
            yield self.iviscspec
            yield self.dviscdc
            yield self.cviscref
            yield self.modelname
            yield self.auxspeciesname

    packagedata_dtype: np.dtype = attrs.field(init=False, factory=lambda: np.dtype([]))
    period_dtype: np.dtype = attrs.field(init=False, factory=lambda: np.dtype([]))


VscPackagedataRow = Vsc.PackagedataRow
