# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

import attrs

from flopy4.mf6._types import ArrayLike, _optional_path
from flopy4.mf6.package import Package
from flopy4.mf6.spec import field, path


@attrs.define(kw_only=True, slots=False)
class Welg(Package):
    multi_package: ClassVar[bool] = True

    readarraygrid: bool = field(
        default=True,
        block="options",
        dfn_type="keyword",
    )
    auxiliary: Optional[list[str]] = field(
        default=None,
        block="options",
        dfn_type="string",
        shape=(),
        optional=True,
    )
    auxmultname: Optional[str] = field(
        default=None,
        block="options",
        dfn_type="string",
        optional=True,
    )
    print_input: bool = field(
        default=False,
        block="options",
        dfn_type="keyword",
        optional=True,
    )
    print_flows: bool = field(
        default=False,
        block="options",
        dfn_type="keyword",
        optional=True,
    )
    save_flows: bool = field(
        default=False,
        block="options",
        dfn_type="keyword",
        optional=True,
    )
    auto_flow_reduce: Optional[float] = field(
        default=None,
        block="options",
        dfn_type="double",
        optional=True,
    )
    afrcsv_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        dfn_type="record",
        optional=True,
        inout="fileout",
    )
    flow_reduction_length: bool = field(
        default=False,
        block="options",
        dfn_type="keyword",
        optional=True,
    )
    obs_file: Optional[Path] = path(
        default=None,
        converter=_optional_path,
        block="options",
        dfn_type="record",
        optional=True,
        inout="filein",
    )
    mover: bool = field(
        default=False,
        block="options",
        dfn_type="keyword",
        optional=True,
    )
    export_array_netcdf: bool = field(
        default=False,
        block="options",
        dfn_type="keyword",
        optional=True,
    )
    maxbound: Optional[int] = field(
        default=0,
        block="dimensions",
        dfn_type="integer",
        optional=True,
        auto_from="stress_period_data",
    )
    q: Optional[ArrayLike] = field(
        default=None,
        block="period",
        reader="readarray",
        dfn_type="double",
        layered=True,
    )
    aux: Optional[ArrayLike] = field(
        default=None,
        block="period",
        reader="readarray",
        dfn_type="double",
        layered=True,
    )
