# autogenerated file, do not modify
from pathlib import Path
from typing import ClassVar, Optional

import attrs
import numpy as np
from numpy.typing import NDArray

from flopy4.mf6._types import ARRAY_EQ, FloatArrayLike, to_str_array
from flopy4.mf6.package import Package
from flopy4.mf6.spec import child, field, path
from flopy4.mf6.utl.obs import Obs


@attrs.define(kw_only=True, slots=False)
class Welg(Package):
    dfn_name: ClassVar[str] = "gwf-welg"

    multi_package: ClassVar[bool] = True

    observations: ClassVar[dict[str, tuple[tuple[str, ...], ...]]] = {
        "to-mvr": (("cellid",), ("string",)),
        "wel": (("cellid",), ("string",)),
        "wel-reduction": (("cellid",), ("string",)),
    }

    readarraygrid: bool = field(
        default=True,
        block="options",
        longname="use array-based grid input",
    )
    auxiliary: Optional[NDArray[np.str_]] = field(
        default=None,
        converter=to_str_array,
        eq=ARRAY_EQ,
        block="options",
        optional=True,
        longname="keyword to specify aux variables",
    )
    auxmultname: Optional[str] = field(
        default=None,
        block="options",
        optional=True,
        longname="name of auxiliary variable for multiplier",
    )
    print_input: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="print input to listing file",
    )
    print_flows: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="print calculated flows to listing file",
    )
    save_flows: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="save well flows to budget file",
    )
    auto_flow_reduce: Optional[float] = field(
        default=None,
        block="options",
        optional=True,
        longname="cell fractional thickness for reduced pumping",
    )
    afrcsv_file: Optional[Path] = path(
        default=None,
        converter=attrs.converters.optional(Path),
        block="options",
        optional=True,
        direction="out",
        keyword="auto_flow_reduce_csv",
    )
    flow_reduction_length: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="flow reduction length keyword",
    )
    obs: Optional[Obs] = child(block="options", keyword="obs6", direction="in")
    mover: bool = field(
        default=False,
        block="options",
        optional=True,
    )
    export_array_netcdf: bool = field(
        default=False,
        block="options",
        optional=True,
        longname="export array variables to netcdf output files.",
    )
    maxbound: Optional[int] = field(
        default=None,
        block="dimensions",
        optional=True,
        longname="maximum number of wells in any stress period",
    )
    q: Optional[dict[int, FloatArrayLike | None]] = field(
        default=None,
        block="period",
        shape=("nodes",),
        layered=True,
        netcdf=True,
        fill_forward=True,
    )
    aux: Optional[dict[int, dict[str, FloatArrayLike]]] = field(
        default=None,
        block="period",
        shape=("nodes",),
        layered=True,
        netcdf=True,
        fill_forward=True,
        fk="options.auxiliary",
    )
