name: CI
on:
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'
  pull_request:
    branches:
      - main
      - develop
    paths-ignore:
      - '**.md'
      - '.gitignore'
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.9.6
        with:
          pixi-version: v0.72.0
          environments: dev
          activate-environment: true

      - name: Lint check
        run: pixi run ruff check

      - name: Format check
        run: pixi run ruff format --check

      - name: Type check
        run: pixi run mypy flopy4

      - name: Spell check
        run: pixi run codespell

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.9.6
        with:
          pixi-version: v0.72.0
          environments: dev
          activate-environment: true

      - name: Print package version
        run: python -c "from flopy4 import version; print(version.__version__)"

      - name: Build package
        run: pixi run build

  test:
    name: Test
    needs:
      - build
      - lint
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python: [ "311", "312", "313" ]
    env:
      GCC_V: 11
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install nightly build
        uses: modflowpy/install-modflow-action@v1
        with:
          repo: modflow6-nightly-build

      - name: Install PROJ, HDF5, NetCDF (macOS)
        if: runner.os == 'macOS'
        run: brew install proj hdf5 netcdf

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.9.6
        with:
          pixi-version: v0.72.0
          environments: test${{ matrix.python }}
          activate-environment: true

      # temporary. devtools 2.x will autosync, but 1.x needs opt-in.
      - name: Sync devtools
        run: pixi run mf sync

      - name: Run tests
        run: |
          pixi run python -m ipykernel install --name flopy4 --user
          pixi run test
