name: Extended
on:
  push:
    branches:
      - develop
    paths-ignore:
      - '**.md'
      - '.gitignore'
  pull_request:
    branches:
      - develop
    paths-ignore:
      - '**.md'
      - '.gitignore'
  workflow_dispatch:

jobs:
  test_extended:
    name: Test Extended (${{ matrix.os }}, ${{ matrix.env }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        env: [test311, test312, test313]
    env:
      REPOS_PATH: ${{ github.workspace }}

    steps:

      - name: Checkout pyphoenix-project
        uses: actions/checkout@v4

      - name: Checkout modflow6
        uses: actions/checkout@v4
        with:
          repository: MODFLOW-USGS/modflow6
          path: modflow6
          ref: develop

      - name: Setup pixi (modflow6)
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: v0.41.1
          manifest-path: modflow6/pixi.toml

      - name: Build extended modflow6
        uses: ./.github/actions/build-extended-mf6

      - name: Add modflow6 bin to PATH
        shell: bash
        run: echo "$GITHUB_WORKSPACE/modflow6/bin" >> $GITHUB_PATH

      - name: Setup pixi (pyphoenix)
        shell: bash
        run: pixi install --environment ${{ matrix.env }}

      - name: Run example tests
        env:
          MF6_EXTENDED: "true"
        run: pixi run --environment ${{ matrix.env }} pytest test/test_examples.py -v
